### ISSUE TITLE
guardrails-2.json SCP blocks all SSM Parameters Deletion

### ISSUE THREAD

**Issue by gmeab** [awslabs/landing-zone-accelerator-on-aws#100]
**Describe the bug**
The SCP guardrails-2.json is using a wildcard to stop any SSM parameters being deleted, the resource should be filtered to protect just LZA parameters 

```
"Sid": "PreventSSMModification",
      "Effect": "Deny",
      "Action": ["ssm:DeleteParameters"],
      "Resource": "*",
      "Condition": {
        "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:${PARTITION}:iam::*:role/${ACCELERATOR_PREFIX}-*",
            "arn:${PARTITION}:iam::*:role/AWSControlTowerExecution",
            "arn:${PARTITION}:iam::*:role/cdk-accel-*"
          ]
        }
      }
    },
```
Looking at the parameters, it looks like it could be restricted to **accelerator/AWSAccelerator-***

**To Reproduce**
Apply the SCP to a OU

**Expected behavior**
The SCP should protect the LZA install but not stop routine actions e.g. deleting SSM parameters.

**Comment by dbaileyut** [comment]
Related: I could be mistaken but it doesn't seem to protect against deleting parameters one by one with DeleteParameter (not plural). "ssm:DeleteParameter" should probably be added to the action array.

**Comment by awsclemj** [comment]
Hello, this SCP statement [has been updated](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/c16686e7476371b5e184c473db87dd3f61117732/reference/sample-configurations/lza-sample-config/service-control-policies/guardrails-2.json#L114) in our latest release. Please note the variable used will only work as of v1.5.0 deployments. Thank you for your feedback and support of the LZA solution! I will close this as resolved.
