### ISSUE TITLE
Enable acceleration on VPN connections

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#102]
there is an option when manually creating to enable acceleration on a site to site vpn via console 

i tried to just add it in the code. though the code ran successfully it did not enable as expected 

is this a feature that is not available?

here is the code snippet 

    vpnConnections:
    - name: XXXXX-vpn
      transitGateway: Network-Main
      routeTableAssociations:
        - Network-Main-Core
      routeTablePropagations:
        - Network-Main-Core
      staticRoutesOnly: true
      tunnelSpecifications:
        - tunnelInsideCidr: 169.254.200.0/30
          preSharedKey: Key1-bmXXX4356-b5WvZP
        - tunnelInsideCidr: 169.254.200.100/30
          preSharedKey: Key2-bmXXX4356-dYyhBi
    - name: bmhcc-vpn-Acceleration
      transitGateway: Network-Main
      routeTableAssociations:
        - Network-Main-Core
      routeTablePropagations:
        - Network-Main-Core
      staticRoutesOnly: true
      enableAcceleration: true
      tunnelSpecifications:
        - tunnelInsideCidr: 169.254.200.0/30
          preSharedKey: Key1-bmXXX4356-b5WvZP
        - tunnelInsideCidr: 169.254.200.100/30
          preSharedKey: Key2-bmXXXc4356-dYyhBi

**Comment by awsclemj** [comment]
Hello,

A feature enhancement for advanced VPN options has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
