### ISSUE TITLE
Multi region deployment request 

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#103]
I am not sure if this is a miss on my side to get it to deploy in multiple regions or its a feature that is not available just yet but the ability to deploy this as multi region would be super helpful 

following something like this from AWS 
https://www.wellarchitectedlabs.com/reliability/200_labs/200_deploy_and_update_cloudformation/6_multi_region_deploy/

and or this

https://docs.aws.amazon.com/solutions/latest/multi-region-infrastructure-deployment/template.html

**Comment by awsclemj** [comment]
Hello @frankscalzo, and thanks for reaching out to the LZA team!

I believe you are looking for the [`enabledRegions`](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#enabledRegions) property available in `global-config.yaml`. LZA is multi-region aware when this value is set to more than one region. Please note that any resources utilizing the `deploymentTargets` property will be automatically deployed to the secondary region if you do not have `excludedRegions` configured for those resources. Resources that use the `region` property (such as VPCs) will need to be defined in new configuration definitions in their respective config files to take advantage of the new region.

I hope this helps! Please let us know if there's anything more we can do to help on this issue.

**Comment by frankscalzo** [comment]
that was it i missed that since there i not a great spot for clear docs 

i had to disable/ ignore new region for  audit manager and detective while deploying thanks
