### ISSUE TITLE
email-smtp endpoint does not open port 587 for connectivity

### ISSUE THREAD

**Issue by tbmorris** [awslabs/landing-zone-accelerator-on-aws#119]
**Describe the bug**
When creating an interface endpoint in the network-config yaml file, a security group called interface_ep_https_sg is added to the endpoint interface when created.  The AWS Simple Email Service requires port 587 among the many available.  Need to have options to apply other security groups to endpoints.

**To Reproduce**
Create a interface endpoint on a VPC.

**Expected behavior**
Should be able to access the endpoint on the port configured.  In my case, it would be port 587.

**Please complete the following information about the solution:**

- [1.3.2 ] Version: [e.g. v1.1.0]
- [us-gov-west-1] Region: [e.g. us-east-1]

**Comment by awsclemj** [comment]
Hello, in v1.5.0 we have included a feature enhancement to allow custom security groups to be attached to interface endpoints. Please see the [documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.InterfaceEndpointServiceConfig.html#securityGroup) for more details.

I will mark this issue as resolved. Thanks for your support of the LZA!
