### ISSUE TITLE
Clean Up Code to not report Lambda in AWS Inspector Vulnerabilities 

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#120]
i recently enabled AWS Inspector2 manually and found that some of the code in the LZ has CWE violations.

Not sure if these can be addressed at this point i am doing an ignore 

all 2  are part of a lambda created by the project 

AWSAccelerator-InstallerSta-SolutionHelper

lines of code in the lambda are lines 42-44

CWE-117
CWE-79,80

did not know if this should be a bug or a security vulnerability so i am just putting here

**Comment by erwaxler** [comment]
Hi @frankscalzo , thanks for reporting these findings. I have a few questions so I can attempt to reproduce these findings in my environment:

- What version of the LZA were you running when these findings appeared?
- Were all three findings (CWE-117, CWE-79, and CWE-80) for that single section of code, lines 42-44?

**Comment by frankscalzo** [comment]
they are either resolved since the original deployment or suppressed but they are no longer coming up in my inspector

**Comment by nagmesh** [comment]
@frankscalzo Thank you for reporting that they are resolved.
