### ISSUE TITLE
can't deploy 

### ISSUE THREAD

**Issue by SergiyShevchenk** [awslabs/landing-zone-accelerator-on-aws#121]
yarn run v1.22.19
--
108 | $ /codebuild/output/src142/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage prepare --require-approval never --config-dir /codebuild/output/src142/src/s3/01 --partition aws
109 | 2023-04-06 15:36:39.440 \| info \| toolkit \| Executing cdk synth prepare
110 | (node:170) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
111 |  
112 | Please migrate your code to use AWS SDK for JavaScript (v3).
113 | For more information, check the migration guide at https://a.co/7PzMCcy
114 | (Use `node --trace-warnings ...` to show where the warning was created)
115 | 2023-04-06 15:37:17.559 \| info \| app \| Begin Accelerator CDK App
116 | (node:194) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
117 |  
118 | Please migrate your code to use AWS SDK for JavaScript (v3).
119 | For more information, check the migration guide at https://a.co/7PzMCcy
120 | (Use `node --trace-warnings ...` to show where the warning was created)
121 | 2023-04-06 15:37:17.712 \| error \| app \| You don't have permissions to access this resource.
122 | 2023-04-06 15:37:17.712 \| error \| toolkit \| AccessDeniedException: You don't have permissions to access this resource.
123 | 2023-04-06 15:37:17.727 \| error \| accelerator \| Runtime Error
124 | /codebuild/output/src142/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:52
125 | throw new Error('Synthesis failed');
126 | ^
127 |  
128 | Error: Synthesis failed
129 | at process.<anonymous> (/codebuild/output/src142/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:33:9)
130 | at process.emit (node:events:525:35)
131 | at process.emit (node:domain:489:12)
132 | at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src142/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
133 | at process._fatalException (node:internal/process/execution:149:25)
134 | Subprocess exited with error 7
135 | error Command failed with exit code 1.
136 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by roncanepa** [comment]
I'm not affiliated with AWS at all but the synthesis process needs credentials to access the environment.  I'd check that you have a valid session on the CLI and that the user/role you're using has high level admin privs.

**Comment by mavogel** [comment]
like this

```sh
# see if any credentials are set
env |grep AWS_
# test the access
aws sts get-caller-identity --no-cli-pager
```

**Comment by SergiyShevchenk** [comment]
everything passed with "green" no issues there

**Comment by awsclemj** [comment]
Hello @SergiyShevchenk, and thanks for your interest in Landing Zone Accelerator on AWS!

Our solution is deployed with an administrative role that the core pipeline CodeBuild project assumes in order to complete CDK synthesis, deploy mandatory custom resources to your management account, as well as describe your organizational and account structure. This role is deployed along with the **AWSAccelerator-PipelineStack** and you should be able to find it if you navigate to the AWS CloudFormation console in your management account and look at the **Resources** tab for that stack. It is prefixed with **AdminCdkToolkitRole**. 

I would verify that that role has not been modified outside of CloudFormation; it should have the AWS-managed **AdministratorAccess** attached to it. The only scenarios I can think of that would cause an access denied error at this stage of the pipeline is if this role has been modified in some way or replaced with a different role outside of CloudFormation. The solution is otherwise deployed with the necessary permissions to complete these activities.

I hope these troubleshooting steps are helpful! Please let us know if you continue running into errors after following this guidance.

**Comment by SergiyShevchenk** [comment]
[Container] 2023/05/01 18:31:28 Running command cd source
--
102 |  
103 | [Container] 2023/05/01 18:31:28 Running command cd packages/@aws-accelerator/accelerator
104 |  
105 | [Container] 2023/05/01 18:31:28 Running command if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi
106 |  
107 | [Container] 2023/05/01 18:31:28 Running command if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi
108 | yarn run v1.22.19
109 | $ /codebuild/output/src565/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage prepare --require-approval never --config-dir /codebuild/output/src565/src/s3/01 --partition aws
110 | 2023-05-01 18:31:31.054 \| info \| toolkit \| Executing cdk synth prepare
111 | (node:170) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
112 |  
113 | Please migrate your code to use AWS SDK for JavaScript (v3).
114 | For more information, check the migration guide at https://a.co/7PzMCcy
115 | (Use `node --trace-warnings ...` to show where the warning was created)
116 | 2023-05-01 18:32:10.244 \| info \| app \| Begin Accelerator CDK App
117 | (node:194) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
118 |  
119 | Please migrate your code to use AWS SDK for JavaScript (v3).
120 | For more information, check the migration guide at https://a.co/7PzMCcy
121 | (Use `node --trace-warnings ...` to show where the warning was created)
122 | 2023-05-01 18:32:10.398 \| error \| app \| You don't have permissions to access this resource.
123 | 2023-05-01 18:32:10.398 \| error \| toolkit \| AccessDeniedException: You don't have permissions to access this resource.
124 | 2023-05-01 18:32:10.413 \| error \| accelerator \| Runtime Error
125 | /codebuild/output/src565/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:52
126 | throw new Error('Synthesis failed');
127 | ^
128 |  
129 | Error: Synthesis failed
130 | at process.<anonymous> (/codebuild/output/src565/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:33:9)
131 | at process.emit (node:events:525:35)
132 | at process.emit (node:domain:489:12)
133 | at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src565/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
134 | at process._fatalException (node:internal/process/execution:149:25)
135 | Subprocess exited with error 7
136 | error Command failed with exit code 1.
137 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
138 |  
139 | [Container] 2023/05/01 18:32:10 Command did not exit successfully if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi exit status 1
140 | [Container] 2023/05/01 18:32:10 Phase complete: BUILD State: FAILED
141 | [Container] 2023/05/01 18:32:10 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1
142 | [Container] 2023/05/01 18:32:10 Entering phase POST_BUILD
143 | [Container] 2023/05/01 18:32:10 Phase complete: POST_BUILD State: SUCCEEDED
144 | [Container] 2023/05/01 18:32:10 Phase context status code:  Message:

**Comment by SergiyShevchenk** [comment]
athe 

AWSAccelerator-PipelineStack-XXXXXXXX-us-east-1 | CREATE_COMPLETE, no issues there

**Comment by SergiyShevchenk** [comment]
Failed | 
COMMAND_EXECUTION_ERROR: Error while executing command: if [ ! -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --stage $ACCELERATOR_STAGE --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1 |

**Comment by SergiyShevchenk** [comment]
how would we identify the resource that there is no access to?

**Comment by SergiyShevchenk** [comment]
this is all related to the:
AWSAccelerator-ToolkitProject

**Comment by SergiyShevchenk** [comment]
role successfully created and attached two policies

**Comment by SergiyShevchenk** [comment]
awaiting for a new version to be released

**Comment by awsclemj** [comment]
For anyone that is monitoring this thread in the future, the root cause of the failure case here was due to the solution not being installed in the organization Management account.
