### ISSUE TITLE
Spelling error in test folder name.

### ISSUE THREAD

**Issue by HenrikStanley** [awslabs/landing-zone-accelerator-on-aws#125]
**Describe the bug**
The folder: 

`https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/source/packages/%40aws-accelerator/constructs/test/aws-budets`

Should properly be spelled "aws-budgets".

**To Reproduce**
Go to the folder path:
`http://landing-zone-accelerator-on-aws/source/packages/@aws-accelerator/constructs/test/aws-budets/`

**Expected behavior**
Folder is spelled the same as the verb and test case inside the folder `budgets`

**Please complete the following information about the solution:**
Not sure if any process could be made to lint the folder naming.

**Comment by aasimsayani** [comment]
Hi @HenrikStanley,

I wanted to inform you that we have fixed the name of the `aws-budgets` folder on your behalf. We'll leave this issue open until the next release where the name change will be reflected.

Thanks for your support and interest in the solution.

**Comment by erwaxler** [comment]
This has been fixed in our latest release, so I'll go ahead and close this issue. Thank you for your interest in the Landing Zone Accelerator!
