### ISSUE TITLE
Initial AWSAccelerator-Pipeline execution fails to run due to the staging bucket not allowing ACLs

### ISSUE THREAD

**Issue by jesseadams** [awslabs/landing-zone-accelerator-on-aws#127]
**Describe the bug**
Initial deployment of LZA following the Immersion Day guide (https://catalog.us-east-1.prod.workshops.aws/workshops/c295f289-9eec-419f-80d3-f56a98f57b58/en-US/lza-administrators/prerequisites/deploy-landing-zone-accelerator) fails without manual intervention.

During the `Bootstrap` step of the `AWSAccelerator-Pipeline` the `StagingBucket` resource update fails with `The bucket does not allow ACLs`. I updated the `PublicAccessBlockConfiguration` parameter from `true` to `false` and updated the stack, then tried again. It had no effect. I had to manually update the `StagingBucket` resource that was created to enable ACLs, thus creating drift, before the `Bootstrap` step would complete successfully. 

**To Reproduce**
1. Follow the steps in https://catalog.us-east-1.prod.workshops.aws/workshops/c295f289-9eec-419f-80d3-f56a98f57b58/en-US/lza-administrators/prerequisites/deploy-landing-zone-accelerator with the latest version (release/v1.3.2)
2. Wait until the AWSAccelerator-Pipeline runs
3. See the failure at the `Bootstrap` step

**Expected behavior**
I would have expected the `AWSAccelerator-Pipeline` to complete successfully for the first time, without manual intervention required.

**Please complete the following information about the solution:**

- [X] Version: 1.3.2
- [X] Region: us-east-2
- [X] Was the solution modified from the version published on this repository? No.
- [X] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No, but I'm not sure how this is related.
- [X] Were there any errors in the CloudWatch Logs? I did not check, I just looked at the CodeBuild and CloudFormation error messages.

**Comment by erwaxler** [comment]
Hey @jesseadams , thank you for your interest in LZA! This appears to be a result of the recent change in [default S3 behavior](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/). The team has implemented a fix that will be included in the next release, I will keep this issue open until that code is available.

**Comment by erwaxler** [comment]
@jesseadams @alexgabriel-ca For users encountering this error for new deployments, we have pushed the fix to the [development/v.1.3.3](https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/development/v.1.3.3) branch. This is a development branch so issues encountered are not covered by AWS Support, however for customers prioritizing speed this branch can be used to deploy before the next official release. We expect the next official release to occur in early May.

**Comment by erwaxler** [comment]
Hi @jacekhewko, we do not publicly disclose exact dates on our roadmap, if you work with your AWS Account Manager they can help you obtain more detailed information under NDA. 

To upgrade the solution, you would update your AWSAccelerator-InstallerStack CloudFormation Stack. Use the same template, but change the [Branch Name](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/step-1.-launch-the-stack.html) CloudFormation parameter to specify the new branch to pull from: `development/v.1.3.3`. 

Following the official release, you can follow the instructions [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/update-the-solution.html) to return to the official release branches.

**Comment by richardkeit** [comment]
This notification was published in December 2022 - https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

Please prioritize this - it essentially blocks **all new customers**

**Comment by awsclemj** [comment]
Hello,

[v1.4.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.4.0) of the solution has been officially released, which includes the S3 ACL fixes captured in this issue. 

I will be closing out this ticket. Thank you for your interest in Landing Zone Accelerator!

**Comment by jacekhewko** [comment]
hi @awsclemj ,

We've upated the Installer Stack to v1.4.0 successfully, but unfortunately when running the pipeline, it failed with new error on Deploy (Security_Resources) step:

```

Failed resources:
--
242 | AWSAccelerator-SecurityResourcesStack-163516910218-eu-west-2 \| 3:51:46 PM \| CREATE_FAILED        \| AWS::Config::DeliveryChannel       \| ConfigDeliveryChannel Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-103550689697-eu-west-2, unable to get s3 bucket acl. (Service: AmazonConfig; Status Code: 400; Error Code: InsufficientDeliveryPolicyException; Request ID: 1e8dd756-0ee2-444e-b204-0268647aada4; Proxy: null)
243 | SecurityResourcesStack.setupConfigRecorderAndDeliveryChannel (/codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/security-resources-stack.ts:546:32)
244 | \_ new SecurityResourcesStack (/codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/security-resources-stack.ts:140:10)
245 | \_ main (/codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:799:42)
246 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
247 | \_ async /codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1003:5
248 |  
249 | ❌  AWSAccelerator-SecurityResourcesStack-163516910218-eu-west-2 failed: Error: The stack named AWSAccelerator-SecurityResourcesStack-163516910218-eu-west-2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-103550689697-eu-west-2, unable to get s3 bucket acl. (Service: AmazonConfig; Status Code: 400; Error Code: InsufficientDeliveryPolicyException; Request ID: 1e8dd756-0ee2-444e-b204-0268647aada4; Proxy: null)
250 | at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src873/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
251 | at runMicrotasks (<anonymous>)
252 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
253 | at async deployStack (/codebuild/output/src873/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
254 | at async /codebuild/output/src873/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:39:11
255 | at async run (/codebuild/output/src873/src/s3/00/source/node_modules/p-queue/dist/index.js:163:29)
256 |  
257 | ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-SecurityResourcesStack-163516910218-eu-west-2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-103550689697-eu-west-2, unable to get s3 bucket acl. (Service: AmazonConfig; Status Code: 400; Error Code: InsufficientDeliveryPolicyException; Request ID: 1e8dd756-0ee2-444e-b204-0268647aada4; Proxy: null)
258 | at deployStacks (/codebuild/output/src873/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
259 | at runMicrotasks (<anonymous>)
260 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
261 | at async CdkToolkit.deploy (/codebuild/output/src873/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
262 | at async Function.execute (/codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:312:9)
263 | at async Promise.all (index 0)
264 | at async Function.run (/codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:565:9)
265 | at async /codebuild/output/src873/src/s3/00/source/packages/@aws-accelerator/accelerator/cdk.ts:100:3
266 | 2023-05-09 15:52:12.136 \| error \| toolkit \| Stack Deployments Failed: Error: The stack named AWSAccelerator-SecurityResourcesStack-163516910218-eu-west-2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-103550689697-eu-west-2, unable to get s3 bucket acl. (Service: AmazonConfig; Status Code: 400; Error Code: InsufficientDeliveryPolicyException; Request ID: 1e8dd756-0ee2-444e-b204-0268647aada4; Proxy: null)
267 | Deployment failed
268 | error Command failed with exit code 1.
269 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
270 |  
271 | [Container] 2023/05/09 15:52:12 Command did not exit successfully yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out exit status 1
272 | [Container] 2023/05/09 15:52:12 Phase complete: BUILD State: FAILED
273 | [Container] 2023/05/09 15:52:12 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out. Reason: exit status 1
274 | [Container] 2023/05/09 15:52:12 Entering phase POST_BUILD
275 | [Container] 2023/05/09 15:52:12 Phase complete: POST_BUILD State: SUCCEEDED
276 | [Container] 2023/05/09 15:52:12 Phase context status code:  Message:

```
