### ISSUE TITLE
landing-zone-accelerator-on-aws/reference/sample-configurations/aws-best-practices/backup-policies/org-backup-policies.json file has a JSON error

### ISSUE THREAD

**Issue by bullittbirant** [awslabs/landing-zone-accelerator-on-aws#13]
**Describe the bug**
Line 173 and 176 of the landing-zone-accelerator-on-aws/reference/sample-configurations/aws-best-practices/backup-policies/org-backup-policies.json file has to switch since delete after days must be greater than move to cold storage after days.

**To Reproduce**
Edit the file.

**Expected behavior**
The policy is created but gives the rror when you open the console.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by erwaxler** [comment]
Hello, thank you for reporting this bug. Closing the ticket as this has been resolved.
