### ISSUE TITLE
Ability to run CDK in a different account than Management Account

### ISSUE THREAD

**Issue by rverma-dev** [awslabs/landing-zone-accelerator-on-aws#139]
**Is your feature request related to a problem? Please describe.**
We are building internal saas tooling and want to offload network and security management for the saas control pane account to CDK. 

**Describe the feature you'd like**
Ability to see and manage accounts config outside of the management account, The idea is that the bootstrapped code commit repo should be outside the management account. Call control tower/organization apis using assume role to management

**Additional context**
1. We tried with specifying accountIDs to skip ou apis but still stuck at prepare stack synthesis.
2. We tried OU delegation to the landing zone account, however landing zone consider the assets and everything in management account while it bootstrap them in the current account

**Comment by erwaxler** [comment]
Hi @rverma-dev , thanks for reaching out to the Landing Zone Accelerator team! I have created an issue in the team's backlog and will update this issue accordingly.

**Comment by awsclemj** [comment]
Hello,

A feature enhancement related to this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). Please see the [documentation](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/external-pipeline-deployment.html) for more details. I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
