### ISSUE TITLE
Sending Guardduty findings to Log archive account

### ISSUE THREAD

**Issue by kumaryts** [awslabs/landing-zone-accelerator-on-aws#14]
**Describe issue**
In manifest settings, there is no option to send Guardduty findings to S3 bucket in Log Archive account. When logging is enable for Guardduty, logs are sent to S3 bucket in Audit account.

**Expected behavior**
There should be an option to define account id to store logs in define account's S3 bucket.

**Comment by erwaxler** [comment]
Hello, thank you for your interest in the Landing Zone Accelerator on AWS. As of version 1.3.0, GuardDuty logs are sent to the central logging bucket located in the Log Archive account.
