### ISSUE TITLE
Change HOME_REGION in global config but AWSAccelerator pipeline still get stuck with us-east-1 at Account stage

### ISSUE THREAD

**Issue by quangchustudy** [awslabs/landing-zone-accelerator-on-aws#140]
**Describe the bug**
![image](https://user-images.githubusercontent.com/125671399/236611695-9b00bd07-2bee-493f-a47d-5a44c0b2331e.png)

**To Reproduce**
Use the Region selector in the console navigation bar to choose "ap-southeast-1" to deploy the cloud formation template file from the beginning.
Take a look at codepipeline at the Account stage

**Expected behavior**
Expect successfully with using "ap-southeast-1" not us-east-1

**Please complete the following information about the solution:**

- [ ] Version: 1.4.0

SO0199-pipeline

- [ ] Region: ap-southeast-1

**Screenshots**
![image](https://user-images.githubusercontent.com/125671399/236603461-42d7dcec-b913-4851-8c73-d9bd0d68fe51.png)

**Additional context**

**Comment by gavinying** [comment]
I had exactly the same issue, thanks for raising it.

**Comment by awsclemj** [comment]
Hello, and thank you for your interest in Landing Zone Accelerator on AWS! 

There are some API calls for global services that must be completed in us-east-1, specifically AWS Organizations API calls in this solution. The Accounts stage is always deployed to us-east-1 for this reason. 

us-east-1 is bootstrapped when the solution is installed. If you have any SCPs or region deny that block actions in us-east-1, it’s possible the region may not have been bootstrapped properly. You should see a CDKToolkit stack in that region once the pipeline has completed. If you do not, can you verify you do not have any region deny settings in place for us-east-1 and run the Installer CodePipeline again? The Install stage in that pipeline should bootstrap us-east-1 for you.  

More info on regional endpoints for AWS Organizations: https://docs.aws.amazon.com/general/latest/gr/ao.html

Thank you! Please let us know of this resolves your issue.

**Comment by quangchustudy** [comment]
Hi @awsclemj , @gavinying 

Issue already resolved and you're right for "The Accounts stage is always deployed to us-east-1".
I got stuck with this problem since I did a clean-up (including s3 bucket cdk-accel-assets-xxxxxxx-us-east-1 but still keep the cloudformation of CDKToolkit stack on us-east-1) for the last deployed in wrong region us-east-1 while I setup landing zone with control tower as [https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html](prerequisites) => error happened at Account Stage.

And I solved as following:
- Deleted the old CDKToolkit stack on us-east-1
- Trigger release change to run AWSAccelerator-Pipeline again then you can see the CDKToolkit will be created on us-east-1
![image](https://user-images.githubusercontent.com/125671399/236631747-729f2d53-cb40-4253-929e-6895bb379801.png)
Pls noted: above CDKToolkit of Account on us-east-1 is different with CDToolkit on desired region 
![image](https://user-images.githubusercontent.com/125671399/236631949-17791fbb-2b30-45d1-988b-d59db1f59e28.png)
 
Thank you.

**Comment by gavinying** [comment]
@awsclemj @quangchustudy Unfortunately, I still have this issue. 
- the problem is `AWSAccelerator-Pipeline` seems not creating `AWSAccelerator-CDKToolkit` stack in `us-east-1` region (ap-southeast-1 region successfully created stacks). 
- I have already added `us-east-1` to allowed region;
- I have cleaned up S3 and cloudwatch in both regions before I run `AWSAccelerator-Pipeline`

My question is, 
- is `AWSAccelerator-CDKToolkit` stack in `us-east-1` region supposed to be created during `Prepare` stage of `AWSAccelerator-Pipeline`? Why I couldn't see any logs about creating stacks in `us-east-1` region while the stage succeded? 

![2023-05-08_11-50](https://user-images.githubusercontent.com/10823762/236730625-4802f291-9448-4e9e-a693-0a64c16633b3.png)
![2023-05-08_11-52](https://user-images.githubusercontent.com/10823762/236730637-e326f10f-8d7a-4255-9540-f18dd0142065.png)
![2023-05-08_11-54](https://user-images.githubusercontent.com/10823762/236730646-5170c9d0-6fa4-4ef2-a474-48950e1c2ca4.png)

**Comment by awsclemj** [comment]
Hello @gavinying,

us-east-1 is bootstrapped during the `Install` stage of `AWSAccelerator-Installer` pipeline. I’d suggested manually releasing that pipeline once again if you have recently made edits to your region deny settings and do not see the stack created. 

Thanks!

**Comment by gavinying** [comment]
Hi @awsclemj , I have re-run the `AWSAccelerator-Installer` pipeline just now, it completed without error, but I still didn't see any messages about creating stacks in `us-east-1` region in the logs. I have attached logs for your reference. 
[log.txt](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/11426222/log.txt)
Any other suggestion? thanks.

**Comment by awsclemj** [comment]
Based on this log message, it appears your global region has been modified:

`Container] 2023/05/09 00:42:17 Running command if ! aws cloudformation describe-stacks --stack-name AWSAccelerator-CDKToolkit --region ap-southeast-1; then BOOTSTRAPPED_GLOBAL="no"; fi`

The global region is defined [here] in our installer template, so it must have been modified externally. We strongly advise against modifying the source code of LZA, as it may lead to unexpected failures of the core engine. I would suggest updating your Installer stack using an unmodified template so us-east-1 is bootstrapped.

Thanks!

**Comment by gavinying** [comment]
@awsclemj Awesome, you saved my day, thank you so much!
