### ISSUE TITLE
Enhancement to add support for other VCS for accelerator configuration repo

### ISSUE THREAD

**Issue by DonthineniSagar** [awslabs/landing-zone-accelerator-on-aws#141]
**Is your feature request related to a problem? Please describe.**
It will be nice to have an option to store the aws accelerator configuration files in other supported code repos like Github and bitbucket etc. Currently i do not see an option while deploying the installer stack, it only asks existing code commit repo name or creates a default repo.
**Describe the feature you'd like**
It will be nice to have an option to store the aws accelerator configuration files in other supported code repos like Github and bitbucket etc.
**Additional context**

**Comment by bo1984** [comment]
Hello!

Thank you for reaching out regarding this feature request. By default, we do not provide alternative methods for other source repositories for your LZA configuration as you noted. I have placed an internal feature request on your behalf that the team will evaluate for a future release.

In the meantime, as a workaround, you can mirror your source repos (GitHub or BitBucket) to AWS CodeCommit for configuration management. I will leave this issue open in the meantime to keep track of your feature request.

**Comment by awsclemj** [comment]
Hello, we understand that users may want more flexibility for upstream repositories. However, at this time the LZA team is not evaluating additional sources for the configuration or source code repositories, as these connections to CodePipeline require the CodeStar service which is not currently available in all regions and partitions. Including these options would limit the number of regions our solution is supported in.

As discussed in this thread, a workaround is to automate the mirroring of your configuration changes between your repository of choice and the solution-provided CodeCommit repository.

Thank you for your support of the LZA solution! I will mark this issue as resolved, but please don’t hesitate to reach out with additional feedback.
