### ISSUE TITLE
Deployment of AWSAccelerator-Pipeline failing due to Insufficient delivery policy to Central Logging s3 bucket in LogArchive Account

### ISSUE THREAD

**Issue by ckiernanTA** [awslabs/landing-zone-accelerator-on-aws#142]
**Describe the bug**
When running the AWSAccelerator-Pipeline the stack "AWSAccelerator-SecurityResourcesStack-[Central-Acc-Number]-[Region]" fails to deploy with this output in codebuild:

`AWSAccelerator-SecurityResourcesStack-[Central-Acc-Number]-[Region] | 11/14 | 11:16:43 AM | CREATE_FAILED        | AWS::Config::DeliveryChannel       | ConfigDeliveryChannel Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-[LogArchive-Acc-Number]-[Region], unable to get s3 bucket acl. (Service: AmazonConfig; Status Code: 400; Error Code: InsufficientDeliveryPolicyException; Request ID: [Removed]; Proxy: null)`

The same error is produced in CloudTrail, CloudWatch and CloudFormation

**To Reproduce**
Follow the guide for control tower here: https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/prerequisites/aws-control-tower-deployment
Then Follow the Guide for LZA here: https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/prerequisites/deploy-landing-zone-accelerator

**Expected behavior**
The Stack to be created without issues and the next substep in the deployment to be triggered

**Please complete the following information about the solution:**

- [x] Version: v1.4.0
- [x] Region: eu-west-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes,  but this doesn't seem applicable to my issue.
- [x] Were there any errors in the CloudWatch Logs? only the error I mentioned above

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ckiernanTA** [comment]
I had originally named the wrong sub-account in this issue, I've corrected this now.

**Comment by thetechbender** [comment]
@ckiernanTA, can you provide more info about how you fixed this issue? I am running into the same error on a new deployment of LZA v1.4.0.
`Insufficient delivery policy to s3 bucket: aws-accelerator-central-logs-[LogArchive-Acc-Number]-[Region], unable to get s3 bucket acl.`

**Comment by ckiernanTA** [comment]
@thetechbender I haven't been able to fix it yet myself. I've found an example of this working at the previous version 1.3.2 though while digging. It looks like the bucket policy is basically unchanged so I doubt the bucket is the source of the problem (I could still be wrong though). I think the problem lies with the ConfigDeliveryChannel policy, but that's with a limited understanding of what changed between version, again I could be wrong.

**Comment by ckiernanTA** [comment]
@thetechbender  and anyone else who hits this same issue, We've found that by running v1.4.0 until hitting the Review stage, then denying the next step, then switching back to v1.3.2 and running the deployment again seems to get us past this point. It's not a clean workaround, but it does the job for now until this is picked up or fixed.

**Comment by awsclemj** [comment]
Hello, and thank you for reporting this! We are aware of the issue and are planning a patch release to fix this along with other issues in 1.4.0. We will keep you updated when that new release has been published.

We appreciate your interest and support of Landing Zone Accelerator!

**Comment by awsclemj** [comment]
Hello, this issue has been fixed in [v1.4.1](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.4.1). Thanks again for your bug report! I will go ahead and mark this issue as completed.
