### ISSUE TITLE
Pipeline Execution Failing in Logging

### ISSUE THREAD

**Issue by rockywong-nl** [awslabs/landing-zone-accelerator-on-aws#155]
Describe the bug

Recently, AWS launch Control Tower in Hong Kong Region(ap-east-1). I tried to deploy the Landing Zone Accelerator Pipeline and during the execution, logging cloudformation deployment is failed because of SDK error on Lambda function "CustomSsmGetParameterValueCustomResourceProviderHandler":

Received response status [FAILED] from custom resource. Message returned: UnrecognizedClientException: The security token included in the request is invalid at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: 7bda202e-2182-42fa-9d3c-c60d33fc1b6d)

To Reproduce
Deploy the Landing Zone Accelerator in Hong Kong Region (ap-east-1) and run the pipeline with default configurations.

Expected behavior
The Lambda functions can assume the role in LogArchive account and obtain the ssm parameter value.

-  Version: 1.40 and 1.41
- Region: ap-east-1

![Screenshot 2023-05-19 at 2 36 05 PM](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/96033832/6fdcc901-4490-4548-a5d9-0502f3266895)

**Comment by luke-dau** [comment]
This bug has re-appeared for:

- Version: 1.4.3
- Opt-In region: ap-southeast-4 (Melbourne)

`AWSAccelerator-LoggingStack-*****-ap-southeast-4 | 12:49:56 AM | CREATE_FAILED | Custom::SsmGetParameterValue | LookupCentralSnsKeyArnParameter/Resource/Default (LookupCentralSnsKeyArnParameter7F2E9F10) Received response status [FAILED] from custom resource. Message returned: UnrecognizedClientException: The security token included in the request is invalid 
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27) 
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) 
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) 
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) 
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) 
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: f4e315e1-7fec-45ea-8269-a2cd654fdf65) 
new CustomResource (/codebuild/output/src521/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823) `

**Comment by nagmesh** [comment]
Please look at the workaround in #269.
We are working on a feature to update the accounts with v2 token which should be available in future release.
