### ISSUE TITLE
[Enhancement] SCP update to accommodate aws-portal service prefix deprecation #1144

### ISSUE THREAD

**Issue by vic614** [awslabs/landing-zone-accelerator-on-aws#157]
**Is your feature request related to a problem? Please describe.**

AWS has announced the deprecation of service prefix `aws-portal` (July 6, 2023,). https://aws.amazon.com/blogs/aws-cloud-financial-management/changes-to-aws-billing-cost-management-and-account-consoles-permissions/

`aws-portal` is currently being used in multiple SCPs under `reference/sample-configurations/aws-best-practices-cccs-medium/config/service-control-policies`. 
1. LZA-Guardrails-Sandbox.json
2. LZA-Guardrails-Sensitive.json
3. LZA-Guardrails-Unclass.json

**Describe the feature you'd like**

Update the SCPs affected. 

**Additional context**

N/A

**Comment by erwaxler** [comment]
Hi @vic614 , thanks for raising this issue to the team. The CCCS sample configuration has been moved to an independent repo you can find here: https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium

If you believe there are updates required for the Service Control Policies included in the CCCS repository, please create an issue on that repository so it can be triaged appropriately. Thank you for your interest in the Landing Zone Accelerator!
