### ISSUE TITLE
bug: make ServiceLinkedRole creation idempotent

### ISSUE THREAD

**Issue by mavogel** [awslabs/landing-zone-accelerator-on-aws#158]
**Describe the bug**
By onboarding a brownfield AWS account from another OU within CT before, the `LoggingStack` fails

**To Reproduce**
Onboard an account to LZA (already enrolled in CT) which has `AWSServiceRoleForAutoScaling` existing and in `security-config.yaml`: 
```yaml
centralSecurityServices:
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: true
```

**Expected behavior**
Creating of ServiceLinkedRoles should be idempotent. 

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.4.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

`security-config.yaml`: 

```yaml
centralSecurityServices:
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: true
```

- [x] Region: [e.g. us-east-1] -> eu-central-1
- [x] Was the solution modified from the version published on this repository? -> no
- [x] If the answer to the previous question was yes, are the changes available on GitHub? -> no
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
```console
2023-05-24 14:08:44.811 | error | toolkit | Stack Deployments Failed: Error: The stack named AWSAccelerator-LoggingStack-123456789012-eu-central-1 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Service role name AWSServiceRoleForAutoScaling has been taken in this account, please try a different suffix. (Service: Iam, Status Code: 400, Request ID: 6497278a-28bd-46ad-bb70-6a82833621cc)" (RequestToken: 406679df-058d-bae1-6f08-d1071009f12b, HandlerErrorCode: AlreadyExists)

new LoggingStack 
(/codebuild/output/src211/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/logging-stack.ts:375:7)
```

**Additional context**
error causing LOC: https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/v1.4.1/source/packages/%40aws-accelerator/accelerator/lib/stacks/logging-stack.ts#L372 derived from the error message

```ts
if (this.props.securityConfig.centralSecurityServices.ebsDefaultVolumeEncryption.enable) {
      // create service linked role for autoscaling
      // if ebs default encryption enabled and using a customer master key
      new iam.CfnServiceLinkedRole(this, 'AutoScalingServiceLinkedRole', {
        awsServiceName: 'autoscaling.amazonaws.com',
        description:
          'Default Service-Linked Role enables access to AWS Services and Resources used or managed by Auto Scaling',
      });
    }
```

As I cannot simply [delete](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#delete-service-linked-role) the service-linked-role for Autoscaling, meaning I'd have to tear down all the instances and remove the ASG (even temporarily). 

```
Service-Linked Role arn:aws:iam::123456789012:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling cannot be deleted as it is in use by Auto Scaling Group/s. Returning sample Auto Scaling Group/s.
```
Correct me please if I'm mistaken here and there is another option

**Comment by erwaxler** [comment]
@mavogel Thank you for your interest in the Landing Zone Accelerator! The development team has encountered similar issues regarding service-linked roles (SLRs) and has ultimately made the decision to update the SLR-creation process to be idempotent. This work has been added to our roadmap, I will update this issue when I have more information.

**Comment by tmokmss** [comment]
fyi I recently published a construct library to create a SLR with idempotency. https://constructs.dev/packages/upsert-slr

**Comment by erwaxler** [comment]
Hi @mavogel , we recently released LZA v1.4.2 which includes an update to the way we create service-linked roles. Please update your deployment to version 1.4.2 and verify you are now able to get past this error when the AWSServiceRoleForAutoScaling role already exists in the account. Once you can confirm this has resolved the behavior in your account, I will go ahead and close this issue.

Thanks again for your interest in the Landing Zone Accelerator!

**Comment by erwaxler** [comment]
Hi @Thomas-McKanna , yes in this case I would recommend updating to v1.4.2. You are correct, in this situation the simplest path forward is directly updating to v1.4.2.

**Comment by Thomas-McKanna** [comment]
@erwaxler When I upgraded to v1.4.2, I was able to get past the service linked role error, but later on during the deploy stage of the pipeline I hit another error. I made an issue here: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/187 

Do you have any idea why such an error might have occurred? Trying to figure out how I might even begin to debug the problem.

**Comment by Thomas-McKanna** [comment]
@josh-romme No I only deleted up to (and including) the logging stack. Make sure you do this in all regions that are being managed by LZA for whatever account it causing the issue.

**Comment by BorntraegerMarc** [comment]
I had this error when upgrading to `v1.4.2`

Worked around it by manually running:
```
aws iam create-service-linked-role --aws-service-name autoscaling.amazonaws.com

aws iam create-service-linked-role --aws-service-name cloud9.amazonaws.com
```

In every account

**Comment by BorntraegerMarc** [comment]
@erwaxler I made a typo in my previous comment (now corrected)
This bug happened to me actually in `v1.4.3` when I upgraded 5 days ago.

**Comment by BorntraegerMarc** [comment]
Related to this: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/187
