### ISSUE TITLE
Root Email Address is Not Unique

### ISSUE THREAD

**Issue by bmadden-arch** [awslabs/landing-zone-accelerator-on-aws#162]
**Describe the bug**
I have added new accounts in Control Tower. I have then added them to accounts.config file. When I release the change it fails on the PrepareStack step. The error in CloudWatch tells me Service Catalog having issues. When I go into Service Catalog it is trying to re-provision the existing accounts. The error message in Provisioning failure error message: Invalid ParameterException the email address provided is associated with another account.

**To Reproduce**
1. Add accounts to Control Tower
2. Add accounts to CodeCommit
3.  Release change
4. Pipeline fails on the Preparestack
5. Preparestack goes into Rollback 

**Expected behavior**
Deploy beyond the Preparestack

**Please complete the following information about the solution:**

- [1.3.0 ] Version: [e.g. v1.1.0]

What is the impact of deleting the Preparestack within CloudFormation?

**Comment by bmadden-arch** [comment]
Fix found in the Account Enrollment and environment validation failures

**Comment by sunstonesecure-robert** [comment]
@bmadden-arch can you elaborate on your fix?
