### ISSUE TITLE
bug: scpRevertChangesConfig with custom AcceleratorPrefix causes runaway lambda invocation 

### ISSUE THREAD

**Issue by memorsolutions** [awslabs/landing-zone-accelerator-on-aws#163]
**Describe the bug**
When scpRevertChangesConfig is enabled and a custom AcceleratorPrefix is used during stack deployment, lambda function AccountsStac-RevertScpChangesRevertSc creates and infinite Lambda invocation -> modify SCP-> EventBridge event -> Lambda invocation loop. In addition to high Lambda utilization, throttling can produce TooManyRequestsException accessing Organizations (e.g., through the console) due to saturation of calls by the Lambda function to the Organizations client.

**To Reproduce**
Deploy the accelerator, setting the AcceleratorPrefix to anything except `AWSAccelerator`.

In `security-cofig.yaml`, enable `scpRevertChangesConfig`

```yaml
centralSecurityServices:
  scpRevertChangesConfig:
    enable: true
    snsTopicName: Security
```
Rerun the pipeline to cause the EventBridge rule and Lambda function to be provisioned.

**Expected behavior**
The Lambda function correctly identifies SCP changes made by the accelerator when it calls `isChangeMadeByAccelerator`. Invocation metrics for the AccountsStac-RevertScpChangesRevertSc show that the function is not being continuously called.

**Please complete the following information about the solution:**

- [x] Version: __v1.4.1__
- [x] Version: __v1.4.0__

- [x] Region: __Affects all regions__
- [x] Was the solution modified from the version published on this repository? __Yes__
- [x] If the answer to the previous question was yes, are the changes available on GitHub? __Yes__
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? __There were no errors, but the runway even/lambda loop causes excessive logging.__

**Additional context**
The lines  resulting in the issue are found at https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/21d70ceeaf1cc323507e8d22e705c463c728d252/source/packages/%40aws-accelerator/constructs/lib/aws-events/revert-scp-changes/index.ts#L23 and at https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/21d70ceeaf1cc323507e8d22e705c463c728d252/source/packages/%40aws-accelerator/constructs/lib/aws-events/revert-scp-changes/index.ts#L56-L62.

The fix is to change the constant at line 23 to:
```typescript
const acceleratorRolePrefix = process.env['ACCELERATOR_PREFIX'] ?? 'AWSAccelerator';
```
and then propagate the `AcceleratorPrefix` parameter through to the Lambda function's environment.

I will submit a pull request shortly that fixes this bug.

**Comment by erwaxler** [comment]
Hi @memorsolutions , thank you for identifying this bug and submitting a pull request! I will take a look at your PR shortly and provide any feedback on the PR directly.

**Comment by erwaxler** [comment]
Hi @memorsolutions , this has been merged into our development branch and will be included in our next major release.  I will keep this open until it is publicly available. Thank you again for your contribution!

**Comment by jlowellwofford** [comment]
I encountered this bug in v1.4.2.  Is which release is this fix planned for?

**Comment by Athanasii** [comment]
This was fixed in a previous version.
