### ISSUE TITLE
reference/sample-configurations/aws-best-practices-education missing ssm-documents folder

### ISSUE THREAD

**Issue by asafo** [awslabs/landing-zone-accelerator-on-aws#166]
**Describe the bug**
The file security-config.yaml from education best practices includes files from ssm-documnets,
But the folder doesn't exist, which breaks the build

**To Reproduce**
Deploy LZA with the configs from: reference/sample-configurations/aws-best-practices-education

**Expected behavior**
LZA to deploy aws-best-practices-education without errors

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.1.0]
- [ ] Region: [e.g. eu-west-1]
- [ ] Was the solution modified from the version published on this repository?: Yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?: No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: No
- [ ] Were there any errors in the CloudWatch Logs?: Yes

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by awsclemj** [comment]
Hello,

We haven't heard from you on this issue in a while. If you require any additional assistance, please feel free to reply and/or re-open this issue.

Thank you for your interest in Landing Zone Accelerator on AWS!
