### ISSUE TITLE
AWS cost allocation tags via LZA

### ISSUE THREAD

**Issue by devalibvr** [awslabs/landing-zone-accelerator-on-aws#168]
Hi - this is only a question. I manage AWS accounts with AWS Control Tower, Account Factory for terraform and Landing zone accelerator. my question is are there any way to implement cost allocation tags with  LZA?

**Comment by awsclemj** [comment]
Hello @devalibvr, and thanks for reaching out to the LZA team!

At present, you can apply user-defined tags to many resources using LZA, however there is currently no way to activate user-defined cost allocation tags in the Billing console using LZA. Any resource in our configuration reference that includes a `tags` property (here is [VpcConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.VpcConfig.html#tags) as an example) can have tags applied. 

I hope this information is helpful! Please let us know if there's anything more we can do to help here.
