### ISSUE TITLE
How to properly delete an account

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#169]
**Is your feature request related to a problem? Please describe.**
From a deployed LZA, i need to delete a couple of accounts. 
I did not find any explicit mention on how to do this.  I did the following
1.   Unmanaged the account from the tower. 
2.  Suspended the account in the org. 
3. Removed the account from LZA config 
 

LZA update fails, naturally
```
AWSAccelerator-PrepareStack-455771497148-us-east-2 \| 7:10:59 PM \| UPDATE_FAILED        \| Custom::ValidateEnvironmentConfig                  \| ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) Received response status [FAILED] from custom resource. Message returned: Error: Account xxxx@xxx.xxx with account id xxxx is not in the correct OU. Account is in the ou named Root and should be in Prod,Account with Id xxxx and email xxx@xx.xxx is not in the accounts configuration and is not a member of an ignored OU.,Account with Id XXX and email xxxx.xxx.xx.com is not in the accounts configuration and is not a member of an ignored OU.,Account with Id 690120328019 and email xxxx@xx.xxx is not in the accounts configuration and is not a member of an ignored OU.
--
272 | at Ekn (/var/task/index.js:78:21055)
273 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
274 | at async Runtime.handler (/var/task/__entrypoint__.js:1:932) (RequestId: e5d5b907-c783-4d09-aa3e-dd58db65246a)
275 | new CustomResource (/codebuild/output/src626/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
276 | \_ new ValidateEnvironmentConfig (/codebuild/output/src626/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/validate-environment-config.ts:124:22)
277 | \_ new PrepareStack (/codebuild/output/src626/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:422:30)
278 | \_ main (/codebuild/output/src626/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:487:28)
279 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
280 | \_ async /codebuild/output/src626/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5


```

**Describe the feature you'd like**

A section added to documentation on the right way of deleting accounts. 

P.S: bonus points for a section on a right way to recover from the situation that I got myself into. 

**Additional context**

**Comment by awsclemj** [comment]
Hello @snemir2,

[This section](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/performing-administrator-tasks.html#closing-an-account) of our Implementation Guide includes instructions for suspending an account. It looks like you successfully suspended your account, however you'll need to also complete the step of placing the account in an ignored OU. I hope this helps solve your issue!

**Comment by snemir2** [comment]
Thank you for that!   
I can confirm:
1. following the above would have avoided my issue.   
2. Following https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-account-enrollment-and-environment-validation-failures.html#general-account-enrollment-failure works to recover from not moving the suspended accounts to "Ignored" OU.
