### ISSUE TITLE
Deploying AWS Accelerator Installer Stack always fails at GitHubPipeline creation

### ISSUE THREAD

**Issue by sttomm** [awslabs/landing-zone-accelerator-on-aws#17]
**Describe the bug**
When trying to deploy the AWS Accelerator Installer Stack, i run into this error:
![image](https://user-images.githubusercontent.com/32126381/193022273-e8f1376e-4995-4aac-a2a2-3472cedf14c6.png)

Looking into Cloud Trail shows me that the interactions with CodePipeline only ever calls get operations. I am wondering why there is no Create operation for the pipeline. Because the Get actually returns that an expected pipeline cannot be found:

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "arn": "arn:aws:sts::000000000000:assumed-role/AWSReservedSSO_AWSAdministratorAccess_abc/mail@example.com",
       ...
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2022-09-29T10:07:26Z",
    "eventSource": "codepipeline.amazonaws.com",
    "eventName": "GetPipeline",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "AWS Internal",
    "userAgent": "AWS Internal",
    "errorCode": "ValidationException",
    "errorMessage": "Account '000000000000' does not have a pipeline with name 'AWSAccelerator-Installer'",
    "requestParameters": {
        "name": "AWSAccelerator-Installer"
    },
    "responseElements": null,
    "requestID": "b72c71a1-6847-4f1e-b764-c42a5108a03c",
    "eventID": "da118a2b-2954-4b99-98f3-0203ee552d37",
    "readOnly": true,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "eventCategory": "Management",
    "sessionCredentialFromConsole": "true"
}
``
`

**To Reproduce**
- go to https://aws.amazon.com/de/solutions/implementations/landing-zone-accelerator-on-aws/
- click "Launch in the AWS Console"
- enter the parameters (i used the account email addresses of already existing AWS Accounts that were created by AWS Control Tower)
- During deployment of the AWS Accelerator Installer Stack, the mentioned error occurs

**Expected behavior**
The AWS Accelerator Installer Stack deploys successfully without an error.
If an error occurs, i would expect a more detailed and helpful error message than only "Internal Failure".

**Please complete the following information about the solution:**

- [ x ] Version: 1.2.0
- [ x ] Region:  us-east-1, also tried eu-central-1 before and ran into the same issue
- [ x ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ x ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?  yes, haven't found something suspicious on the code pipeline quotas. All quotas should still be set to the defaults
- [ x ] Were there any errors in the CloudWatch Logs?  yes, during the GetPipeline as mentioned above

**Screenshots**
already added them above

**Additional context**
None

**Comment by sttomm** [comment]
I was able to find the root cause of it. The github-token was missing in the AWS Secret Manager. I think documentation is not ideal around this. You have to get further down in you documentation to get to this page: https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/automated-deployment.html

I didn't really consider going there before applying the Stack as i though the following page already describes everything i need to get started with the Stack: https://aws.amazon.com/de/solutions/implementations/landing-zone-accelerator-on-aws/

I also read the whole README in this github repo and the step of entering the key was not mentioned here either. I think documentation should be extended in that regard.

**Comment by awsclemj** [comment]
Hello, and thank you for the feedback!

We have updated our documentation in a few iterations since this issue was cut. A couple callouts:
1. We now specify and link to the prerequisites in the solution's [splash page](https://aws.amazon.com/solutions/implementations/landing-zone-accelerator-on-aws/)
2. We have restructured the document's format to have all deployment steps listed under the [Deploy the solution](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/deploy-the-solution.html) heading.

Thanks again! I will close this out, but please feel free to open additional issues or use the 'Provide feedback' link in our documentation pages.

**Comment by sunstonesecure-robert** [comment]
Just FYI - this is still a problem - even if NOT using GitHub for the configuration (eg using S3). Why does it need a PAT?  in any case both of the links you noted are now without any info and the info is here:

https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html#create-a-github-personal-access-token-and-store-in-secrets-manager

But again - if not using GitHub as the config store - why do we need a PAT?

**Comment by richardkeit** [comment]
@sunstonesecure-robert  - to pull the accelerator code from the public repo (this one)
