### ISSUE TITLE
S3 Access Logs are not replicating to central logging bucket

### ISSUE THREAD

**Issue by sigfigsteve** [awslabs/landing-zone-accelerator-on-aws#171]
**Describe the bug**
S3 Access Logs deposited in the aws-accelerator-s3-access-logs-_accountID_-_region_ buckets are not being replicated to aws-accelerator-central-logs-_loggingAccountID_-_primaryRegion_.  Examining the "Management" tab of the source account's s3 access logs bucket shows there are no replication rules.

**To Reproduce**
- Create an s3 bucket in a workload account with a logging configuration recording access to that account's aws-accelerator-s3-access-logs-_accountID_-_region_ bucket
- Make some requests to access content in that bucket
- Verify the bucket access is logged in the workload account
- In the LogArchive account, verify no s3 logs are replicated to the aws-accelerator-central-logs-_loggingAccountID_-_primaryRegion_ bucket

**Expected behavior**
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md?plain=1#L228 says
`Logs are stored in account specific S3 buckets and have bucket replication enabled to replicate logs to Centralized Logging S3 Bucket in Central Logging Account. `
although it does not specify a subdirectory/path for s3 access logs (https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md?plain=1#L259).  A subdirectory will probably be required to keep the central bucket organized.
Ideally the replication process would also partition the logs by date so I can efficiently query them with athena, but that's a feature-request add-on.

**Please complete the following information about the solution:**

- [ ] Version: 1.3.2
- [ ] Region: us-east-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**

**Additional context**
If I'm reading the code correctly, I suspect the root of the issue is around https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/logging-stack.ts#L177.  Compare that to https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/logging-stack.ts#L261 and note the serverAccessLogsBucket creation does not pass a "replicationProps" like the elbAccessLogsBucket

**Comment by awsclemj** [comment]
Hello @sigfigsteve, and thank you for raising this issue!

This looks to be a documentation issue rather than a bug -- LZA does not replicate the account-level access logs to the central logs bucket due to the duplicative storage cost associated with that job. I can confirm that we do have a feature request in our backlog that we are evaluating for a future release for users that would like the centralized replication job to be set up. 

I will open a documentation fix ticket on your behalf so we can clear this up; we apologize for any confusion caused by this documentation error.

**Comment by sigfigsteve** [comment]
OK, I'll work with the account-specific buckets for s3 logs and consider this a documentation bug.  For the feature request for the long term, it would be really useful if the logs were partitioned by date.  Feel free to close this issue.

**Comment by awsclemj** [comment]
Thank you for the feedback! I will add this to our feature request. 

Thanks for your interest and support of LZA!
