### ISSUE TITLE
CT attempting to create additional account after failure despite reverted configuration

### ISSUE THREAD

**Issue by stephenson-andrew** [awslabs/landing-zone-accelerator-on-aws#172]
**Describe the bug**
After adding an additional account in to _accounts-config.yaml_ and having CT fail to create the additional account due to service quotas.  If I then remove/revert the change from _accounts-config.yaml_ the pipeline still fails at the _Custom::CreateControlTowerAccounts_ step in the _AWSAccelerator-PrepareStack_

```
AWSAccelerator-PrepareStack-856919951273-eu-west-2 | 0/10 | 12:20:55 PM | UPDATE_FAILED        | Custom::CreateControlTowerAccounts                 | CreateCTAccounts/Resource/Default (CreateCTAccounts3049A752) Received response status [FAILED] from custom resource. Message returned: Account creation failed. Error: Accounts failed to enroll in Control Tower. Check Service Catalog Console
```

**To Reproduce**

1. Add an additional account to the config for LZA to provision through Control Tower whilst at the service limit 
2. Remove the entry for the additional account from _accounts-config.yaml_

**Expected behavior**
LZA does not attempt to provision the account given the configuration now matches the state of the organization.
The pipeline succeeds.

**Please complete the following information about the solution:**

- [x] Version: v1.4.1
- [x] Region: eu-west-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? NA
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? - Failing to check is the root cause - until the quota is increased the LZA pipeline is essentially blocked :(
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by awsclemj** [comment]
Hello @stephenson-andrew, and thanks for reaching out to the Landing Zone Accelerator team!

We have a [troubleshooting guide](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-account-enrollment-and-environment-validation-failures.html#general-account-enrollment-failure) for the failure you're encountering. You will need to follow the steps to clean up the failed provisioned product in order for the custom resource to succeed. If you continue encountering the error after following these steps, please let us know and we will be happy to help further.

Thank you!

**Comment by stephenson-andrew** [comment]
Thanks @awsclemj.

I hadn't seen that part of the troubleshooting guide previously and clearing out the failed service catalog entries resolved the issue.
