### ISSUE TITLE
ecr.api endpoint hostedzone name issue

### ISSUE THREAD

**Issue by DonthineniSagar** [awslabs/landing-zone-accelerator-on-aws#173]
**Describe the bug**
We have encountered this issue, we created a centralised endpoints and tried to spin up ECS fargate task which was failing trying to connect https://api.ecr.<region>.amazon.aws.com. when verified in central VPC the ecr.api end point was created but the hosted zone domain name is ecr.api.<region>.amazon.aws.com. Hence the subscriber VPC was not resolving the api.ecr. We have created another hosted zone with api.ecr.<region>.amazon.aws.com and ECS task ran successfully. is it something expected behavior?

Not sure if we are missing anything!!
```[tasklist]
### Tasks
```

**Comment by DonthineniSagar** [comment]
Have the same issue with dkr.ecr endpoint which is created as ecr.dkr in R53 hostedzone.

**Comment by erwaxler** [comment]
Hello @DonthineniSagar, thank you for reaching out to the Landing Zone Accelerator on AWS team!

I have created a ticket in the team's backlog to attempt to reproduce this error. In order to mirror your configuration, please provide the following information:

- What version of LZA do you have deployed?
- In what region are you observing this behavior?
- Please include a snippet of your `network-config.yaml` file where you have the ECR endpoints defined.

Thank you again for raising this issue!

**Comment by DonthineniSagar** [comment]
@erwaxler  thank you for you response. i investigated  bit more into code and the issue here is the way hostedzone created for the endpoint services. if endpoint has one word there is no issue as there is no dependency of order. 
The code uses "hostedZoneName = `${service}.${region}.amazonaws.com`;"
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/constructs/lib/aws-route-53/hosted-zone.ts

 if endpoint  name is" <regionname>.logs" there is no issue, but if service name is "<regionname>.ecr.api"or "ecr.dkr" the hosted zone created in the order of service name instead of other way like "api.ecr". may be a condition to deal with these exceptions is a fix :) 
 
 Below is my config screenshot.
 
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/108803545/e8552062-0a80-4e9f-ba3e-4ebc6dfb7266)

**Comment by erwaxler** [comment]
@DonthineniSagar Thank you for the additional information! I can confirm this behavior, I've included all relevant information on our ticket. I will update this thread once I have an update on the team's progress.

**Comment by erwaxler** [comment]
The team has implemented a fix for this bug that will be included in our next major release, LZA v1.5.0 currently planned for the end of Q3. I'll keep this issue open until the next release.

**Comment by awsclemj** [comment]
Hello,

A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
