### ISSUE TITLE
Question Around Security Hub Event Rule

### ISSUE THREAD

**Issue by cjthorpe** [awslabs/landing-zone-accelerator-on-aws#178]
Hi,

This is a general question that has come from some of the developers on our project.

In some of our AWS accounts within Control Tower the Event Rule that sends all Security Hub Findings to a Lambda that writes to CloudWatch Logs, _AWSAccelerator-SecurityRe-SecurityHubEventsLogSecu*_, has been disabled manually, in the console.

This is because the Lambda would become very busy at certain times, start throttling, and cause a CloudWatch alarm to raise an OOH alert to support teams. 

Where this is disabled we'd like it to remain so. If LZA is upgraded at some point in the future is there any danger of the upgrade re-enabling this event rule - or will it only become re-enabled if it is manually re-enabled in the console?

Thanks.

Chris Thorpe.
GDS.

**Comment by erwaxler** [comment]
Hi @cjthorpe , thanks for creating this issue. My suspicion is that any pipeline run will likely re-enable this Lambda function. We have implemented a new property in the configuration to allow customers to disable the logging of Security Hub events through Lambda in each account which will allow you to disable these functions through LZA. This feature will be released as part of the next major version of LZA, currently planned for the end of Q3.

**Comment by awsclemj** [comment]
Hello,

The feature my colleague mentioned has been implemented as part of our v1.5.0 release. You may learn how to configure it [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SecurityHubConfig.html#logging).

Thank you for your support of the LZA! I will mark this issue as resolved.
