### ISSUE TITLE
Landing Zone Accelerator Does Not Deploy Outside of US-EAST-1

### ISSUE THREAD

**Issue by bmadden-arch** [awslabs/landing-zone-accelerator-on-aws#18]
Hi,

I'm trying to deploying the Landing Zone Accelerator in EU-WEST-1. During the CodePipeline Account stage it fails as it is looking for a CDK folder in US-EAST-1. There are only 4 regions listed in the GlobalRegionMap section of the template.

**To Reproduce**
Deploy in any region other than US-EAST-1, US-GOV-WEST-1, US-ISOB-EAST-1 or US-ISO-EAST-1 which are all listed.

**Expected behavior**
Expect LZA to deploy all resources in my EU-WEST-1 not split across EU-WEST-1 and US-EAST-1.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.2.0]
- [ ] Region: [e.g. eu-west-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas] yes (https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? See screenshots

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
<img width="177" alt="LZABug1Mappings" src="https://user-images.githubusercontent.com/71442646/193593082-6381352c-0f64-4909-94b5-169a9370b384.png">

**Additional context**
<img width="737" alt="LZACodePipelineError" src="https://user-images.githubusercontent.com/71442646/193593135-45fd0812-ca25-4152-8283-56cb59d98344.png">

**Comment by bmadden-arch** [comment]
I have just modified the template to just have EU-WEST-1 in the GlobalRegionMap and it is running successful now. Suggest you add section to READ.ME and AWS Pages that you need to modify template for the region you want to deploy to if not US-EAST-1, US-GOV-WEST-1, US-ISOB-EAST-1, US-ISO-EAST-1.

**Comment by fanq10** [comment]
Hi @bmadden-arch, 

I have figured out how to deploy the solution in another region other than us-east-1.

Changes need to be made, for my example, I use `ap-southeast-2`, you can replace them with `eu-west-1`

1. source/packages/@aws-accelerator/installer/lib/installer-stack.ts - `ln136`
```
-          regionName: 'us-east-1',
+         regionName: 'ap-southeast-2',
```
2. source/packages/@aws-accelerator/config/lib/global-config.ts - `ln656`
```
-  readonly homeRegion: string = '';
+ readonly homeRegion: string = 'ap-southeast-2';
```

3. source/packages/@aws-accelerator/accelerator/lib/accelerator.ts - `ln248`
```
-    let globalRegion = 'us-east-1';
+    let globalRegion = 'ap-southeast-2';
```

4. source/packages/@aws-accelerator/accelerator/bin/app.ts - `ln120`
```
-    let globalRegion = 'us-east-1';
+    let globalRegion = 'ap-southeast-2';
```

**Comment by rgd11** [comment]
@fanq10 @bmadden-arch 

It is recommended to **not** modify the installer template or the underlying deployment code (.ts files) and interact with the solution primarily through the configuration files. 

`globalRgion` is used to specify the region that is used by clients such as Organizations which is a global service, and should not be modified as they are tied to the AWS partition in use. 

Simply, set your `homeRegion` to the desired region you want to have the solution installed into.

**Comment by jfan9** [comment]
> @fanq10 @bmadden-arch
> 
> It is recommended to **not** modify the installer template or the underlying deployment code (.ts files) and interact with the solution primarily through the configuration files.
> 
> `globalRgion` is used to specify the region that is used by clients such as Organizations which is a global service, and should not be modified as they are tied to the AWS partition in use.
> 
> Simply, set your `homeRegion` to the desired region you want to have the solution installed into.

Thanks @rgd11, also, I reckon it's good to update the LZA document showing which file(s) on which part(s) should be changed.

**Comment by muthhus** [comment]
Hi @jfan9 @rgd11 
In the release/1.4.2, I am getting the above mentioned issue( https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/18#issue-1394779068 - fail: No bucket named 'cdk-accel-assets-<account-id>-us-east-1'. Is account 621056076192 bootstrapped?) even though, I have set the homeRegion(eu-west-2) in the global-config.yaml.

**Comment by 0arko** [comment]
@rgd11 if you use an external pipeline account and therefore an existing repo to host the config files e.g global-config.yaml etc (otherwise the pipeline fails due to the pipeline account being unrecognised) and input this to the CFN parameter `Existing Config Repository Name` then the `homeRegion` parameter is set before the bootstrap stage, meaning that the us-east-1 s3 asset bucket doesnt get created, and we see the above error (No bucket named XXX. is account XXX bootstrapped?) How do we get round this issue without editing the installer files?
