### ISSUE TITLE
Documentation Links to are all returning a 404

### ISSUE THREAD

**Issue by jaybonk** [awslabs/landing-zone-accelerator-on-aws#181]
The links within the documentation pages here: https://awslabs.github.io/landing-zone-accelerator-on-aws/
and from the main repository page: https://github.com/awslabs/landing-zone-accelerator-on-aws, are returning a 404 when attempting to open any of the base configuration or service/function configuration links

**Comment by awsclemj** [comment]
Hello,

Apologies for the brief outage! We were updating our documentation pages to reflect our latest release. This issue should now be resolved.

Thank you!
