### ISSUE TITLE
ORG_ID policy replacement variable does not get substituted in VPC Endpoint Policy

### ISSUE THREAD

**Issue by zakbatinica-reply** [awslabs/landing-zone-accelerator-on-aws#184]
**Describe the bug**
Following the resolution of #161 we made changes to our SCP and VPC endpoint policy to make use of the `ORG_ID` variable. The variable is replaced in the SCP but not in the endpoint policy.

**To Reproduce**
Create an endpoint policy using the following configuration:

`network-config.yaml`

```yaml
endpointPolicies:
  - name: Default
    document: vpc-endpoint-policies/default.json
```

`vpc-endpoint-policies/default.json`

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AllowRequestsByOrgsIdentitiesToOrgsResources",
			"Effect": "Allow",
			"Principal": {
				"AWS": "*"
			},
			"Action": "*",
			"Resource": "*",
			"Condition": {
				"StringEquals": {
					"aws:PrincipalOrgID": "${ORG_ID}",
					"aws:ResourceOrgID": "${ORG_ID}"
				}
			}
		}
	]
}
```

**Expected behavior**
Assuming the organization ID was o-1234 I expected the final SCP would render like this:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AllowRequestsByOrgsIdentitiesToOrgsResources",
			"Effect": "Allow",
			"Principal": {
				"AWS": "*"
			},
			"Action": "*",
			"Resource": "*",
			"Condition": {
				"StringEquals": {
					"aws:PrincipalOrgID": "o-1234",
					"aws:ResourceOrgID": "o-1234"
				}
			}
		}
	]
}
```

**Please complete the following information about the solution:**

- Version: v1.4.2
- Region: eu-west-2
- Was the solution modified from the version published on this repository? No
- If the answer to the previous question was yes, are the changes available on GitHub? N/A
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No
- Were there any errors in the CloudWatch Logs? No

**Screenshots**
Resulting endpoint policy from the above configuration:

![Endpoint Policy](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/127220646/e7bd80d4-ea09-44c8-9c1f-32a5c94aff25)

**Comment by erwaxler** [comment]
Hi @zakbatinica-reply , thanks for creating this issue.

This is currently expected behavior for the LZA; we support [policy replacements](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-solution-specific-variables.html) in the following policy types:
- AWS Organization policies (SCPs, tag policies, backup policies)
- IAM policies
- AWS KMS key policies 

I have recategorized this issue as a feature request and added it to our team's backlog. I will update this issue accordingly, thank you for your interest in the LZA!

**Comment by erwaxler** [comment]
This feature has been implemented and will be available in our next major release slated for the end of Q3.
