### ISSUE TITLE
Max Allowed SCPs error with Control Tower enabled

### ISSUE THREAD

**Issue by fjudith** [awslabs/landing-zone-accelerator-on-aws#186]
**Describe the bug**

Prepare step is always failing if SCPs is enabled in AWS Organization (required for Control Tower)

**To Reproduce**

Configure LZA with either CCCS Medium or base best-practices.
Keep SCPs enabled in AWS Organization
Run the LZA pipeline

**Expected behavior**

Pipeline should successfully acheive Prepare step.

**Please complete the following information about the solution:**

- [x] Version: v1.4.2

- [x] Region: ca-central-1
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? Yes

```
Received response status [FAILED] from custom resource. Message returned: Error: Max Allowed SCPs for ou "Central" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sensitive-Part-1,aws-guardrails-SqDYWQ,FullAWSAccess,aws-guardrails-NXHZrp,Max Allowed SCPs for ou "Dev" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sensitive-Part-1,aws-guardrails-rOpvkM,FullAWSAccess,aws-guardrails-OoOdgU,Max Allowed SCPs for ou "Test" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sensitive-Part-1,aws-guardrails-XpFGrF,aws-guardrails-SocFQz,FullAWSAccess,Max Allowed SCPs for ou "Prod" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sensitive-Part-1,aws-guardrails-mrQoQq,aws-guardrails-cxhYOI,FullAWSAccess,Max Allowed SCPs for ou "UnClass" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Unclass,aws-guardrails-QxYscK,aws-guardrails-GWzKlz,FullAWSAccess,Max Allowed SCPs for ou "Sandbox" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-0,AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sandbox,aws-guardrails-SyLxqz,aws-guardrails-fyBFDd,FullAWSAccess,Max Allowed SCPs for ou "Infrastructure" is 5, found total 6 scps in updated list to attach. Updated list of scps for attachment is AWSAccelerator-Guardrails-Part-1,AWSAccelerator-Guardrails-Sensitive-Part-1,AWSAccelerator-Guardrails-Part-0-Core,aws-guardrails-ZhDQOh,aws-guardrails-EHMjur,FullAWSAccess at dTt (/var/task/index.js:57:21054) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Runtime.handler (/var/task/__entrypoint__.js:1:932) (RequestId: 2dbc51cf-1c71-4032-bf1a-b0170b63e1b2)
```

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by fjudith** [comment]
Solved by remove duplicated [FullAWSAccess](https://us-east-1.console.aws.amazon.com/organizations/v2/home/policies/service-control-policy/p-FullAWSAccess) policy allocated to individual OUs. This policy is already allocated at the organization Root

**Comment by vrioux** [comment]
@fjudith caution, do NOT remove FullAWSAccess from being directly attached to OUs, you will break access to everything. For Allow statements to work, the FullAWSAccess SCP *must* be attached to *ALL* OUs along the way up to the actual accounts.

**Comment by jonathan-pehau** [comment]
@fjudith You need to review the Organization.yaml file and select the SCPs to apply. Keep in mind you already have 3 SCPs used with the FullAWSAccess one needed on each OU and the 2 attached by Control Tower by default.
