### ISSUE TITLE
Invalid Principal for Created EBS Encryption Key

### ISSUE THREAD

**Issue by Thomas-McKanna** [awslabs/landing-zone-accelerator-on-aws#187]
**Describe the bug**

Upon updating to v1.4.2, a failure occurred in the Deploy stage of the pipeline:

<img width="987" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22783091/42eb4148-2663-4f4d-b7d0-1b589ddb1606">

The error was:

```
AWSAccelerator-SecurityStack-707323472617-us-east-2 \|  0/30 \| 5:10:10 PM \| CREATE_FAILED        \| AWS::KMS::Key                                       \| EbsEncryptionKey (EbsEncryptionKey9149E0DA) Resource handler returned message: "Policy contains a statement with one or more invalid principals. (Service: Kms, Status Code: 400, Request ID: 6438f38f-d800-4736-b9fb-646f79c8e506)" (RequestToken: 99b1735e-b4a9-c445-973b-de822e745e3b, HandlerErrorCode: InvalidRequest)
--
1562 | new Key (/codebuild/output/src386/src/s3/00/source/node_modules/aws-cdk-lib/aws-kms/lib/key.js:1:8378)
1563 | \_ SecurityStack.configureDefaultEbsEncryption (/codebuild/output/src386/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/security-stack.ts:252:28)
1564 | \_ new SecurityStack (/codebuild/output/src386/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/security-stack.ts:103:10)
1565 | \_ main (/codebuild/output/src386/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:737:33)
1566 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
1567 | \_ async /codebuild/output/src386/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5
```

**To Reproduce**

An upgrade to v1.4.2 caused the error.

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.4.2]
- [x] Region: us-east-2
- [x] Was the solution modified from the version published on this repository? No

Any ideas for why or how such an error could occur? The only change I made to the configuration was adding one new account.

**Comment by Thomas-McKanna** [comment]
Update: the problem occurred after an upgrade to v1.4.2 that was a result of the issue at https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/158 

I notice in the code for EbsEncryptionKey the following block:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blame/0e75eebc6d60b2270be24e926f8c832528520070/source/packages/%40aws-accelerator/accelerator/lib/stacks/security-stack.ts#L258-L288

Which refers to principal that is a service linked role ending with `:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling`

https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/158 had to do with service linked roles and I see that this service linked role _does not_ exist in the new account that has been added, and I suspect this is why the error is referring to an invalid principal.

Any thoughts on why the service linked role `AWSServiceRoleForAutoScaling` is not being created?

**Comment by Thomas-McKanna** [comment]
I was able to resolve this issue by removing the cloud formation templates in reverse order up to and including the logging stack. A subsequent run of the pipeline was able to recreate these stacks and making it past this error.

**Comment by stuartgraham** [comment]
Same issue with a 1.4.2 upgrade, same with issue #158 . Which is this one closed?

**Comment by jblaplace-mrnf** [comment]
You could try also the following:

From the management account run the following AWS CLI to create the missing service linked roles and retry the stage.

aws iam create-service-linked-role --aws-service-name autoscaling.amazonaws.com
and 
aws iam create-service-linked-role --aws-service-name cloud9.amazonaws.com

**Comment by BorntraegerMarc** [comment]
@Thomas-McKanna I suggest that you re-open this issue since the underlying cause is not fixed yet

**Comment by bakharzy** [comment]
I have the same issue updating from v1.3.2 to 1.5.0. This happened in two regions managed by LZA. 

![Screenshot 2023-10-19 at 11 36 37](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/1803773/17dfe11a-6639-4094-a964-401fb9f2f27f)

**Comment by bakharzy** [comment]
Creating the service linked roles mentioned above helped me to pass that stage. Please note that the roles needed to be created in all accounts. 
Also check if there is any stack in UPDATE_ROLLBACK_FAILED state and change the state by clicking "Continue  update rollback" from Stack actions. 
@Thomas-McKanna would you open this issue? As it is not fixed yet.
