### ISSUE TITLE
[Question] Implementing Okta (or other external IdP) SSO

### ISSUE THREAD

**Issue by sudosoul** [awslabs/landing-zone-accelerator-on-aws#188]
I want to use Okta SSO for AWS access. 

I see [in the docs here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IamConfig.html#providers) that `IamConfig` supports a `providers` block, but is this used alongside AWS AD?

Meaning, AWS AD is a hard requirement?
Or can AD be circumvented and just Okta used?

**Comment by erwaxler** [comment]
Hello, thank you for your interest in the Landing Zone Accelerator.

The `providers` block in the `IamConfig` allows you to create an Identity Provider in AWS IAM. This effectively mirrors the creation process detailed in [this page](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml.html). 

There is no requirement to use this block at all. Regarding AD vs. Okta, the LZA does not impose any specific limitations or requirements above what is included in the AWS IAM documentation. The providers referenced in the AWS Documentation can be created identically through this LZA configuration block.
