### ISSUE TITLE
"s3:GetEncryptionConfiguration" permission missing in central logging bucket policy

### ISSUE THREAD

**Issue by hingyeung** [awslabs/landing-zone-accelerator-on-aws#19]
**Describe the bug**
When session manager s3 logging is enabled in the `global-config.yaml` (`sessionManager.sendToS3`), the session manager is configured to enforce S3 log encryption and checks if the s3 bucket has encryption enabled before connecting. The currently policy of the central logging bucket in the log archive account does not grant `s3:GetEncryptionConfiguration` permission for this check to complete. 

**To Reproduce**
1. Deploy the LZA with `sessionManager.sendToS3` set to `true` in the `global-config.yaml`
2. Launch an ec2 instance with the provided `AWSAccelerator-SessionManagerEC2Role-<region>` role in one of the workload accounts
3. Connect to the instance using session manager
4. Get error: 
```
Your session has been terminated for the following reasons: Couldn't start the session
because we are unable to validate encryption on Amazon S3 bucket.
Error: AccessDenied: Access Denied status code: 403, request id: XXXXXX
```

**Expected behavior**
Enable session manager s3 logging and connect to ec2 instance using session manager without error.

**Please complete the following information about the solution:**

- [ ] Version: v1.2.0
- [ ] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![Screen Shot 2022-10-10 at 7 00 25 pm](https://user-images.githubusercontent.com/1567052/194823723-f257dbe3-7881-4584-b924-6315587473ee.png)

**Additional context**
It appears that we need to include `s3:ObjectOwnerOverrideToBucketOwner` permission in [central-logs-bucket.ts](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/constructs/lib/aws-s3/central-logs-bucket.ts#L217).

**Comment by erwaxler** [comment]
Hello, thank you for your interest in Landing Zone Accelerator on AWS and for identifying this bug. `s3:GetEncryptionConfiguration` permissions were added in version v1.3.0, can you confirm this bug has been resolved after upgrading your environment to v1.3.0?
