### ISSUE TITLE
IAM Errors when running org-wide backup policies

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#195]
**Describe the bug**
IAM Policies deployed OR used by the LZA backup plans thrown errors 
**To Reproduce**
Steps to reproduce the behavior.
1.   Deploy latest LZA version 1.4.2
2. As part of the LZA, i used backup policies from one of the examples.  
3. I see the following in cloud trail logs:
```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "accountId": "XXXXXXXXXXX",
        "invokedBy": "backup.amazonaws.com"
    },
    "eventTime": "2023-07-02T23:16:51Z",
    "eventSource": "backup.amazonaws.com",
    "eventName": "ProcessBackupPlanSelection",
    "awsRegion": "us-east-2",
    "sourceIPAddress": "backup.amazonaws.com",
    "userAgent": "backup.amazonaws.com",
    "errorCode": "AccessDenied",
    "errorMessage": "The provided role arn:aws:iam::XXXXXXXXXXX:role/Backup-Role cannot be assumed by AWS Backup.",
    "requestParameters": null,
    "responseElements": null,
    "eventID": "4d7f5d50-2643-48a4-b018-7dd302857f3c",
    "readOnly": false,
    "eventType": "AwsServiceEvent",
    "managementEvent": true,
    "recipientAccountId": "XXXXXXXXXXX",
    "serviceEventDetails": {
        "backupPlanArn": "arn:aws:backup:us-east-2:XXXXXXXXXXX:backup-plan:orgs/e4548665-3dfc-36a2-92ab-9a6477109903",
        "backupPlanVersion": "OGRkZDBlNzgtNmMzNi00Mjc1LTlkZTUtMmJhNDA3NmQ2OTUy",
        "backupPlanRuleId": "468030dd-e9e4-3fd8-b9ba-e70c6450ad3d",
        "selectionId": "ca468bb5-34dd-3dab-b421-76cabe179c0a"
    },
    "eventCategory": "Management"
}


```

**Expected behavior**

Expect that the role is setup to be assumed by the backup service.  

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.4.2]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: us-east-2
- [ ] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
Related configs:
In Global-configs:
```
...
backup:
  vaults:
    - name: BackupVault
      deploymentTargets:
        organizationalUnits:
          - Root
```

In organization-config.yaml:
```
...
backupPolicies:
  - name: BackupPolicy
    description: Organization Backup Policy
    policy: backup-policies/backup-plan.json
    deploymentTargets:
      organizationalUnits:
        - Root
```
 backup-plan.json is actually with no changes from example(other than region)
```
{
  "plans": {
    "Hourly_Plan": {
      "regions": {
        "@@append": [
          "us-east-2"
        ]
      },
      "rules": {
        "Backup_Rule": {
          "schedule_expression": {
            "@@assign": "cron(0 5/1 ? * * *)"
          },
          "lifecycle": {
            "move_to_cold_storage_after_days": {
              "@@assign": "365"
            },
            "delete_after_days": {
              "@@assign": "1095"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "BackupVault"
          }
        }
      },
      "selections": {
        "tags": {
          "Backup_Assignment": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/Backup-Role"
            },
            "tag_key": {
              "@@assign": "BackupPlan"
            },
            "tag_value": {
              "@@assign": [
                "Hourly"
              ]
            }
          }
        }
      }
    },
    "Daily_Plan": {
      "regions": {
        "@@append": [
          "us-east-2"
        ]
      },
      "rules": {
        "Backup_Rule": {
          "schedule_expression": {
            "@@assign": "cron(0 5 ? * * *)"
          },
          "lifecycle": {
            "move_to_cold_storage_after_days": {
              "@@assign": "365"
            },
            "delete_after_days": {
              "@@assign": "1095"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "BackupVault"
          }
        }
      },
      "selections": {
        "tags": {
          "Backup_Assignment": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/Backup-Role"
            },
            "tag_key": {
              "@@assign": "BackupPlan"
            },
            "tag_value": {
              "@@assign": [
                "Daily"
              ]
            }
          }
        }
      }
    },
    "Weekly_Plan": {
      "regions": {
        "@@append": [
          "us-east-2"
        ]
      },
      "rules": {
        "Backup_Rule": {
          "schedule_expression": {
            "@@assign": "cron(0 5 ? * 1 *)"
          },
          "lifecycle": {
            "move_to_cold_storage_after_days": {
              "@@assign": "365"
            },
            "delete_after_days": {
              "@@assign": "1095"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "BackupVault"
          }
        }
      },
      "selections": {
        "tags": {
          "Backup_Assignment": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/Backup-Role"
            },
            "tag_key": {
              "@@assign": "BackupPlan"
            },
            "tag_value": {
              "@@assign": [
                "Weekly"
              ]
            }
          }
        }
      }
    },
    "Monthly_Plan": {
      "regions": {
        "@@append": [
          "us-east-2"
        ]
      },
      "rules": {
        "Backup_Rule": {
          "schedule_expression": {
            "@@assign": "cron(0 5 1 * ? *)"
          },
          "lifecycle": {
            "move_to_cold_storage_after_days": {
              "@@assign": "365"
            },
            "delete_after_days": {
              "@@assign": "1095"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "BackupVault"
          }
        }
      },
      "selections": {
        "tags": {
          "Backup_Assignment": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/Backup-Role"
            },
            "tag_key": {
              "@@assign": "BackupPlan"
            },
            "tag_value": {
              "@@assign": [
                "Monthly"
              ]
            }
          }
        }
      }
    }
  }
}```

**Additional context**
Add any other context about the problem here.

**Comment by snemir2** [comment]
While on this subject, may I ask a few questions:
1.   Is there a way to deploy cross-region policy (i.e. as part of backup plan copy backups to another region)
2. Is there a way to do cross-account backups (i.e. from accounts in Prod ou copy backups to an account in SharedServices OU (or otherwise different aws account)
3. Is there a way to enable s3 backup from lza configs?

**Comment by snemir2** [comment]
a quick update:
i am adding   AWSBackupServiceRolePolicyForS3[Backup|Restore] to the Backup role -- seemed promising to resolve part of the issue.   (guessing it should have been included in the examples as those policies are not very new anymore).    

Will likely take me a few days to test -- will let you know if this resolves. 

For completness, this is my backup role now from iam-config.yaml:
```
 - name: Backup-Role
        assumedBy:
          - type: service
            principal: backup.amazonaws.com
        policies:
          awsManaged:
            - service-role/AWSBackupServiceRolePolicyForBackup
            - service-role/AWSBackupServiceRolePolicyForRestores
            - AWSBackupServiceRolePolicyForS3Backup
            - AWSBackupServiceRolePolicyForS3Restore
```

**Comment by snemir2** [comment]
actually, the problem remains - I still periodically get the "assume role" error in cloud trail.    (not certain why)
Also -- is there a way to "opt in/out" services for aws backup? 
OptIn of s3 is of specific interest.

**Comment by bo1984** [comment]
Hello, Thank you for using the Landing Zone Accelerator on AWS solution. Currently, I'm attempting to recreate the IAM issues that you're having with AWS Backup as well as the service role. While I attempt to recreate this issue, do you happen to have any SCPs that could possibly be blocking this condition? If you're using AWS Control Tower and you've enabled region controls, this may cause issues depending on your configuration.

In terms of your other inquiries, our backup policies and vault constructs utilize a deploymentTargets method that deploys these resources at scale - https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.DeploymentTargets.html

There, you specify which accounts/OUs this gets deployed to, and can exclude at an account and region level.

In terms of the cross-account and cross-region activities, this would be handled at the policy level. There are multiple examples where you can append multiple regions in your config and specify the ARN of the vault:

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup_syntax.html
