### ISSUE TITLE
Unable to set iamPasswordPolicy/maxPasswordAge  to ZERO (never expire)

### ISSUE THREAD

**Issue by jaybonk** [awslabs/landing-zone-accelerator-on-aws#199]
**Describe the bug**
Unable to set a password to never expire. When setting the maxPasswordAge to ZERO. When setting maxPasswordAge: 0, the config file passes the yarn validate-config, and the build stage in the AWSAccelerator-Pipeline.  However, it fails in the Deploy stage in the Security action with the following message "Message returned: ValidationError: 1 validation error detected: Value '0' at 'maxPasswordAge' failed to satisfy constraint: Member must have value greater than or equal to 1"

The [reference documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IamPasswordPolicyConfig.html#maxPasswordAge) description specifies that "If you do not specify a value for this parameter, then the operation uses the default value of 0. The result is that IAM user passwords never expire" which contradicts the default value for 90 also in the documentation. 

**To Reproduce**
In the security-config.yaml file, in the iamPasswordPolicy, change the default setting of maxPasswordAge: 90 to maxPasswordAge: 0.  This successfully passes when running yarn validate-config, and when running the AWSAccelerator-Pipeline the Build stage will succeed.  However, the Security action in the Deploy stage will fail, returning this error: **Value '0' at 'maxPasswordAge' failed to satisfy constraint: Member must have value greater than or equal to 1**

Removing the iamPasswordPolicy entirely, removing the maxPasswordAge, or setting the maxPasswordAge to null all fail in yarn validate-config.

**Expected behavior**
I would expect that when configuring the IAM Password Policy, I would be allowed to set the password to never expire for the cases where the IAM user created is from a service or application. 

If specifying a ZERO value for the maxPasswordAge does set the password to never expire. That value (ZERO) should be allowed as a valid value and not cause a constraint violation error to be thrown. 

**Please complete the following information about the solution:**

- [1.4.2 ] Version
- [us-west-2 ] Region
- [Yes] Was the solution modified from the version published on this repository?
- [No] If the answer to the previous question was yes, are the changes available on GitHub?
- [No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [No] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
The only changes made to the provided solution were changing the value specified for the maxPasswordAge

**Comment by awsclemj** [comment]
Hello @jaybonk , thank you for filing an issue with the Landing Zone Accelerator team!

I have taken a look at our underlying implementation and can confirm that our documentation does not align with the expected behavior when setting the `maxPasswordAge` property to zero. I have submitted a bug report to a backlog on your behalf.

Thank you for your support of the LZA solution! I will leave this ticket open for now. We will update the issue when there is a fix implemented.

**Comment by awsclemj** [comment]
Hello @jaybonk, I would just like to follow up here to gain more details on your use case for our team. Generally service/application accounts only require programmatic access keys and not console login. The max password age would only impact the latter and not the former. Is this impacting your ability to create service accounts with long-term access keys?

**Comment by jaybonk** [comment]
Hello @awsclemj, you are correct about the programmatic access keys used for service/application accounts.  I got the request to set a password policy so the password never expires, and I clearly didn't think it through.  This is not impacting the creation of service accounts.   Other than the documentation not matching the configuration option, I don't see any issues.
