### ISSUE TITLE
Presence of Sandbox OU prevents LZA deployment

### ISSUE THREAD

**Issue by twdcnz** [awslabs/landing-zone-accelerator-on-aws#204]
**Describe the bug**
I was trying to deploy LZA into a brand new set of accounts today. Control Tower had been deployed with the "Sandbox" OU, which had two workload accounts in it. I had also created the "Infrastructure" OU as per the [prerequisites](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html).

In the Prepare phase of the AWSAccelerator-Pipeline I received this error message

`AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 52/98 | 8:25:12 PM | CREATE_COMPLETE      | Custom::CreateOrganizationalUnits                  | CreateOrganizationalUnits/Resource/Default (CreateOrganizationalUnits3A58A65B) 
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 52/98 | 8:25:14 PM | CREATE_IN_PROGRESS   | Custom::InviteAccountsToOrganization               | InviteAccountsToOu/Resource/Default (InviteAccountsToOu482336A1) 
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 52/98 | 8:25:16 PM | CREATE_IN_PROGRESS   | Custom::InviteAccountsToOrganization               | InviteAccountsToOu/Resource/Default (InviteAccountsToOu482336A1) Resource creation Initiated
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:17 PM | CREATE_COMPLETE      | Custom::InviteAccountsToOrganization               | InviteAccountsToOu/Resource/Default (InviteAccountsToOu482336A1) 
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:27 PM | CREATE_IN_PROGRESS   | Custom::ValidateEnvironmentConfig                  | ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) Resource creation Initiated
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:27 PM | CREATE_FAILED        | Custom::ValidateEnvironmentConfig                  | ValidateEnvironmentConfig/Resource/Default (ValidateEnvironmentConfigB40B464F) Received response status [FAILED] from custom resource. Message returned: Error: Organizational Unit 'Sandbox' with id of 'ou-nppw-h3je9gav' was not found in the organization configuration.
    at dTt (/var/task/index.js:57:21054)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runtime.handler (/var/task/__entrypoint__.js:1:932) (RequestId: fb193d02-2df0-40a7-932e-bd7d6c1dee5b)
    new CustomResource (/codebuild/output/src1403/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new ValidateEnvironmentConfig (/codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/validate-environment-config.ts:124:22)
    \_ new PrepareStack (/codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:422:30)
    \_ main (/codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:487:28)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:28 PM | CREATE_FAILED        | AWS::Events::Rule                                  | ControlTowerOuEventsRule (ControlTowerOuEventsRule7E8DCB15) Resource creation cancelled
    new Rule (/codebuild/output/src1403/src/s3/00/source/node_modules/aws-cdk-lib/aws-events/lib/rule.js:1:1368)
    \_ new PrepareStack (/codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:607:46)
    \_ main (/codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:487:28)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1403/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:29 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                         | AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 The following resource(s) failed to create: [ControlTowerOuEventsRule7E8DCB15, ValidateEnvironmentConfigB40B464F]. Rollback requested by user.
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 | 53/98 | 8:25:58 PM | DELETE_IN_PROGRESS   | AWS::SSM::Parameter                                | AcceleratorLambdaKmsArnParameter (AcceleratorLambdaKmsArnParameterFECEE80C) `

The key error was "Organizational Unit 'Sandbox' with id of 'ou-nppw-h3je9gav' was not found in the organization configuration". That OU with that ID was found in the organisation.

I then deleted the Infrastructure OU, and renamed the Sandbox OU to Infrastructure, then re-ran the pipeline. At that point I received this error message

```
AWSAccelerator-PrepareStack-855249988860-ap-southeast-2 failed: Error [ValidationError]: Stack [AWSAccelerator-PrepareStack-855249988860-ap-southeast-2] cannot be deleted while TerminationProtection is enabled
    at Request.extractError (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/codebuild/output/src779/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2023-07-09T20:57:34.298Z,
  requestId: '6908fa9e-ded6-4a73-8c5a-8498cbc03c02',
  statusCode: 400,
  retryable: false,
  retryDelay: 794.6469770577107
}

Deployment failed: Error: Stack Deployments Failed: ValidationError: Stack [AWSAccelerator-PrepareStack-855249988860-ap-southeast-2] cannot be deleted while TerminationProtection is enabled
    at deployStacks (/codebuild/output/src779/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/codebuild/output/src779/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
    at async Function.execute (/codebuild/output/src779/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:312:9)
    at async /codebuild/output/src779/src/s3/00/source/packages/@aws-accelerator/accelerator/cdk.ts:100:3
2023-07-09 20:57:34.306 | error | toolkit | Stack Deployments Failed: ValidationError: Stack [AWSAccelerator-PrepareStack-855249988860-ap-southeast-2] cannot be deleted while TerminationProtection is enabled
Deployment failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[Container] 2023/07/09 20:57:34 Command did not exit successfully yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out exit status 1
[Container] 2023/07/09 20:57:34 Phase complete: BUILD State: FAILED
[Container] 2023/07/09 20:57:34 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out. Reason: exit status 1
[Container] 2023/07/09 20:57:34 Entering phase POST_BUILD
[Container] 2023/07/09 20:57:34 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2023/07/09 20:57:34 Phase context status code:  Message: 
```

The key error message there is "Stack [AWSAccelerator-PrepareStack-855249988860-ap-southeast-2] cannot be deleted while TerminationProtection is enabled".

I removed termination protection and re-ran the pipeline and everything worked.

I think the solution here is either a code change or a documentation change. Either:

- Have the LZA deployment cope with the existence of the Sandbox OU
- Change the documentation to specify that there must not be a Sandbox OU, and if there is, to rename it to "Infrastructure".

**To Reproduce**
Create a default Control Tower, including the Sandbox OU
Create an AWS account inside the Sandbox OU
Create an Infrastructure OU as per the LZA deployment guide
Follow the LZA deploy instructions

**Expected behavior**
LZA should deploy correctly.

**Please complete the following information about the solution:**

- [x] Version: 1.4.2

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [x] Region: ap-southeast-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

Logs are more useful than screenshots

**Additional context**

**Comment by bhkhatri221** [comment]
Hello @twdcnz , thank you for filing an issue with the Landing Zone Accelerator team! We have mentioned this requirements in the [Prerequisites](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html) section under For AWS Control Tower based installation (recommended). I hope this information is helpful! Please let us know if there's anything more we can do to help here.

I have recategorized this issue as documentation.I'll be closing this issue now, and thank you again for bringing this to our attention.

**Comment by twdcnz** [comment]
@bhkhatri221 that's not quite what the documentation says. What it says is "If you’re deploying a new AWS Control Tower landing zone, you can add the prerequisite Infrastructure OU during the initial setup wizard. By default, the landing zone deploys with an additional Sandbox OU. **You can rename this OU to Infrastructure if desired**. Alternatively, you can create the Infrastructure OU after the landing zone is provisioned."

"If Desired" is very soft recommendation. Someone else deployed Control Tower for me so I left it as-is. Since LZA absolutely will not deploy when an OU named Sandbox exists the documentation really needs to say something like

"An OU named Sandbox **MUST NOT** exist or LZA will not deploy. If you are deploying a new Control Tower rename the default Sandbox OU to Infrastructure either before deploying Control Tower, or in AWS Organizations before deploying LZA"

**Comment by bhkhatri221** [comment]
Hello @twdcnz , thank you for the clarification and adding addition context. I have created an issue for our team to update the document. I will update this issue accordingly. I am reopening this issue and tagging it as documentation label.

Please let us know if you have any follow-up questions that we can help address. Thanks again for your support!

**Comment by awsclemj** [comment]
Hello @twdcnz,

I just wanted to follow-up up on my colleague's @bhkhatri221's comments. We do have specific recommendations for landing zones that have been previously deployed. You may find that guidance [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-existing-landing-zones.html). In short, the LZA will deploy so long as the Sandbox OU and associated accounts are added to the `accounts-config.yaml` and `organizations-config.yaml` files. 

We have this noted in the prerequisites document that @bhkhatri221 pointed out in the following statement: "If you want to deploy to an existing multi-account environment, see [Working with existing landing zones](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-existing-landing-zones.html) for additional considerations before deploying the solution."

Does this additional context clarify the behavior, or do you see any additional gaps in our prerequisite documentation that we may address?

Thank you for your support of the LZA solution!

**Comment by twdcnz** [comment]
Thanks @awsclemj . It wasn't an existing landing zone, it was a brand new account / control tower set up for LZA, it was just set up according to an AWS partner existing standards rather than taking into account LZA pre-requisites.

I think you're right though, it looks like LZA simply found an OU that wasn't configured in the `organization-config.yaml` file and that caused the error. I ran into that same issue later on and fixed it by configuring the OU.

I think the documentation change that I suggested above is worthwhile, as it will simplify things by giving prescriptive guidance rather than making an optional suggestion. Beyond that a quick test that things deploy in a new account based on the new pre-requisites is probably sufficient.

**Comment by bhkhatri221** [comment]
Hi @twdcnz , With the release of [v1.7.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0), you can create, update, or reset an AWS Control Tower Landing Zone. The Landing Zone Accelerator on AWS solution enables you to maintain the AWS Control Tower Landing Zone, which should resolve any issues related to the creation of Organizational Units (OUs) mentioned earlier.

We appreciate your continued support of the Landing Zone Accelerator. Please keep raising issues to help us further enhance the solution.
