### ISSUE TITLE
Cannot run LZA pipeline due to the existing IPAM

### ISSUE THREAD

**Issue by gavinying** [awslabs/landing-zone-accelerator-on-aws#207]
## Background
I have an existing IPAM setup in my Network account, which has already provisioned a few CIDRs to VPCs. 
## Purpose
Now I want to integrate IPAM into LZA pipeline, so that I can auto-assign non-overlap CIDRs to VPCs in newly created accounts via LZA pipeline.
## Error 
But I got the following error, 
```
❌  AWSAccelerator-NetworkPrepStack-xxx-ap-southeast-1 failed: Error: The stack named 
AWSAccelerator-NetworkPrepStack-xxx-ap-southeast-1 failed creation, it may need to be 
manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler 
returned message: "You've reached the limit for ipams. You have created 1 ipams and you 
are limited to 1. (Service: Ec2, Status Code: 400, Request ID: c57ad38c-5530-4d49-82a9-d18f665af084)" 
(RequestToken: 1149b329-0797-1e3e-1329-7ae4e410a859, HandlerErrorCode: InvalidRequest)
```
## Problem
I have confirmed with AWS support that the current LZA doesn't support importing resources, e.g. IPAM, seems the only way is to destroy the existing IPAM and re-create by adding new IPAM to network-config.yaml. But destroying existing IPAM requires removing provisioned CIDRs in VPCs, which is a huge disruption. 
## Help wanted
My end goal is to integrate IPAM to LZA but keep the existing VPCs. 
Any suggestion to achieve this? Thanks.

**Comment by bhkhatri221** [comment]
Hello @gavinying, and and thanks for your interest in Landing Zone Accelerator on AWS! 

The Landing Zone Accelerator solution currently does not support the import of most existing resources, including IPAM resources. This behavior is documented in our [implementation guide](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-existing-landing-zones.html#existing-resources). We recommend to continue managing the IPAM-created VPCs outside of LZA or create a new IPAM in LZA.

**Comment by awsclemj** [comment]
Hello,

We haven't heard from you on this issue in a while. As such, we are resolving this issue. If you require any additional assistance on this issue, please feel free to reply and/or re-open this issue.

Thank you for your interest in Landing Zone Accelerator on AWS!
