### ISSUE TITLE
"ECR private repositories should have image scanning configured" SecurityHub notifications for cdk-accel-container-assets

### ISSUE THREAD

**Issue by roncanepa-tufts** [awslabs/landing-zone-accelerator-on-aws#209]
**Is your feature request related to a problem? Please describe.**
New landing zone with barely any client workloads in it currently. Via the LZA, we have the following controls enabled in security hub:
- AWS Foundational Security Best Practices v1.0.0
- CIS AWS Foundations Benchmark v1.4.0

And our security hub is full of high-priority alerts:

> ECR private repositories should have image scanning configured
> 
> [ECR.1] This control checks whether a private ECR repository has image scanning configured. This control fails if a private ECR repository doesn’t have image scanning configured. Remediation instructions 

except that every single instance of this alert is for a resource that the LZA created and all have the format `cdk-accel-container-assets-${account_num}`.

**Describe the feature you'd like**
I would expect the LZA to create resources in a manner consistent with the usual security controls, especially since (as far as I can tell) basic scanning for ECRs is free/included in the service. I could understand this being left off/out if it was a paid addition.

**Comment by roncanepa-tufts** [comment]
Hi @awsclemj , Thank you for the response.  I do see the details as to why this change was made, but I'm not seeing the workaround steps that you mentioned.  Do you have a pointer, please?

**Comment by awsclemj** [comment]
Absolutely! The recommendation is to set up image scanning at the registry level, which covers all repositories in an account. Basic scanning is set up by default per the documentation: https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry-settings.html

I hope this helps!

**Comment by roncanepa-tufts** [comment]
Thank you, I overlooked that bit.

I would like to highlight that having to go along behind the LZA to clean up and mitigate alerts for resources that the LZA isn't actually creating/using is not an ideal state.  Especially because this is a multiplicative issue where the more accounts we create and regions we operate in (an operating model emphasized and encouraged by the LZA), the more work it means for us to clear these alerts. It has to become part of a "new account" workflow either manually or requires more effort on our part to automate the remediation since this has to be done for each and every `account * regions` combination.  We also can't disable the securityhub rule entirely in case a workload account owner decides to use ECR.  It doesn't matter to me whether it's handled eventually by the CDK or if the LZA can implement its own mitigations but I do feel that this is something that I shouldn't have to manage.

Thank you as always for your help and efforts.

**Comment by kisst** [comment]
While not the same case, it's very strongly linked, also from AWS Foundations Benchmark, also related to cdk-accel-container-assets ECR repos, and also about scanning, but this time it's scan on push, as now the scan is on that part is solved.

So the Q is did anyone consider to create a customisation via CFN CR to get this handled within the scope of LZA itself?
As in create a CloudFormation template which is deployed across the Org from LZA, and it contains a definition of a Custom Resource with Lambda, and then deploy a "Hardening" which set the "scan on push" to true on all "cdk-accel-container-assets" repo ? 

If no one got it yet, I am happy to get a crack of it, however unsure what would be a best way to make this customization part of the public domain, is there any library of "extensions" or customizations for LZA, and if it exist already then someone might addressed this before.

**Comment by peter-eisch** [comment]
> So the Q is did anyone consider to create a customisation via CFN CR to get this handled within the scope of LZA itself? As in create a CloudFormation template which is deployed across the Org from LZA, and it contains a definition of a Custom Resource with Lambda, and then deploy a "Hardening" which set the "scan on push" to true on all "cdk-accel-container-assets" repo ?
> 

I've not found documentation for creating extensions in the source/custom-config-rules BUT a lambda which sources cli commands to be executed as a remediation might be an option until CDK has this capability.
