### ISSUE TITLE
Any changes to transit Gateway fail at bootstrap step

### ISSUE THREAD

**Issue by joshbfei** [awslabs/landing-zone-accelerator-on-aws#21]
**Describe the bug**
I had been using landing accelerator and deployed a few VPCs/subnets/Routes and a transit gateway. 

Lately (Starting Sept 23) any change to a transit gateway attachment causes the build to fail at the bootstrap step with "error:  undefined". This problem coincided with v1.2.1 

**To Reproduce**
Deploy a network with Transit Gateway and attachment on v1.2.0,  make any to change to transit gateway attachment and deploy on v1.2.1

**Expected behavior**
boot strap would either emit an error from the build, or continue with CDK Synth

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.1.0]
v1.2.1

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: [e.g. us-east-1]:
 us-east-1
- [ ] Was the solution modified from the version published on this repository?
no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?
<html>
<body>

[2022-10-31 20:00:20] - info:       [network-vpc-stack] Adding Transit Gateway Attachment for Network-Main.TG
288 | [2022-10-31 20:00:20] - error:  undefined
289 | Subprocess exited with error 1
290 | error Command failed with exit code 1.
291 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
292 |  
293 | [Container] 2022/10/31 20:00:20 Command did not exit successfully if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi exit status 1
294 | [Container] 2022/10/31 20:00:20 Phase complete: BUILD State: FAILED
295 | [Container] 2022/10/31 20:00:20 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1
296 | [Container] 2022/10/31 20:00:20 Entering phase POST_BUILD
297 | [Container] 2022/10/31 20:00:20 Phase complete: POST_BUILD State: SUCCEEDED
298 | [Container] 2022/10/31 20:00:20 Phase context status code:  Message:
299

<br class="Apple-interchange-newline">
</body>
</html>

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by joshbfei** [comment]
To expand on this some, I  have found that other additions also cause the same error. For example I attempted to added a network firewall and experienced the same behavior. I have tried increasing the compute resources and memory in the CodeDeploy pipeline but there was no change.

**Comment by awsclemj** [comment]
Hello @joshbfei, we are working to improve the `error: undefined` issue in our next release. This typically is due to a typographical error in the configuration file. If possible, can you provide your network-config.yaml file both before and after the change so we may validate the syntax? Please omit any personal details in the file if applicable. Thanks!

**Comment by joshbfei** [comment]
@awsclemj, thank you for the response, I had walked away from this effort for a while and am just now looking again. In reviewing the changes between the successful and failing configuration I am 99% sure it is due to the "account"  option on the transit gateway attachment. I had referenced the account that owns the VPC the attachment will attach TO instead of the owning account of the transit gateway. Reviewing the example configuration I now see that the account on a transit gateway attachment should always reference the owner of the TG.


     transitGatewayAttachments:
       - name: Spoke01-TGA
         transitGateway:
           name: Network-Main.TG
           account: Network-Main   ##<-- This account should always be the TG owner, not the attached VPC account owner
         routeTableAssociations:
           - Network-Main-Spoke.RT
         routeTablePropagations:
           - Network-Main-Spoke.RT
           - Network-Main.RT
         subnets:
           - Spoke01TransitGatewayAttach-A.SN
           - Spoke01TransitGatewayAttach-B.SN

**Comment by erwaxler** [comment]
@joshbfei After correcting the account on the transit gateway attachment, were you able to move forward successfully?

**Comment by awsclemj** [comment]
We are currently working on improving our config validation for the network configuration and will include a check to ensure the TGW attachment config checks for the referenced TGW in the specified account. These updates will make it into our next minor release. 

I will go ahead and close this issue. Thank you for the feedback!

**Comment by joshbfei** [comment]
@erwaxler , Yes I was able to move forward (at least past the TGW error).  Thank you for your help. 

@awsclemj , Very glad to hear about the validation check. Looking forward to it.
