### ISSUE TITLE
Customizations - CloudFormationStack doesn't appear to use Transform: "AWS::LanguageExtensions"

### ISSUE THREAD

**Issue by rdkls** [awslabs/landing-zone-accelerator-on-aws#211]
**Describe the bug**
My goal is to deploy an IAM OIDC Identity Provider + Role, only to specific accounts.

To do this I have a custom cloudformation stack with a Mapping keyed on Account ID, a Condition based on AWS::AccountId being in the mapping, and resources using this Condition (only created if it exists).

It has at top `Transform: "AWS::LanguageExtensions"`

The mapping is like:
```
Mappings:
  AccountSubConditionMapping:
    "123456789012": # my-account
      "sub": "project_path:myorg/myproj:ref_type:branch:ref:main"
```

Then later I have a condition based on the current account id being a key in the mapping:
```
Conditions:
  AccountSupportsGitlabCicd: !Not
    - !Equals
      - Fn::FindInMap:
          - AccountSubConditionMapping
          - !Ref "AWS::AccountId"
          - "sub"
          - DefaultValue: ""
      - ""
```

However the FindInMap (using the DefaultValue, which uses the LanguageExtensions transform) throws an error if it can't find the current account id in the map.

I also tried working around this using Fn::Length, but the codebuild bootstrap step then failed saying Fn::Length wasn't a function.
It seems to be the LanguageExtensions transform may not be getting applied?

At this point I think my workaround will be explicitly specifying accounts in customizations-config.yaml deploymentTargets

**To Reproduce**
Create custom cloudformation as above

**Expected behavior**
Resources do not get deployed if account id is not a key in the mapping

**Please complete the following information about the solution:**

- [1.4.1 ] Version: [e.g. v1.1.0]
- [ap-southeast-2 ] Region: [e.g. us-east-1]
- [no ] Was the solution modified from the version published on this repository?
- [- ] If the answer to the previous question was yes, are the changes available on GitHub?
- [n/a ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [n/a ] Were there any errors in the CloudWatch Logs?

**Comment by nagmesh** [comment]
Hello @rdkls 
Thank you for your reaching out.
We use cfn-include to work with existing templates and cfn-include [does not handle transforms currently](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloudformation_include-readme.html#migrating-templates-that-use-transforms). 
I hope this was helpful! I will be closing this issue, but please feel free to follow-up or open new issues as you have additional questions. Thank you for your interest in Landing Zone Accelerator!
