### ISSUE TITLE
Newly Created Loggroups recieve solution defined retention period

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#213]
**Describe the bug**
Cloudwatch log groups once created have the LZA solution defined retention period set. 

**To Reproduce**
Apply the following config:
global-config.yaml
~~~yaml
cloudwatchLogRetentionInDays: 3653
...
logging:
  cloudwatchLogs:
    enabled: true
~~~
Where [cloudwatchLogRetentionInDays](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#cloudwatchLogRetentionInDays) is defined as:
> CloudWatchLogs retention in days, accelerator's custom resource lambda function logs retention period is configured based on this value.

Navigate to an account that is not excluded by `logging.cloudwatchLogs.exclusions` configuration and create a new log group.
It will have the solution retention period applied.

**Expected behavior**
1. Is this expected? If so, update  [cloudwatchLogRetentionInDays](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#cloudwatchLogRetentionInDays) description to reflect this the upper limit create to newly created log groups. This will cause a race condition with any other method of creating logGroups (with retention).
2. Feature request to allow custom retention periods, eg `logging.cloudwatchLogs.retentionRules` where user can specify in a similar convention to that of  `logging.cloudwatchLogs.exclusions`

**Please complete the following information about the solution:**

- [x] Version: [development/v1.4.3](https://github.com/awslabs/landing-zone-accelerator-on-aws/compare/development/v1.4.3) , https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/34a8e4d1e41c0d7a0c6dbdf3424f1653032fa4c5 

- [x] Region: `ap-southeast-2`
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
Cloudtrail entry of solution applying retention
~~~json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "BBB:AWSAccelerator-LoggingSta-NewCloudWatchLogsCreateE-03n6XnQjRYEr",
        "arn": "arn:aws:sts::xxxx:assumed-role/AWSAccelerator-LoggingSta-NewCloudWatchLogsCreateE-1LYQNF3GK44GX/AWSAccelerator-LoggingSta-NewCloudWatchLogsCreateE-03n6XnQjRYEr",
        "accountId": "123456789101",
        "accessKeyId": "AAA",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "BBB",
                "arn": "arn:aws:iam::123456789101:role/AWSAccelerator-LoggingSta-NewCloudWatchLogsCreateE-1LYQNF3GK44GX",
                "accountId": "123456789101",
                "userName": "AWSAccelerator-LoggingSta-NewCloudWatchLogsCreateE-1LYQNF3GK44GX"
            },
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2023-07-20T01:50:46Z",
                "mfaAuthenticated": "false"
            }
        }
    },
    "eventTime": "2023-07-20T01:50:47Z",
    "eventSource": "logs.amazonaws.com",
    "eventName": "PutRetentionPolicy",
    "awsRegion": "ap-southeast-2",
    "sourceIPAddress": "52.63.249.205",
    "userAgent": "aws-sdk-nodejs/2.1374.0 linux/v16.20.0 exec-env/AWS_Lambda_nodejs16.x AwsSolution/SO0199/1.4.2 promise",
    "requestParameters": {
        "logGroupName": "richardtest",
        "retentionInDays": 3653
    },
    "responseElements": null,
    "requestID": "be3390a2-e5ae-4905-bf14-eb053fd61e36",
    "eventID": "6edca2d2-9172-4056-a987-810fdf1ef65d",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "apiVersion": "20140328",
    "managementEvent": true,
    "recipientAccountId": "123456789101",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "logs.ap-southeast-2.amazonaws.com"
    }
}
~~~
**Additional context**

**Comment by padebnat** [comment]
Hello @richardkeit,

Thank you for reaching out to the Landing Zone Accelerator team. 

cloudwatchLogRetentionInDays in global config is used to set retention for solution deployed CloudWatch logs and any new CloudWatch logs created outside the solution. Solution only updates retention when existing retention value is less than the value specified for this parameter. 

We have created issue in our backlog to update documentation for cloudwatchLogRetentionInDays.
We are also looking into the feature request for custom retention periods; however, we cannot currently provide an ETA for when the feature will be available against our current planned feature roadmap.
Thank you for your support and interest of the LZA solution! I will leave this issue open should you have any follow-ups for the team.

**Comment by awsclemj** [comment]
Hello,

Our [documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#cloudwatchLogRetentionInDays) has been updated as of our v1.5.0 release to clarify the behavior. Thank you for reporting this! I will mark this issue as resolved.

**Comment by bakharzy** [comment]
@awsclemj  can you please update the link you provided in the last comment? It seems it has moved.

**Comment by bakharzy** [comment]
@awsclemj I tried to set the `cloudwatchLogRetentionInDays` to a lower number (730), but I receive error when trying to run the pipeline. Does this mean that I cannot change the retention duration?

**Comment by richardkeit** [comment]
Hi @bakharzy ,

Can you please add the error message for context for the AWS team?

Thanks

**Comment by bakharzy** [comment]
Below is the error message. Pipeline fails in prepare stage and complains about `RetentionInDays` property in network-config.yaml file below vpcFlowLogs. I also changed the `RetentionInDays` property to match the value of `cloudwatchLogRetentionInDays`, but didn't help and received same error. 
![Screenshot 2024-04-11 at 9 56 10](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/1803773/569a844e-8c5e-4a0c-8013-75fe3878ab57)

**Comment by bakharzy** [comment]
Ok found the issue! It seems retention can be only some specific values: 
1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, 3653,

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/acb6f296bf996993945a54ca2907badfd9ee2020/source/packages/%40aws-accelerator/config/validator/security-config-validator.ts#L343

This needs to be documented here:
https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.GlobalConfig.html#cloudwatchLogRetentionInDays

**Comment by padebnat** [comment]
Hi @bakharzy,
Yes, CloudWatch log retention value can be selected from this list. In order to update the documentation, we have created a backlog item.
