### ISSUE TITLE
managedActiveDirectorie creation error without R53 resolver rule name

### ISSUE THREAD

**Issue by DonthineniSagar** [awslabs/landing-zone-accelerator-on-aws#226]
**Describe the bug**
I am trying to create managedActiveDirectories- ms-AD standard edition as its a standalone AD ( not connecting to on-premise), i expect R53 resolverRuleName property should be optional. However if i validate the config without this property validation fails.

**To Reproduce**
create a managedActiveDirectories with resolverRuleName property and validate the config.

**Expected behavior**
It should create Microsoft AD- standard/enterprise edition without R53 resolver rule.

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.4.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [x] Region: ap-southeast-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? NA
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? NA

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
<img width="1199" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/108803545/a637a96f-6725-4a9a-b1c7-c0a87dcf332e">
 
<img width="557" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/108803545/bcb75c18-c145-462f-b801-3d02a609a3ea">

**Additional context**

**Comment by awsclemj** [comment]
Hello,

A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
