### ISSUE TITLE
bug: parameters in CloudFormationStackConfig not working

### ISSUE THREAD

**Issue by dannysteenman** [awslabs/landing-zone-accelerator-on-aws#227]
**Describe the bug**
The validate-config tool fails to validate the customizations-config.yaml file when introducing the following parameters to the stack as property.

**To Reproduce**
Create a stack in the customizations-config.yaml file e.g.

```
customizations:
  cloudFormationStackSets: []
  cloudFormationStacks:
    - name: CloudnationAccessRoles
      description: Deploys a set of roles named with CloudNation, to easily identify and to support the organisation.
      regions:
        - eu-central-1
      deploymentTargets:
        organizationalUnits:
          - Root
      runOrder: 1
      template: ./cfn-templates/cloudnation-access-roles.yaml
      parameters:
        - name: CreateAdminRole
          value: true
      terminationProtection: true
```

Next run the validate-config tool and it shows the following output:

```
aws-cn-landing-zone-accelerator/source on  main via  v18.17.0 took 9s
✗ yarn validate-config ../../aws-accelerator-config
yarn run v1.22.19
$ ts-node $PWD/packages/@aws-accelerator/accelerator/lib/config-validator.ts ../../aws-accelerator-config
2023-08-03 13:20:29.659 | info | config-validator | Config source directory -  ../../aws-accelerator-config
2023-08-03 13:20:29.676 | info | accounts-config-validator | accounts-config.yaml file validation started
2023-08-03 13:20:29.677 | info | global-config-validator | global-config.yaml file validation started
2023-08-03 13:20:29.677 | info | iam-config-validator | iam-config.yaml file validation started
2023-08-03 13:20:29.678 | info | network-config-validator | network-config.yaml file validation started
2023-08-03 13:20:29.682 | info | organization-config-validator | organization-config.yaml file validation started
2023-08-03 13:20:29.682 | info | security-config-validator | security-config.yaml file validation started
2023-08-03 13:20:29.683 | warn | config-validator | Config file validation failed !!!
2023-08-03 13:20:29.683 | warn | config-validator | Error: Could not parse content:
* Invalid value true supplied to /customizations/cloudFormationStacks/1/parameters/0/value in customizations-config.yaml config file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I update the value of the parameter to use quotes:

```
      parameters:
        - name: CreateAdminRole
          value: "true"
```

Then the validation is successful. 

I've used the docs to setup the parameters: https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CloudFormationStackConfig.html#parameters

**Expected behavior**
Working parameters functionality

**Please complete the following information about the solution:**

- [ ] Version: [ v1.4.3]

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by dannysteenman** [comment]
Another thing, I've deployed the custom cfn template, however after deployment I noticed the parameters weren't injected into the template.

**Comment by awsclemj** [comment]
Hello, and thank you for reaching out to the Landing Zone Accelerator team!

This validation error is expected behavior, as we only accept string type parameters in our current implementation. `true` is evaluated to a boolean in YAML syntax when it is included without the string quotes, which is why the error is thrown. 

I will close this issue as resolved, but please don’t hesitate to reach out to us or [AWS Support](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/aws-support.html) should you have any additional questions/issues with the solution. Thank you!
