### ISSUE TITLE
Operations Stack Fails Because '*' Invalid Principal Type

### ISSUE THREAD

**Issue by hypori-github** [awslabs/landing-zone-accelerator-on-aws#228]
**Describe the bug**
Pipeline fails on Operatons stack for applying S3 bucket policy to aws-accelerator-cur-XXXXXXXXXX-us-east-1 with error 'Invalid principal in policy".  

**To Reproduce**
Deploy Accelerator pipeline on v1.4.3 in GovCloud

**Expected behavior**
Operations stack fails for ReportBucketPolicy because '*' cannot be used as principal in S3 bucket policy.

**Please complete the following information about the solution:**

- [ ] Version: 1.4.3

- [ ] Region: us-gov-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? N/A

**Screenshots**

**Additional context**
Manually attempting to apply the S3 bucket policy fails also because '*' is not acceptable for principal in policy.

**Comment by nagmesh** [comment]
Hello @hypori-github,

Thanks for bringing this to our attentions.
Cost and Usage reports are only available in standard partitions so its not possible to reference the service principal. 
We will track this issue internally and release a fix.

**Comment by nagmesh** [comment]
A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
