### ISSUE TITLE
LZA doesn't support permission boundary in lza configuarion

### ISSUE THREAD

**Issue by JoyXinhongChen** [awslabs/landing-zone-accelerator-on-aws#231]
LZA doesn't support permission boundaries in identity center configuration
Tried different syntax still doesn't work, reached out to aws support (AWS support Case ID 12680944021), and the temp solution is to attach them manually in identity center.
But every time we make any change in LZA iam configuration, the manual permission boundary attachments are gone in the identity center.

**Comment by lucashalbert** [comment]
@bo1984 - Is there an ETA on when this backlog feature will be worked on and potentially released? I'm trying to determine if I should leverage a different mechanism in the meantime depending on if it's a ways out on the road map.

**Comment by bo1984** [comment]
Hi @lucashalbert , unfortunately I do not have a timeline on when this feature will be implemented. As a temporary workaround, you could make use of our customizations feature that utilizes AWS CloudFormation templates to provision resources. Specifically, you could make use of the PutPermissionsBoundaryToPermissionsSet API call, which is non-destructive (meaning that the resource will be re-created by CloudFormation).

**Comment by awsclemj** [comment]
Hello,

A feature enhancement for Identity Center permissions boundaries has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
