### ISSUE TITLE
Centralizing VPC Flow Logs

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#235]
centralized logging is stated in the document but I am trying to get the VPC flow logs to centralize.

I have them creating locally to each account in an S3 bucket but need them in the log account 

i am not seeing a place for ARN destination in the config 

https://awslabs.github.io/landing-zone-accelerator-on-aws/variables/_aws_accelerator_config.vpcFlowLogsConfig-1.html

code below 

vpcFlowLogs:
  trafficType: ALL
  maxAggregationInterval: 600
  destinations:
    - s3
    - cloud-watch-logs
  destinationsConfig:
    cloudWatchLogs:
      retentionInDays: 30
    s3:
  defaultFormat: false
  customFields:
    - version
    - account-id
    - interface-id
    - srcaddr
    - dstaddr
    - srcport
    - dstport
    - protocol
    - packets
    - bytes
    - start
    - end
    - action
    - log-status
    - vpc-id
    - subnet-id
    - instance-id
    - tcp-flags
    - type
    - pkt-srcaddr
    - pkt-dstaddr
    - region
    - az-id
    - pkt-src-aws-service
    - pkt-dst-aws-service
    - flow-direction
    - traffic-path

**Comment by m-j-gardner** [comment]
As far as I've been able to gather, you can only configure VPC flow logs via LZA for VPCs created by LZA.  We don't create any VPCs that way so AWS advised us to either use Customizations for Control Tower (CfCT) or a config rule and remediation.

The latter can be deployed by LZA so we're giving that a go with config rule `VPC_FLOW_LOGS_ENABLED` and remediation ssm doc `AWS-EnableVPCFlowLogs`.

**Comment by awsclemj** [comment]
Hello @frankscalzo,

We have recently updated our [centralized logging documentation](https://github.com/awslabs/landing-zone-accelerator-on-aws#log-centralization-methods) to clarify the behavior of VPC flow logs when using S3 as a destination. The buckets are created per-account and are then replicated to the central logs bucket. Please note as @m-j-gardner mentioned that only solution-deployed VPCs will have this enabled by default. If deploying VPCs outside of LZA, you will either need to target the bucket created by LZA or target CloudWatch Logs, which are also replicated to the central S3 bucket. 

Thank you for your support of the solution! I will mark this issue as resolved.
