### ISSUE TITLE
AssumedByConfig to allow Condition

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#238]
Currently the `assumedBy` key as part of the [RoleConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.RoleConfig.html#assumedBy) allows only 2x inputs:
1. [type](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html#type): `"service" | "account" | "provider"`
2. [princpal](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html#principal): string: ''

This limits the controls that can be enforced.

**Describe the feature you'd like**
Would like the ability to insert conditions in the [AssumedByConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.AssumedByConfig.html) for example:
~~~yaml
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: central-team-role
        path: platform
        instanceProfile: false
        assumedBy:
          - type: account
            principal: Tooling
            ### new functionality
            condition:
              StringLike:
                 aws:PrincipalArn: arn:aws:iam::${ACCEL_LOOKUP::AccountId:Tooling}:role/my-platform-role
            ### end new functionality block
        policies:
          customerManaged:
            - central-team-policy
~~~

1. [Condition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html) - this would allow administrators : 
     - To limit use of roles by service (eg using [aws:SourceAccount](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceaccount ) which is considered by practice for defending against confused deputy) 
     - Restrict based on Principal - doing at the condition level doesn't require the LZA engine to manage deployment order (as if it were at the Principal level)
2. New `ACCEL_LOOKUP::AccountId` namespace for the [$ACCEL_LOOKUP Reference Variable](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-solution-specific-variables.html#accel_lookup-reference-variable) functionality
    - Allow administrator to restrict based on different AWS Account Ids (currently limited to the mandatory account set) 
    
    
**Additional context**

**Comment by bo1984** [comment]
Hi Richard!

Thanks for reaching out. As part of the 1.8.0 release, we support the ability to specify a `principalArn` type for the IAM Role's trust policy. This is what that configuration would look like.

```
assumedBy:
  - type: principalArn
    principal: 'arn:aws:iam::111122223333:role/path/role-name'
```

**Comment by richardkeit** [comment]
Hi @bo1984 ,

Apologies that I missed this notification, while I do follow all issue updates more closely - the tagging (@richardkeit) does help bubble things up.

While this change closely resembles the solution, it does not solve the problem of not having access to the Condition attribute of the Trust Policy.
This is particularly important when the Principal does not exist yet (and/or the ARN is dynamic in nature, eg when not specifying the `RoleName` in the `AWS::IAM::Role` resource) when creating the role.

While I did my best to give an example in the description, this is the specific AWS reference on [Principals](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-roles) and the behind the scenes lookup that occurs:

> If your Principal element in a role trust policy contains an ARN that points to a specific IAM role, then that ARN transforms to the role unique principal ID when you save the policy. This helps mitigate the risk of someone escalating their privileges by removing and recreating the role. You don't normally see this ID in the console, because IAM uses a reverse transformation back to the role ARN when the trust policy is displayed. However, if you delete the role, then you break the relationship. The policy no longer applies, even if you recreate the role because the new role has a new principal ID that does not match the ID stored in the trust policy. When this happens, the principal ID appears in resource-based policies because AWS can no longer map it back to a valid ARN. The end result is that if you delete and recreate a role referenced in a trust policy's Principal element, you must edit the role in the policy to replace the principal ID with the correct ARN. The ARN once again transforms into the role's new principal ID when you save the policy. For more information, see [Understanding AWS's Handling of Deleted IAM roles in Policies](https://repost.aws/articles/ARSqFcxvd7R9u-gcFD9nmA5g/understanding-aws-s-handling-of-deleted-iam-roles-in-policies).

Also, it is worth mentioning that a Principal that does not exist yet results in a failure to create the Role (as the lookup cannot occur)
