### ISSUE TITLE
The maximum number of VPCs has been reached.

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#241]
Hi,

Trying to change my network-config.yaml setup to match the centralized inbound and outbound inspection account. I am doing it on the pre-prod account where nothing spectacular was implemented already, just couple of tests.

My new network-config.yaml includes one VPC for main Network account and one templateVpc for all the workload accounts. However, when trying to deploy it for further testing, I am getting below on Deploy (Network_VPCs) step:

```

Failed resources:
--
1189 | AWSAccelerator-NetworkVpcStack-141804913778-eu-west-2 \| 12:25:58 PM \| CREATE_FAILED        \| AWS::EC2::VPC                         \| MainVpcVpc (MainVpcVpc92BED2A6) Resource handler returned message: "The maximum number of VPCs has been reached. (Service: Ec2, Status Code: 400, Request ID: 5ce9e2b3-ab97-48ae-9110-21df5e97e9b5)" (RequestToken: 79d65bb7-1d80-c629-18dc-b61fe9935538, HandlerErrorCode: GeneralServiceException)
1190 | new Vpc (/codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ec2/vpc.ts:524:22)
1191 | \_ new NetworkVpcStack (/codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-vpc-stack.ts:436:21)
1192 | \_ main (/codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:760:28)
1193 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
1194 | \_ async /codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:846:5
1195 |  
1196 | ❌  AWSAccelerator-NetworkVpcStack-141804913778-eu-west-2 failed: Error: The stack named AWSAccelerator-NetworkVpcStack-141804913778-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The maximum number of VPCs has been reached. (Service: Ec2, Status Code: 400, Request ID: 5ce9e2b3-ab97-48ae-9110-21df5e97e9b5)" (RequestToken: 79d65bb7-1d80-c629-18dc-b61fe9935538, HandlerErrorCode: GeneralServiceException)
1197 | at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src2584/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
1198 | at runMicrotasks (<anonymous>)
1199 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
1200 | at async deployStack (/codebuild/output/src2584/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
1201 | at async /codebuild/output/src2584/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:39:11
1202 | at async run (/codebuild/output/src2584/src/s3/00/source/node_modules/p-queue/dist/index.js:163:29)
1203 |  
1204 | ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-NetworkVpcStack-141804913778-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The maximum number of VPCs has been reached. (Service: Ec2, Status Code: 400, Request ID: 5ce9e2b3-ab97-48ae-9110-21df5e97e9b5)" (RequestToken: 79d65bb7-1d80-c629-18dc-b61fe9935538, HandlerErrorCode: GeneralServiceException)
1205 | at Object.exports.deployStacks (/codebuild/output/src2584/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
1206 | at runMicrotasks (<anonymous>)
1207 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
1208 | at async CdkToolkit.deploy (/codebuild/output/src2584/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
1209 | at async Function.execute (/codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:289:9)
1210 | at async Promise.all (index 3)
1211 | at async Function.run (/codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:488:5)
1212 | at async /codebuild/output/src2584/src/s3/00/source/packages/@aws-accelerator/accelerator/cdk.ts:95:3
1213 | 2023-08-22 12:28:34.991 \| error \| toolkit \| Stack Deployments Failed: Error: The stack named AWSAccelerator-NetworkVpcStack-141804913778-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The maximum number of VPCs has been reached. (Service: Ec2, Status Code: 400, Request ID: 5ce9e2b3-ab97-48ae-9110-21df5e97e9b5)" (RequestToken: 79d65bb7-1d80-c629-18dc-b61fe9935538, HandlerErrorCode: GeneralServiceException)
1214 | Deployment failed
1215 | error Command failed with exit code 1.
1216 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1217 |  
1218 | [Container] 2023/08/22 12:28:35 Command did not exit successfully yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out exit status 1
1219 | [Container] 2023/08/22 12:28:35 Phase complete: BUILD State: FAILED
1220 | [Container] 2023/08/22 12:28:35 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out. Reason: exit status 1
1221 | [Container] 2023/08/22 12:28:35 Entering phase POST_BUILD
1222 | [Container] 2023/08/22 12:28:35 Phase complete: POST_BUILD State: SUCCEEDED

```

Any idea on what is going on here and how can I fix it? I'm not sure if "maximum number of VPCs" is an actual issue given only one VPC per account has been setup so far.

Thanks,
Jacek

**Comment by bhkhatri221** [comment]
Hello @jacekhewko, thank you for filing an issue with the Landing Zone Accelerator team!

To ensure we have all relevant details for this issue, can you please log in to the account where vpc is created and verify the number of vpc's ?

Thanks, and we look forward to hearing back from you!

**Comment by jacekhewko** [comment]
...what's more, I can't even go back to my "previous" successfully deployed configuration as I am keep getting the same error now.

**Comment by awsclemj** [comment]
Hi @jacekhewko, and thank you for getting back to us!

This is a account-level service quota issue and not directly related to LZA. The default maximum number of VPCs per account is 5. You can request a service quota limit increase for the number of allowed VPCs in your account following the link in the table in [this reference](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html).

I hope this helps!

**Comment by jacekhewko** [comment]
@awsclemj Thanks for the reply.

This means that whenever we change anything in the yaml configs, the resources that has been changed are not really changed (or removed) in the corresponding accounts, but new resources are being created instead.

Does it mean that LZA can only safely create resources, but changing or destroying them is impossible and has to be managed manually? What is the official best practice scenario for modifying resources in the LZA config files, then?

Thanks a lot.

**Comment by awsclemj** [comment]
Hello,

It is possible the CloudFormation orphaned the resources if there were still dependent resources deployed in the VPCs. This could be any number of things, such as an interface/gateway endpoint or EC2 instance created outside of LZA. You would see a DELETE_FAILED message in the corresponding CloudFormation stack event logs should that be the case. Generally, removing resources from the configuration file will remove them from your environment in any other case.

If you can confirm the VPCs are no longer in your configuration file, you may safely clean up any leftover dependencies and delete them using the AWS management console. For future reference, [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/configuration-file-best-practices.html) are our best practices page for managing resources in your configuration files, including resources with downstream dependencies. 

I hope this helps!

**Comment by awsclemj** [comment]
Hello,

We haven’t heard from you in a while on this issue. I will go ahead and mark this as resolved. Please don’t hesitate to contact us or [AWS Support](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/aws-support.html) should you encounter additional issues with the solution.

Thank you for your support of Landing Zone Accelerator!
