### ISSUE TITLE
How to reference existed provider to rolSets in iam-config.yaml file? 

### ISSUE THREAD

**Issue by Shra234** [awslabs/landing-zone-accelerator-on-aws#246]
**Describe the bug**
I am using an existing provider that was created by LZA, and now I need to reference it to iam-config.yaml file under the roleSets.

```iam-config.yaml

roleSets:
   - deploymentTargets:
          organizationalUnits:
              - Root
      roles:
         - name: DevOps-Access-Role
           assumedBy:
              - type: provider
                principal: arn:aws:iam::<accountNo>:saml-provider/AWSSSO_DO_NOT_DELETE
           policies:
              awsManaged:
                  - AWSSupportAccess
                  - ReadOnlyAccess
                  - AWSBackupOperatorAccess

In the above file, the principal arn caused the below error

| error | app | Cannot read properties of undefined (reading 'samlProviderArn')
| error | toolkit | TypeError: Cannot read properties of undefined (reading 'samlProviderArn')
| error | accelerator | Runtime Error

/codebuild/output/src3611/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:56
--
throw new Error('Synthesis failed');
^
Error: Synthesis failed
     at process.<anonymous> (/codebuild/output/src3611/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:41:9)
     at process.emit (node:events:525:35)
     at process.emit (node:domain:489:12)
     at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src3611/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
     at process._fatalException (node:internal/process/execution:149:25)

**Comment by awsclemj** [comment]
Hello,

For the `provider` principal type, you may reference the `name` property of a SAML provider defined in [SamlProviderConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SamlProviderConfig.html). LZA does not support referencing a provider ARN  in this manner.

I hope this helps! Please let us know if you have any follow-up questions. Thank you for your interest in the solution!

**Comment by Shra234** [comment]
Thank you for the response.
so I implemented it as mentioned above and still getting an error

samlProviderConfig:
   - name: AWSSSO_DO_NOT_DELETE
     metadataDocument: SamlProviderConfig/metadata.xml
roleSets:
   - deploymentTargets:
          organizationalUnits:
              - Root
      roles:
         - name: DevOps-Access-Role
           assumedBy:
              - type: provider
                principal: AWSSSO_DO_NOT_DELETE
           policies:
              awsManaged:
                  - AWSSupportAccess
                  - ReadOnlyAccess
                  - AWSBackupOperatorAccess
                  
The error

| info \| AWSAccelerator-OperationsStack-273340211028-ap-southeast-2 \| Role - assumed by type(provider) principal(AWSSSO_16604d50d1bc8dec_DO_NOT_DELETE)
| error \| app \| Cannot read properties of undefined (reading 'samlProviderArn')
| error \| toolkit \| TypeError: Cannot read properties of undefined (reading 'samlProviderArn')
| error \| accelerator \| Runtime Error
 /codebuild/output/src758/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:56
 throw new Error('Synthesis failed');
 ^

Error: Synthesis failed
      at process.<anonymous> (/codebuild/output/src758/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:41:9)
      at process.emit (node:events:525:35)
      at process.emit (node:domain:489:12)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src758/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
      at process._fatalException (node:internal/process/execution:149:25)
Subprocess exited with error 7

**Comment by Shra234** [comment]
I also tried the following, but it is not working for the existing provider. It failed at the deployment stage. So the question is how to reference existing provider to rolSets. 

```iam-config.yaml

providers:
   - name: AWSSSO_DO_NOT_DELETE
     metadataDocument: SamlProviderConfig/metadata.xml
roleSets:
   - deploymentTargets:
          organizationalUnits:
              - Root
      roles:
         - name: DevOps-Access-Role
           assumedBy:
              - type: provider
                principal: AWSSSO_DO_NOT_DELETE
           policies:
              awsManaged:
                  - AWSSupportAccess
                  - ReadOnlyAccess
                  - AWSBackupOperatorAccess

**Comment by awsclemj** [comment]
Hello @Shra234,

Are you attempting to reference a SAML provider that already exists in your environment (not deployed with LZA)? If so, that feature is not currently available. I'd be happy to file a feature request on your behalf should that be your use case. In the meantime, you may use [CustomizationConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CustomizationConfig.html) or other external infrastructure as code in order to deploy your IAM roles. 

If this is not what you are trying to accomplish, can you please provide more details on the error you're experiencing during SAML provider deployment?

Thank you!

**Comment by Shra234** [comment]
Hi @awsclemj,
The SAML provider is created by CT, and I just want to reference the existing SAML provider to roleSets in "iam-config.yaml" file. It should be supported because I am not using random existing providers.

**Comment by awsclemj** [comment]
Hi @Shra234 ,

You may want to have a look at [IdentityCenterConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IdentityCenterConfig.html). The config you are applying is intended for external SAML-based IdPs, not AWS Identity Center (formerly SSO). I hope this information helps to unblock you. 

Note: we are aware of an API throttling issue when creating many permission sets and assignments in one pipeline run. This issue will be fixed in our upcoming release.

**Comment by Shra234** [comment]
Hi @awsclemj,

We want to create a custom role, and the role can be assumed with the existing SAML Provider created by Control Tower. IdentityCenterConfig will not create custom roles. It will create permission sets. 

So, still, a problem is how to reference existing SAML providers to custom-created roles under the roleSets in "iam-config.yaml" file.

Thank You

**Comment by awsclemj** [comment]
Hello,

Do you happen to have a link to reference the configuration you’re attempting to apply? I am unclear how this role would work with AWS Identity Center if it is not managed by a permission set assignment. Typically with the role type that you are trying to create, there is an external SAML IdP that performs the authentication process, not AWS Identity Center. 

When you assign a permission set to a user or group in AWS Identity Center, that automatically creates a managed role for you based that the user or group can assume in the SSO sign-in console or AWS CLI [(reference)](https://docs.aws.amazon.com/singlesignon/latest/userguide/get-started-assign-account-access-admin-user.html). 

What you are trying to configure is not supported by the LZA, but given a reference to your use case I’d be happy to file a feature request for our team to consider.

Thank you!

**Comment by Shra234** [comment]
Hi @awsclemj,

Currently, we will use the Identity Center but it would be nice if is possible to assign the Identity Center role or the role created by CT to "roleSets". I understand now that it only supports external SAML Idp not the AWS Identity Center.

If you can file the feature request to support the Identity Center SSO reference to roleSet role then it will be nice.

Thank You again for clarifying that roldeSet roles only support external SAML Idp

**Comment by bo1984** [comment]
Hello,

We have an issue already tracking this issue. I will keep this issue open and keep you up to date once this has been implemented.

**Comment by erwaxler** [comment]
Hi @Shra234 ,

As of Landing Zone Accelerator v1.8.0 we now support additional functionality around role trust policies. Please see this page for more information on how you can use these new configuration options to create a trust relationship with additional principal types:

https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.AssumedByConfig.html

Thank you for your support of the Landing Zone Accelerator!
