### ISSUE TITLE
The ipam-pool ID does not exist

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#247]
Hey,

I am having below error when trying to deploy new networking config:

```
  AWSAccelerator-NetworkPrepStack-xxxxxxxxxx-eu-west-2 failed: Error: The stack named AWSAccelerator-NetworkPrepStack-xxxxxxxxxx-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The ipam-pool ID 'ipam-pool-04d342923c1aa7209' does not exist (Service: Ec2, Status Code: 400, Request ID: 61d35190-06b8-4b8d-9a86-ec9ef4c43c4d)" (RequestToken: cfebb57c-8e39-30e2-e2ff-f647aaaaf261, HandlerErrorCode: NotFound)
```

This is probably due to the "clean-up" we performed manually before running the pipeline - turns out we removed too much IPAMS. My question is: how do we recover from this and move on? Is it possible to force the pipeline to create new ipams and resources instead of looking for the old one?

Another issue is - we are forced to do "manual cleaning" before running new LZA configs as it seems like LZA is not good ad modifying or removing resources. How should we manage it?

As a temporary work-around I've just changed all IPAM names in the config file.

**Comment by awsclemj** [comment]
Hello @jacekhewko,

When running into a resource not found error, that typically means the resource has been deleted outside of the LZA configuration files and as such the environment is in a drifted state. I would recommend reading through the guidance [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/configuration-file-best-practices.html) for managing your LZA-deployed resources.

Please also note that LZA is [fully supported](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/aws-support.html) by AWS Support, and you may open such inquiries with them if you have a qualifying support plan. 

Thank you for your interest in the LZA solution! I will close this issue as resolved, but feel free to write me back if you have any follow-up questions.
