### ISSUE TITLE
Cannot have more than 1 builds in queue (AccountLimitExceeded)

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#249]
Hi,

Not sure if this is a bug or known limitation, but it turns out that you can only deploy a single AWS account at a time in the accounts-config.yaml, or the Pipeline will fail:

<img width="580" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/50452852/b5751acb-666d-4bb6-bff0-365a7d252d23">

It is not a big issue when you have 2 accounts to add, but becomes a problem if you need to deploy more, especially given than a single Pipeline run can last over 40 minutes.

What is odd, though, is that all 3 accounts had been created despite the error - but we still can't be sure if all of the required configurations had been applied inside the accounts, too, unless we have successful pipeline run. And the real issue is - we are unable to fix this error, re-runs are not helping.

How can we fix it?

Thank you,
Jacek

**Comment by awsclemj** [comment]
Hello,

Please see the comment in this issue for additional guidance: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/243 

I hope this helps. Please let us know if this solves your issue. Thank you for your interest in the solution!

**Comment by david-midlink** [comment]
Hello @jacekhewko 

I encountered the same problem. I requested an expansion of the service quotas in CodeBuild for "Concurrently running builds" and it resolved the issue for me. I hope this helps.

**Comment by awsclemj** [comment]
Hello,

We haven’t heard from you in a while on this issue. I will go ahead and mark this as resolved. Please don’t hesitate to contact us or [AWS Support](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/aws-support.html) should you encounter additional issues with the solution.

Thank you for your support of Landing Zone Accelerator!

**Comment by HeskethGD** [comment]
This is silly. Why do I need to request to be able to run more than 1? Why can't you just bill me for what I use? Why is it set to 1 in the first place? Why are there so many options for concurrent build service requests how am I supposed to know which one to request when all I know is something is failing in codepipeline why trying to use cdk pipelines.
