### ISSUE TITLE
New LZA fails at AWSAccelerator-InstallerProject pipeline

### ISSUE THREAD

**Issue by mgamsjager** [awslabs/landing-zone-accelerator-on-aws#252]
**Describe the bug**
Newly created lading zone with all default values fails at this pipeline

```


AWSAccelerator-PipelineStack-522963402568-eu-central-1 \| 32/35 \| 1:01:38 PM \| CREATE_FAILED        \| AWS::CodeStarNotifications::NotificationRule \| Pipeline/Resource/AcceleratorPipelineFailureNotification (PipelineAcceleratorPipelineFailureNotification5BE0EB21) Resource handler returned message: "Invalid request provided: AWS::CodeStarNotifications::NotificationRule" (RequestToken: 4d880e81-b3a4-59c3-aa5d-91f7eb92a47b, HandlerErrorCode: InvalidRequest)

```

**To Reproduce**
Deploy LZA

**Expected behavior**
Deploy LZA

**Please complete the following information about the solution:**

- [ ] Version: release/v1.4.3

- [ ] Region: eu-central1
- [ ] Was the solution modified from the version published on this repository?: **NO**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?:  **COULD NOT FIND IT**
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?. **DOESN'T SEEM TO BE THE ISSUE**
- [ ] Were there any errors in the CloudWatch Logs?: **ONLY BUILD LOGS**

**Screenshots**
<img width="2843" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/3090587/309a7d7a-9c34-4bbe-a6b1-18d075f9ef4c">

**Comment by joeshawfieldatayo** [comment]
We also hit this error in 1.5.1.. Not sure the cause as we have deployed quite a few LZA previously... Looking for a problem in the email or account names at the moment but noting is jumping out.

AWSAccelerator-PipelineStack-753660261619-us-east-1 | 29/32 | 4:23:05 PM | CREATE_FAILED        | AWS::CodeStarNotifications::NotificationRule | Pipeline/Resource/AcceleratorPipelineStatusNotification (PipelineAcceleratorPipelineStatusNotification0FCF4387) Resource handler returned message: "Invalid request provided:

**Comment by edwxamazon** [comment]
Hey guys, 

Stumble upon the same issue while trying to deploy v1.4.3, after taking a look at CloudTrail trail there is a "`CreateNotificationRule`" event showing error, the message found there basically states it is a transient condition related to the service linked role required to create the notification rule not being ready.

> "Message": "AWS CodeStar Notifications could not create the AWS CloudWatch Events managed rule in your AWS account. If this is your first time creating a notification rule, the service-linked role for AWS CodeStar Notifications might not yet exist. Creation of this role might take up to 15 minutes. Until it exists, notification rule creation will fail. Wait 15 minutes, and then try again. If this is is not the first time you are creating a notification rule, there might be a problem with a network connection, or one or more AWS services might be experiencing issues. Verify your network connection and check to see if there are any issues with AWS services in your AWS Region before trying again."

Retried (after remove the CodeCommit repo, delete the S3 bucket and related cfn stack) and it worked just fine.

**Comment by andreprawira** [comment]
got the same error, deleted the failed stack and the buckets it created, re run the pipeline and it worked
