### ISSUE TITLE
Improved usability - remove need for empty key declarations

### ISSUE THREAD

**Issue by atheiman** [awslabs/landing-zone-accelerator-on-aws#259]
To improve the usability, default empty values should exist for many keys in config yamls. For example, deploying network-config.yaml without any endpoint policies configuration requires `endpointPolicies: []`. This leads to a frustrating experience for end users

**Comment by bo1984** [comment]
Hi Austin, we understand that some of the design decisions for LZA can potentially lead to confusion and frustration. We make some of these parameters a requirement as we try to utilize best practices for our configuration. In the context of the `endpointPolicies` parameter, we make this a required object given that it ties in with the VPC Endpoints that are provisioned and we have it set to use endpoint policies as a best AWS practice. If you have any other questions or concerns, please do not hesitate to reach out.
