### ISSUE TITLE
Multi region support

### ISSUE THREAD

**Issue by satishdosapati** [awslabs/landing-zone-accelerator-on-aws#261]
I am looking for the ability to allow provisioning resources independently in multiple regions.
Not looking for DR capability.
Does lza support this functionality currently out of the box.
If so can you point me to the documentation and some best practice recommendation around the same.

**Comment by bo1984** [comment]
Hi @satishdosapati , thank you for your interest in the Landing Zone Accelerator on AWS (LZA) solution. Most of the resources that are provisioned through the LZA solution give the option of creating in certain account(s) and/or region(s). For example, our Typedocs for most of the resources give examples and valid properties that you could use to provision these resources to your desired configuration. Here's a link to our Vpc configuration:

https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.VpcConfig.html

For other configurations, we do maintain sample configurations that can be referenced and used as a starter template:

https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/reference/sample-configurations

Please let me know if you have any other questions or concerns.
