### ISSUE TITLE
Organizing account and network config for large orgs

### ISSUE THREAD

**Issue by trey2001** [awslabs/landing-zone-accelerator-on-aws#263]
I have a set up for an org with 100+ workload accounts and have a need to organize network and account configuration as it's getting to be too large in size for a file to read and manage.

Is there a better way to organize this already? Perhaps a network config folder structure as an example where I can break the configuration out into more files? Any help is appreciated.

**Comment by bo1984** [comment]
Hi @trey2001 , thank you for your feedback and utilizing the Landing Zone Accelerator on AWS solution. As of right now, we don't have immediate plans to decouple the networking config to a folder structure that you mentioned. As a workaround, if you have repeatable LAN patterns with your AWS VPCs, you want want to consider utilizing [Vpc Templates](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.VpcTemplatesConfig.html) as you can use the built-in deploymentTargets method to scale these out.

In terms of the accounts configuration, there is no method at the moment to better consolidate this config.

For your networking config, we do support the use of  [YAML anchors](https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/) though to help trim down the content of your config files. I will leave this issue open should you have any other questions or concerns.
