### ISSUE TITLE
Unhelpful error message when referencing an iam policy not available in a role deploymentTarget

### ISSUE THREAD

**Issue by atheiman** [awslabs/landing-zone-accelerator-on-aws#265]
Just worked thru a misconfiguration issue with `iam-config.yaml` that would have been much easier to debug if CodeBuild Bootstrap stage of pipeline had given a more helpful error message.

The misconfiguration was we deployed an iam policy only to a specific target account, but then tried to reference that policy in a role deployed to all accounts. This resulted in Bootstrap stage CodeBuild error message:

```
| error | accelerator | Resolution error: Resolution error: Resolution error: Cannot read properties of undefined (reading 'managedPolicyArn').
```

If the codebuild job / cdk synth could provide more information on the iam policy name not being found, the misconfiguration would have been much easier to debug, and would be a better user experience.

**Comment by bo1984** [comment]
Hi Austin, thank you for the feedback and for using the Landing Zone Accelerator on AWS solution. I have added a feature request to our backlog to improve validation messaging around the IAM config regarding your use case. If you have any other questions or concerns, please do not hesitate to reach out.
