### ISSUE TITLE
Auto-enroll new govcloud account in govcloud control tower

### ISSUE THREAD

**Issue by atheiman** [awslabs/landing-zone-accelerator-on-aws#267]
Currently we are provisioning govcloud accounts by

1. adding the account to commercial accounts-config.yaml
1. running commercial pipeline - account is created and enrolled in commercial control tower
1. adding the account to govcloud accounts-config.yaml
1. running govcloud pipeline - account is created and joined to the organization _but not enrolled in control tower_

**Comment by bhkhatri221** [comment]
Hello @atheiman , thank you for filing an issue with the Landing Zone Accelerator team ! We have identified the issue and this feature is being tracked in the upcoming release.

We will keep this issue open for tracking purposes and keep you aware of any status updates going forward. Thank you for supporting Landing Zone Accelerator!

**Comment by awsclemj** [comment]
Hello @atheiman,

A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
