### ISSUE TITLE
Logging stage fails for opt-in region ap-southeast-4 with invalid security token

### ISSUE THREAD

**Issue by luke-dau** [awslabs/landing-zone-accelerator-on-aws#269]
**Describe the bug**

Pipeline will fail during the Logging action group of the Logging stage for the opt-in region ap-southeast-4 (Melbourne) with the error “UnrecognizedClientException: The security token included in the request is invalid”. This doesn’t impact or effect the home region which, in this case, was ap-southeast-2.

Detailed error received:

AWSAccelerator-LoggingStack-############-ap-southeast-4 | 5:13:46 AM | CREATE_FAILED        | Custom::SsmGetParameterValue     | LookupCentralSnsKeyArnParameter/Resource/Default (LookupCentralSnsKeyArnParameter7F2E9F10) Received response status [FAILED] from custom resource. Message returned: UnrecognizedClientException: The security token included in the request is invalid
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: f70c4711-82c4-43f2-a1cc-1b6137b3f6f1)
    new CustomResource (/codebuild/output/src1048/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new SsmParameterLookup (/codebuild/output/src1048/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ssm/ssm-parameter-lookup.ts:88:22)
    \_ LoggingStack.createSnsForwarderFunction (/codebuild/output/src1048/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/logging-stack.ts:1302:30)
    \_ new LoggingStack (/codebuild/output/src1048/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/logging-stack.ts:156:12)
    \_ main (/codebuild/output/src1048/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:712:32)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1048/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5

**To Reproduce**

- Deploy LZA
- Implement default TSE-SE, without Control Tower
- Manually enable Melbourne region on all accounts
- In ‘global-config.yam’ > under ‘enabledRegions:’ > include ap-southeast-4 in the list
- Execute pipeline

**Expected behavior**

Pipeline to execute without failure, and accounts to be baselined in both ap-southeast-2 and ap-southeast-4

**Please complete the following information about the solution:**

- [ ] Version: v1.4.3
- [ ] Region: Home – ap-southeast-2, Opt-In – ap-southeast-4
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes two, see below:

- Log 1

2023-09-21T05:13:41.627Z	4bd3b64e-8aa1-4154-aef2-a569c0b67a18	INFO	
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:ap-southeast-4:############:function:AWSAccelerator-LoggingSta-CustomSsmGetParameterVal-6P1rXXdtbSl4",
    "ResponseURL": "...",
    "StackId": "arn:aws:cloudformation:ap-southeast-4:############:stack/AWSAccelerator-LoggingStack-############-ap-southeast-4/4cd2d940-583d-11ee-a80b-060726065302",
    "RequestId": "f70c4711-82c4-43f2-a1cc-1b6137b3f6f1",
    "LogicalResourceId": "LookupCentralSnsKeyArnParameter7F2E9F10",
    "ResourceType": "Custom::SsmGetParameterValue",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:ap-southeast-4:############:function:AWSAccelerator-LoggingSta-CustomSsmGetParameterVal-6P1rXXdtbSl4",
        "invokingAccountID": "############",
        "assumeRoleArn": "arn:aws:iam:: **LogArchive**:role/AWSAccelerator-SnsTopic-KeyArnParam-Role",
        "parameterRegion": "ap-southeast-4",
        "parameterName": "/accelerator/kms/snstopic/key-arn",
        "invokingRegion": "ap-southeast-4",
        "parameterAccountID": "**LogArchive**",
        "uuid": "366be7e8-4058-4ef9-baf1-404c1b402a9f"
    }
}

- Log 2

2023-09-21T05:13:45.912Z	4bd3b64e-8aa1-4154-aef2-a569c0b67a18	INFO	submit response to cloudformation {
  Status: 'FAILED',
  Reason: 'UnrecognizedClientException: The security token included in the request is invalid\n' +
    '    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)\n' +
    '    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
    '    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
    '    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)\n' +
    '    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n' +
    '    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
    '    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
    '    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n' +
    '    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)\n' +
    '    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)',
  StackId: 'arn:aws:cloudformation:ap-southeast-4:############:stack/AWSAccelerator-LoggingStack-############-ap-southeast-4/4cd2d940-583d-11ee-a80b-060726065302',
  RequestId: 'f70c4711-82c4-43f2-a1cc-1b6137b3f6f1',
  PhysicalResourceId: 'AWSCDK::CustomResourceProviderFramework::CREATE_FAILED',
  LogicalResourceId: 'LookupCentralSnsKeyArnParameter7F2E9F10',
  NoEcho: undefined,
  Data: undefined
}

**Screenshots**

If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/144298761/1c7bfa1a-21f1-4071-b4c8-98f5d7491374)

**Additional context**

This appears to be similar to: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/155 
Solution deployed without Control Tower as it is not available in ap-southeast-4 (Melbourne) yet.

**Comment by luke-dau** [comment]
Additional Information:

This stack actually deploys correctly in the log-archive account, it is only when the cross account STS is used that the deployment fails. See image below.

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/144298761/38ef6060-7e0d-4aaa-8dc4-1b8031b6bbe6)

**Comment by nagmesh** [comment]
Hello @luke-dau,

Thank you for your interest in Landing Zone Accelerator on AWS!
In opt-in regions regular sts token are not valid and V2 tokens need to be specified.
As per [docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-manage-tokens),

> Set the session token version. Version 1 tokens are valid only in AWS Regions that are available by default. These tokens do not work in manually enabled Regions, such as Asia Pacific (Hong Kong). Version 2 tokens are valid in all Regions. However, version 2 tokens include more characters and might affect systems where you temporarily store tokens.

Can you [use cli](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/set-security-token-service-preferences.html) to set token to V2 and retry the pipeline?

Thank you.

**Comment by nagmesh** [comment]
We are working on a feature to update the accounts with v2 token which should be available in future release.
