### ISSUE TITLE
Missing "VpnConnectionOptionsSpecification" options in the LZA 

### ISSUE THREAD

**Issue by anthonier** [awslabs/landing-zone-accelerator-on-aws#270]
**Is your feature request related to a problem? yes, we don't have option to specify the LocalIpv4NetworkCidr  & RemoteIpv4NetworkCidr in the LZA code.

LocalIpv4NetworkCidr -> (string)
The IPv4 CIDR on the customer gateway (on-premises) side of the VPN connection.
Default: 0.0.0.0/0

RemoteIpv4NetworkCidr -> (string)
The IPv4 CIDR on the Amazon Web Services side of the VPN connection.
Default: 0.0.0.0/0

**Describe the feature you'd like**
Need to have the options to add specific CIDR to the VPN connection

**Comment by bo1984** [comment]
Hello,

Thank you for using the Landing Zone Accelerator on AWS solution. I have gone ahead and file a feature request for this. In the meantime, I will leave this issue open for further communication and we will keep you up to date on this feature.
