### ISSUE TITLE
Resource Name Length Limit Check

### ISSUE THREAD

**Issue by jeffdickman** [awslabs/landing-zone-accelerator-on-aws#272]
**Is your feature request related to a problem? Please describe.**
CloudFormation has a resource naming limit of 38 characters.
LZA appends additional context onto the resource names as part of the process.
With the appended information, a resource name can exceed the 38 characters if the initial description is too verbose.

**Describe the feature you'd like**
Create a check earlier in the build process to identify if resource names are going to exceed the 38 character limit and either fix or error out at this point. 

**Additional context**
No other context.

**Comment by bo1984** [comment]
Hello @jeffdickman , thank you for using the Landing Zone Accelerator on AWS (LZA)solution and providing us feedback. For AWS CloudFormation, the actual resource name limit is 255 characters which can be verified through this [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html). In terms of the resources that are provisioned through LZA. We specifically name our constructs to avoid duplicate construct IDs, when you look at some of the resources, particularly on the networking side, we have to combine certain constructs to have unique naming constructs. Limiting the resource naming down below 38 characters would cause issues with some of these resources getting past the Prepare stage of the pipeline.

If you have any other questions please do not hesitate to contact us.
