### ISSUE TITLE
Associating PermissionSets with Management Account

### ISSUE THREAD

**Issue by jeffdickman** [awslabs/landing-zone-accelerator-on-aws#274]
**Is your feature request related to a problem? Please describe.**
The identityCenter configuration allows me to create PermissionSets for our organization.  However, these permission sets cannot be associated with an identityCenterAssignments that also grants privileges to the Management account.  This requires manually associating groups/accounts/PermissionSets for the Management account.  

If a permission set is manually associated with the management account AND associated with the other managed accounts, updating the PermissionSet or associating the PermissionSet to another account will cause CloudFormation to fail with a completely unhelpful error around access denied.

**Describe the feature you'd like**
Enable the ability to associate PermissionSets to the Management account within the same identityCenter configuration that supports the sub-accounts.

**Additional context**
None.

**Comment by bhkhatri221** [comment]
Hello @jeffdickman and thanks for your interest in Landing Zone Accelerator on AWS ! This is know issues, and we have already created an feature request in our backlog.

I am closing this issue and related feature request can be tracked as a part of [#215.](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/215). Thank you for supporting Landing Zone Accelerator!
