### ISSUE TITLE
AWSAccelerator-LoggingStack: Error Publishing Assets and Pipeline Failure

### ISSUE THREAD

**Issue by pamelaeteng26** [awslabs/landing-zone-accelerator-on-aws#279]
**Describe the bug**
The AWSAccelerator-LoggingStack encountered a failure with the following error message: "Error: Failed to publish one or more assets." This issue arises when attempting to execute the pipeline and include a specific SCP (Service Control Policy) in the list of SCPs. Below is the SCP in question:
```
{
    "Effect": "Deny",
    "Action": "s3:PutObject",
    "Resource": "*",
    "Condition": {
        "Null": {
            "s3:x-amz-server-side-encryption": true
        },
        "StringNotEquals": {
            "s3:x-amz-server-side-encryption": "aws:kms"
        }
    }
}
```

Even after modifying the SCP as follows, the issue still persists:

```
{
    "Effect": "Deny",
    "Action": "s3:PutObject",
    "Resource": "*",
    "Condition": {
        "Null": {
            "s3:x-amz-server-side-encryption": true
        }
    }
}
```

**To Reproduce**

1. Edit the current SCP configuration and insert the mentioned SCP above into the list.
2. Release the changes into the pipeline.

**Expected behavior**

The expected behavior is that no errors should occur after adding the specified SCP to the configuration. However, the current behaviour results in a failure during the pipeline execution.

Below is what the logs look like:

```
AWSAccelerator-LoggingStack-111111111111-eu-west-2 failed: Error: Failed to publish one or more assets. See the error messages above for more information.
at publishAssets(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/lib/util/asset-publishing.ts:60:11)
at processTicksAndRejections (node: internal/process/task_queues:96:5)
at sync CloudFormationDeployments.publishStackAssets(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/Lib/api/cloudformation-deployments.ts:573:7)
at sync CloudFormationDeployments.deployStack(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:420:7
at sync deployStack(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
at async/codebuild/output/src2446/src/53/00/source/node_modules/aws-cdk/lib/deploy.ts:39:11
at sync run (/codebuild/output/src2446/src/s3/00/source/node_modules/p-queue/dist/index.js:163:29
Z13
214
Deployment failed: Error: Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
216
at deployStacks(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
at processTicksAndRejections(node:internal/process/task_queues:96:5
217
at sync CdkToolkit.deploy(/codebuild/output/src2446/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
218
at sync Function.execute (/codebuild/output/src2446/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:312:9
219
at sync Function.run (/codebuild/output/src2446/src/53/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:471:7
220
221
at async/codebuild/output/src2446/src/s3/00/source/packages/@aws-accelerator/accelerator/cdk.ts:100:3
2023-10-03 18:52:36.051 | error I toolkit | Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
222 Deployment failed
223 error Command failed with exit code 1.
224 info Visit https://varnpkg.com/en/docs/cli/run for documentation about this command.

```
**Please complete the following information about the solution:**

- [x] Version:  [v1.4.3]
- [x] Region: [e.g. eu-west-2]
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes

**Comment by awsclemj** [comment]
Hello @pamelaeteng26, and thank you for opening an issue with the Landing Zone Accelerator team!

I have not been able to reproduce the error you've encountered when using either SCP statement that you mentioned in the overview. Both worked without issue in my environment. You may want to validate whether or not there are other statements in your SCP that would deny access to the `cdk-accel-assets-<account>-<region>` bucket in the account/region that you are deploying your LZA resources to. LZA requires access to this bucket to write the underlying CloudFormation templates and Lambda functions that it generates.

I hope this information is helpful! As I was unable to reproduce this issue, I will mark this issue as resolved. Please feel free to reach out to AWS Support if you are unable to determine the cause of the publishing error in your environment.

Thank you for your interest in the LZA solution!

**Comment by awsclemj** [comment]
Hello @alexhaycock,

I only had it applied to my Security, Infrastructure, and Workload OUs when I originally tested. I have deployed another pipeline successfully with the attachment set to Root. I've confirmed that the statement matches your statement exactly. 

One thing to call out: check if you have any region deny settings enabled in Control Tower or otherwise. That could potentially be a blocker for asset uploads.

I hope this helps, and thank you for your interest in the solution!

**Comment by awsclemj** [comment]
Hello @alexhaycock,

I ran another pipeline run in my test environment with your test case. I have multiple regions enabled as well. Still, the pipeline passes successfully.

I would suggest opening an AWS Support case so a support engineer may assist in evaluating what may be blocking asset uploads in your environment.

As always, thank you for your support and interest in the LZA solution!
