### ISSUE TITLE
Generate a managed policy for the Session Manager access policy instead of inline

### ISSUE THREAD

**Issue by bentterp** [awslabs/landing-zone-accelerator-on-aws#282]
**Is your feature request related to a problem? Please describe.**
When using solutions inside a workload account where instance profiles are created dynamically, Session Manager cannot be used until the access policy is manually applied to the instance profile.

**Describe the feature you'd like**
These solutions normally have support for referencing additional IAM policies and/or permission boundaries, so if the Session Manager access policy could be a customer-managed policy instead of inline, it would be easier to deploy these solutions in a workload account.

**Additional context**
One example of such a solution is ParallelCluster.

**Comment by bo1984** [comment]
Hi Bent! I've gone ahead and submitted a feature request for this issue. This should be included in our next upcoming release.
