### ISSUE TITLE
unable to update error in deploy>>operations

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#297]
i am receiving an error regarding SSO it says that the Audit account does not have permissions to create permission sets  i checked and SSO is not delegated any longer in the Audit account yet it still thinks it is how can i get around this since this is production ENV it was working fin in 1.4.3 but 1.5 and 1.5.1 have been causing this issue 

Resource handler returned message: "User: arn:aws:sts::XXXXXXXXX:assumed-role/cdk-accel-cfn-exec-role-XXXXXXXXX-us-east-1/AWSCloudFormation is not authorized to perform: sso:CreatePermissionSet (Service: SsoAdmin, Status Code: 400, Request ID: a4b447f1-XXXX-4f22-XXXX-29247a9eccab)" (RequestToken: 4369d49d-XXXX-1c36-XXXX-b20894972932, HandlerErrorCode: GeneralServiceException)

**Comment by KittieHearts42** [comment]
https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/293 not sure if this article helps you.
