### ISSUE TITLE
Does it not create an OU automatically? 

### ISSUE THREAD

**Issue by deepend-dev** [awslabs/landing-zone-accelerator-on-aws#3]
**Describe the bug**
The accelerator pipeline not able to create `infrastructure` OU on first run.

**To Reproduce**
Pipeline runs the first time

**Expected behavior**
Infrastructure OU is automatically created.

**Please complete the following information about the solution:**
- [ x ] Version: [e.g. v1.0.1]
- [ x ] Region: ap-south-1
- [ x ] Was the solution modified from the version published on this repository? No
- [ x ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ x ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [ x ] Were there any errors in the CloudWatch Logs? Nope

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://user-images.githubusercontent.com/55054090/178217443-b2029390-1808-4ee2-8af8-60dd2f7e284c.png)
![image](https://user-images.githubusercontent.com/55054090/178217523-adf38d4c-8048-489c-a0c8-d84b96c33703.png)

**Additional context**

**Comment by ninjaducloud** [comment]
I have exactly the same problem.
To fix it, I added the Infrastructure OU manually through AWS Control Tower.

However, I get another error

![Screen Shot 2022-07-11 at 12 20 22 PM](https://user-images.githubusercontent.com/83257291/178313287-1aac0663-9640-401e-af79-fe375a7606ed.png)

![Screen Shot 2022-07-11 at 12 23 46 PM](https://user-images.githubusercontent.com/83257291/178313304-2aa4ec16-944b-491e-bca1-2fff349e2450.png)

I use the default configuration files, those present in CodeCommit.
I'm using ca-central-1 rather than ap-south-1

**Comment by ninjaducloud** [comment]
@deepend-dev 
If you take a look at the sample file organization-config.yaml, they say

_If using AWS Control Tower, ensure that all the specified Organizational Units (OU) 
have been created and enrolled as the accelerator will verify that the OU layout 
matches before continuing to execute the deployment pipeline._

My comprehension is that you need to manage your OUs with Control Tower and not LZA.

**Comment by deepend-dev** [comment]
Okay so the OU needs to be created through GUI and then added to org file ... @ninjaducloud

**Comment by rgd11** [comment]
That is correct, when using the Landing Zone Accelerator on AWS with AWS Control Tower, you will need to ensure that the OU is added and properly enrolled with Control Tower. 

The definitions within the organization configuration file allow references to the OUs that are listed, such as specifying which OUs to deploy a resource to using the [deploymentTargets](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.DeploymentTargets.html#organizationalUnits)
