### ISSUE TITLE
identityCenterPermissionSets - add description

### ISSUE THREAD

**Issue by dbaileyut** [awslabs/landing-zone-accelerator-on-aws#307]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have descriptions on the Permission Sets managed by LZA

**Describe the feature you'd like**
Add description to the configuration of Permission Sets.

**Additional context**

**Comment by awsclemj** [comment]
Hello @dbaileyut, and thanks for reaching out the the Landing Zone Accelerator team

I just wanted to let you know that we are already tracking this request in #273. I will go ahead and close this out as a duplicate.

Thank you for your interest in the LZA solution!
