### ISSUE TITLE
CloudWatch Alarms does not have authorization to access the SNS topic encryption key

### ISSUE THREAD

**Issue by LawLaw443** [awslabs/landing-zone-accelerator-on-aws#31]
**Describe the bug**
LZA 1.2.2 creates the Config aggregator in the Management Account, and when I set the CloudWatch alarms deployment target to this account, the alarm default action will send the notifications to the SNS topics created in the Audit account.

I received the following error message when I created some events to trigger the alarm:
"CloudWatch Alarms does not have authorization to access the SNS topic encryption key."

To fix the issue, I have to update the key "accelerator/kms/sns/key" in the Audit account manually as following.

        {
            "Sid": "Allow_CloudWatch_for_CMK",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudwatch.amazonaws.com"
            },
            "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKey*"
            ],
            "Resource": "*"
        }

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
CloudWatch should have access to the SNS topic encryption key and the Alarm should be able to send the notifications via the topics created in the Audit account.

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.1.0] v1.2.2
- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by thi-baut** [comment]
I faced a similar problem and fixed the issue by manually adding the following to the SNS key policy: 

`        {
            "Sid": "Allow access for CW Events Service Principal",
            "Effect": "Allow",
            "Principal": {
                "Service": "events.amazonaws.com"
            },
            "Action": [
                "kms:GenerateDataKey*",
                "kms:Decrypt"
            ],
            "Resource": "*"
        }
`

**Comment by hickeydh-aws** [comment]
Hello @LawLaw443. Thank you for submitting this bug. We have reworked SNS Topics in version 1.3. The new configuration example can be found here https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SnsTopicConfig.html . Can you let us know if this resolves the issue?

**Comment by hickeydh-aws** [comment]
Please re-open the issue if you're still having a problem.

**Comment by prad9** [comment]
We are facing same problem again

**Comment by nelsonsilva-code** [comment]
@prad9 Did you manage to fix this? I'm having the same issue and I appear to have all the permissions set up (even did kms:*, sns:* and cloudwatch:* to test)
