### ISSUE TITLE
AWSAccelerator-InstallerProject fails on upgrade to release/v1.5.1

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#311]
**Describe the bug**
Installer Stack Codebuild job fails to upgrade

**To Reproduce**
`AWSAccelerator-InstallerStack` is currently on `Version 1.4.3` running the TSE sample config.
Click update stack and change `RepositoryBranchName` to `release/v1.5.1`, wait for the codebuild job to run

**Expected behavior**
Solution updates

**Please complete the following information about the solution:**

- [x] Version: release/v1.5.1
- [x] Region: ap-southeast-2
- [ ] ~Was the solution modified from the version published on this repository?~
- [ ] ~If the answer to the previous question was yes, are the changes available on GitHub?~
- [ ] ~Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?~
- [x] Were there any errors in the CloudWatch Logs?
~~~


[Container] 2023/11/02 06:20:10.928483 Phase complete: PRE_BUILD State: SUCCEEDED
--
223 | [Container] 2023/11/02 06:20:10.928500 Phase context status code:  Message:
224 | [Container] 2023/11/02 06:20:10.961637 Entering phase BUILD
225 | [Container] 2023/11/02 06:20:10.962233 Running command cd source
226 |  
227 | [Container] 2023/11/02 06:20:10.967203 Running command if [ "aws" = "aws-cn" ]; then
228 | sed -i "s#registry.yarnpkg.com#registry.npmmirror.com#g" yarn.lock;
229 | yarn config set registry https://registry.npmmirror.com
230 | fi
231 |  
232 | [Container] 2023/11/02 06:20:10.972315 Running command yarn install
233 | yarn install v1.22.19
234 | [1/4] Resolving packages...
235 | [2/4] Fetching packages...
236 | [3/4] Linking dependencies...
237 | [4/4] Building fresh packages...
238 | $ cd ../ && husky install source/.husky && cd source
239 | fatal: not a git repository (or any parent up to mount point /codebuild)
240 | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
241 | husky - git command not found, skipping install
242 | $ cd ../ && husky install source/.husky
243 | fatal: not a git repository (or any parent up to mount point /codebuild)
244 | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
245 | husky - git command not found, skipping install
246 | Done in 53.72s.
247 |  
248 | [Container] 2023/11/02 06:21:06.119333 Running command yarn lerna link
249 | yarn run v1.22.19
250 | $ /codebuild/output/src2594382541/src/source/node_modules/.bin/lerna link
251 | ERR! link The "link" command was removed by default in v7, and is no longer maintained.
252 | ERR! link Learn more about this change at https://lerna.js.org/docs/legacy-package-management
253 | error Command failed with exit code 1.
254 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
255 |  
256 | [Container] 2023/11/02 06:21:07.140452 Command did not exit successfully yarn lerna link exit status 1
257 | [Container] 2023/11/02 06:21:07.154927 Phase complete: BUILD State: FAILED
258 | [Container] 2023/11/02 06:21:07.154949 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn lerna link. Reason: exit status 1
259 | [Container] 2023/11/02 06:21:07.196885 Entering phase POST_BUILD
260 | [Container] 2023/11/02 06:21:07.197427 Running command inprogress_status_count=$(aws codepipeline get-pipeline-state --name "AWSAccelerator-Pipeline" \| grep '"status": "InProgress"' \| grep -v grep \| wc -l)


~~~

**Comment by awsclemj** [comment]
Hello @richardkeit, and thank you for creating an issue with the Landing Zone Accelerator team!

You will need to update your installer stack, as described [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-the-link-command-was-removed-error.html) in our Troubleshooting docs. For future reference, the installer stack should always be updated along with solution upgrades to ensure you have the latest features. 

Thanks for your support! I will close this issue out since there is a documented fix.

**Comment by richardkeit** [comment]
That's what was done, per the `Steps to Reproduce`

**Comment by awsclemj** [comment]
Hi again @richardkeit,

My apologies if the information that was provided was unclear. What was meant in my response was that you must also update the installer template to the latest version that is available in S3. This is an additional step on top of updating the branch name in the stack parameters. The new installer stack includes the code changes that fix the issue you’ve run into. 

Please see [step 3](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/update-the-solution.html) in Update the solution for those details. 

Thank you!

**Comment by richardkeit** [comment]
Hi @awsclemj ,

Appreciate you looping back 🙇 
I'll have to eat humble pie on this one, you sent me all the information originally.


We've created some Github actions to get started quickly and will look to double down on this documentation (and make sure people are aware, "changing the cloudformation parameter" isn't the quicker way):
~~~yaml
      - name: Deploy to the LZA Solution
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: AWSAccelerator-InstallerStack
          template: https://solutions-reference.s3.amazonaws.com/landing-zone-accelerator-on-aws/latest/AWSAccelerator-InstallerStack.template
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          parameter-overrides: >
            ManagementAccountEmail=${{ vars.AWS_MANAGEMENT_ACCOUNT_EMAIL }},
            LogArchiveAccountEmail=${{ vars.AWS_LOGARCHIVE_ACCOUNT_EMAIL }},
            AuditAccountEmail=${{ vars.AWS_AUDIT_ACCOUNT_EMAIL }},
            ApprovalStageNotifyEmailList=${{ vars.LZA_APPROVAL_STAGE_NOTIFY_EMAIL_LIST || vars.AWS_MANAGEMENT_ACCOUNT_EMAIL }},
            UseExistingConfigRepo=${{ vars.USE_EXISTING_CONFIG_REPO || 'No' }},
            ExistingConfigRepositoryName=${{ vars.EXISTING_CONFIG_REPOSITORY_NAME }},
            ExistingConfigRepositoryBranchName=${{ vars.EXISTING_CONFIG_REPOSITORY_BRANCH_NAME }},
            RepositoryBranchName=${{ vars.REPOSITORY_BRANCH_NAME || format('release/{0}', env.release_tag) }}

~~~
