### ISSUE TITLE
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}

### ISSUE THREAD

**Issue by jobalbz** [awslabs/landing-zone-accelerator-on-aws#315]
This error occurred at the Pipeline - Accounts stage. Please see below for more details of the error

====
<html>
<body>

LZADev-AccountsStack-123456789012-us-east-1 \|  97/106 \| 2:29:06 AM \| CREATE_FAILED        \| Custom::CreateServiceLinkedRole \| SecurityHubServiceLinkedRole/CreateServiceLinkedRoleResource/Default (SecurityHubServiceLinkedRoleCreateServiceLinkedRoleResource4CC7EFAA) Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}

431 | at checkExceptions (/var/runtime/node_modules/@aws-sdk/util-waiter/dist-cjs/waiter.js:26:30)
432 | at waitUntilFunctionActive (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/waiters/waitForFunctionActive.js:52:46)
433 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
434 | at async defaultInvokeFunction (/var/task/outbound.js:1:875)
435 | at async invokeUserFunction (/var/task/framework.js:1:2192)
436 | at async onEvent (/var/task/framework.js:1:369)
437 | at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: bfe55a2a-7dc6-41b3-bafc-6f51ca803777)
438 | new CustomResource (/codebuild/output/src1155/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
439 | \_ new ServiceLinkedRole (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-iam/service-linked-role.ts:89:21)
440 | \_ AccountsStack.createServiceLinkedRole (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/accelerator-stack.ts:810:31)
441 | \_ AccountsStack.createSecurityHubServiceLinkedRole (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/accelerator-stack.ts:458:12)
442 | \_ new AccountsStack (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/accounts-stack.ts:122:12)
443 | \_ createAccountsStack (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:414:27)
444 | \_ createManagementAccountStacks (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:102:22)
445 | \_ main (/codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:226:5)
446 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
447 | \_ async /codebuild/output/src1155/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5

</body>
</html>

**Comment by jobalbz** [comment]
The issue was resolved by increasing the Limit increase request Lambda's Concurrent executions limit from 10 to 100.

**Comment by jobalbz** [comment]
> > The issue was resolved by increasing the Lambda's Concurrent executions limit from 10 to 100. Other accounts' limit may have to be increased as well.
> 
> How to increase this? Is it from code or from the AWS console?

Via the AWS console - AWS Support - Service Quotas - AWS Services - AWS Lambda

**Comment by richardkeit** [comment]
@Yatingambhir85 , @jobalbz - this is also an avenue:
`global-config.yaml`
~~~yaml
limits:
  # Update Lambda concurrent executions in the Audit account.
  # https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/315
  - serviceCode: lambda
    # Lambda concurrent executions
    quotaCode: L-B99A9384
    desiredValue: 200
    deploymentTargets: # or which every deploymentTarget that is having issues
      organizationalUnits:
        - Audit 
~~~

**Comment by nniranjanmj** [comment]
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"} at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26) at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async defaultInvokeFunction (/var/task/outbound.js:1:1024) at async invokeUserFunction (/var/task/framework.js:1:2287) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 527a4483-68f9-4b37-862d-3cb7146634da)


After incresing the lambda concurent execution to 1000 also the issue still persits.
Plz help with that
