### ISSUE TITLE
Transit Gateway Cidr Blocks not supported in network config

### ISSUE THREAD

**Issue by hpf-mrnf** [awslabs/landing-zone-accelerator-on-aws#326]
<!--
**Describe the bug**
Updating LZA 1.4.2 to 1.5.1, we get this error for the AWSAccelerator-NetworkPrepStack in the Shared Network account:
**Transit Gateway CIDR block X.X.X.X/24 cannot be removed while it is in use by resource vpn-0xxxxxxxxxxxxx**.

_Resource handler returned message: "Transit Gateway CIDR block X.X.X.X/24 cannot be removed while it is in use by resource vpn-0xxxxxxxxxxxxx. (Service: Ec2, Status Code: 400, Request ID: f11d2f54-5806-434e-a783-47a64c58bd83)" (RequestToken: 53f02ac9-e9ea-4f65-a044-e55142bb4d84, HandlerErrorCode: GeneralServiceException)_

**To Reproduce**
We deployed the main TGW with LZA network-config file.
We have one TGW attachement as Direct Connect connection with a Direct Connect Gateway.
We also have 4 private VPN tunnels inside the DX connection which all terminated at the TGW. To be able to achieve this, we manually added a private CIDR block to the TGW to serve for the VPN tunnels. This feature (**TransitGatewayCidrBlocks**) is not supported by LZA yet. We believe that this is the cause of the error and we hereby request this feature be added to LZA.

`- name: Network-Main
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65521 # À valider
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Network-Main-Segregated
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: Perimeter
              account: Perimeter
          - destinationPrefixList: onpremises-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Shared
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: Perimeter
              account: Perimeter
          - destinationPrefixList: onpremises-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Onprem
        routes:
          - destinationPrefixList: awslab-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Standalone
        routes: []`

**Please complete the following information about the solution:**

- [ ] Version: 1.4.2 to 1.5.1
- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes
**Screenshots**
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/143bd99a-dce1-4899-a604-5718708a73f9)

**Comment by hpf-mrnf** [comment]
Updating LZA 1.4.2 to 1.5.1, we get this error for the AWSAccelerator-NetworkPrepStack in the Shared Network account:
**Transit Gateway CIDR block X.X.X.X/24 cannot be removed while it is in use by resource vpn-0xxxxxxxxxxxxx**.
 
_Resource handler returned message: "Transit Gateway CIDR block X.X.X.X/24 cannot be removed while it is in use by resource vpn-0xxxxxxxxxxxxx. (Service: Ec2, Status Code: 400, Request ID: f11d2f54-5806-434e-a783-47a64c58bd83)" (RequestToken: 53f02ac9-e9ea-4f65-a044-e55142bb4d84, HandlerErrorCode: GeneralServiceException)_
 
**To Reproduce**
We deployed the main TGW with LZA network-config file.
We have one TGW attachement as Direct Connect connection with a Direct Connect Gateway.
We also have 4 private VPN tunnels inside the DX connection which all terminated at the TGW. To be able to achieve this, we manually added a private CIDR block to the TGW to serve for the VPN tunnels. This feature (**TransitGatewayCidrBlocks**) is not supported by LZA yet. We believe that this is the cause of the error and we hereby request this feature be added to LZA.
 
`- name: Network-Main
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65521 # À valider
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Network-Main-Segregated
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: Perimeter
              account: Perimeter
          - destinationPrefixList: onpremises-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Shared
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: Perimeter
              account: Perimeter
          - destinationPrefixList: onpremises-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Onprem
        routes:
          - destinationPrefixList: awslab-prefix-list
            attachment:
              vpcName: Inspection
              account: Network
      - name: Network-Main-Standalone
        routes: []`
 
**Please complete the following information about the solution:**
 
- [ ] Version: 1.4.2 to 1.5.1
- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes
**Screenshots**
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/143bd99a-dce1-4899-a604-5718708a73f9)

**Comment by ryda009** [comment]
We are also experiencing this same issue, however it did not happen until going from v1.5.2 to v1.6.0. We've had a TGW CIDR for several LZA upgrades without issue until v1.6.0. We have not yet been able to duplicate in our Dev Environment.

**Comment by bo1984** [comment]
Hi @hpf-mrnf ! Thank you for utilizing the Landing Zone Accelerator on AWS (LZA) solution. We've had several end-users run into this issue when upgrading from 1.4.x version to a version after 1.5. In the 1.5 version, we remove an `Accel-P` tag from the solution which gets removed from most of the resources that add this that are supported by the LZA solution, Transit Gateways included. When `CreateTags` or `DeleteTags` API calls are done with Transit Gateway, there's a Modify API call that is performed to resolve the drift between what's in CloudFormation and the current state of your resource. CloudFormation is then attempting to get your Transit Gateway in a desired state by removing the static CIDR that you implemented.

As a workaround for customers, you can add that tag pairs to the config file, specifically for the Transit Gateways that are provisioned by LZA. I'd first validate the current Accel-P value in your TGWs, but if you're using the default value for the Accelerator prefix, you should just be able to add the following tag values in your network-config.yaml file to `ALL` Transit Gateways.

```
tags:
  - key: Accel-P
    value: AWSAccelerator
```

When a changeset is performed at the `Network-Prep` stack in the `Deployment` stage of the pipeline, CloudFormation will see that nothing has changed and the aforementioned Modify call will not be invoked. We will provide an update on when the static TGW CIDRs are natively supported in the LZA solution as part of a feature release as this current exists in our backlog.

**Comment by hpf-mrnf** [comment]
[Intranet logo]
[like]  Houessou, Pierre-François (DGR... reacted to your message:
________________________________

**Comment by bo1984** [comment]
Hello,

We have released support for static CIDR blocks (IPv4 and IPv6) in our [1.8.1 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/release/v1.8.1). This is a sample config:

```
transitGateways:
  - name: Network-Main
    transitGatewayCidrBlocks:
      - 10.0.0.0/20
      - 10.5.0.0/20
    transitGatewayIpv6CidrBlocks:
      - 2001:db8::/64
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Network-Main-Segregated
        routes: []
      - name: Network-Main-Shared
        routes: []
      - name: Network-Main-Standalone
        routes: []
```

If you're using this IP address currently and want LZA to take over, you'll have to remove the IP address from the TGW, then have LZA provision. We also support TGW Connect Attachments as part of our 1.8.0 release, but don't support direct peering as of yet. If you remove the IP address, the Connect Attachment peers will have to be brought down momentarily. Please let me know if you have any other questions or concerns.

**Comment by ryda009** [comment]
Thank you for the update.

Question:
If we currently have a ipv4 CIDR assigned manually to the TGW and run the
LZA upgrade to 1.8.1 without it defined in the yaml file  - will the "now
supported version" attempt to remove the manually assigned CIDR?

Thanks,
Ryan

**Comment by bo1984** [comment]
Hi Ryan,

It shouldn't attempt to remove it in 1.8.1. If you have another pipeline/process that added the static CIDR to the TGW, it should be fine.

**Comment by ryda009** [comment]
Thank you!
