### ISSUE TITLE
Creating Identity Center config fails to deploy due to missing SSM parameter

### ISSUE THREAD

**Issue by dsultanaabc** [awslabs/landing-zone-accelerator-on-aws#328]
**Describe the bug**
Fresh CT LZA setup. Trying to interact with a preconfigured Identity Centre with users/groups synced via Azure/SCIM (note we are delegating the IAM Identity Centre to our Audit account). 

When attempting to create an identity centre, I receive the following error during the Operations stage: 

 ❌ Deployment failed: Error [ValidationError]: Unable to fetch parameters [/accelerator/organization/security/identity-center/instance-arn] from parameter store for this account.

When I manually create the SSM parameter MANUALLY and populate it with the ARN of our identity centre, the operations stage completes successfully.

NOTE: Appears to also happen when attempting to add identityCenterAssignments:

❌ Deployment failed: Error [ValidationError]: Unable to fetch parameters [/accelerator/organization/security/identity-center/identity-store-id] from parameter store for this account.

After creating this SSM parameter MANUALLY, oepration stage completes successfully

**To Reproduce**
Edit iam-config.yaml is as below:

`identityCenter:
  name: identityCenter
  delegatedAdminAccount: Audit
providers: []
policySets: []
roleSets: []
groupSets: []
userSets: []`

Run accelerator pipeline and it fails during operations stage

**Expected behavior**
I expect the above configuration to apply, not throw an error about an SSM parameter not being available 

NOTE: When I manually create the SSM parameter MANUALLY and populate it with the ARN of our identity centre, the operations stage completes successfully.

**Please complete the following information about the solution:**

- [ 1.5.1 ] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ap-southeast-2] Region: 
- [ no ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ no ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by erwaxler** [comment]
Hi @dsultanaabc , thanks for raising this issue to the team. Identity Center resources were refactoring in the v1.7.0 release, are you still observing this behavior in the latest release?
