### ISSUE TITLE
Deployment of IdentityCenter resources via development toolkit doesnt detect changes

### ISSUE THREAD

**Issue by dsultanaabc** [awslabs/landing-zone-accelerator-on-aws#329]
**Describe the bug**
When attempting to configure IdentityCenter resources in iam-config.yaml, running the local development toolkit against a specific stage doesnt detect any changes in the stack, hence doesn't deploy any resources:

cdk synth command output:

`2023-11-16 12:27:23.404 | info | stack-utils | Stack in account <redacted> and region ap-southeast-2 using CliCredentialSynthesizer
2023-11-16 12:27:23.451 | info | AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2 | Creating StackSet Administrator Role
2023-11-16 12:27:23.464 | info | AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2 | Creating StackSet Execution Role
2023-11-16 12:27:23.479 | info | AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2 | Completed stack synthesis`

cdk deploy command output:

`i✨  Synthesis time: 0.01s

AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2: deploying... [1/1]
AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2: creating CloudFormation changeset...

 ✅  AWSAccelerator-OperationsStack-<redacted>-ap-southeast-2 (no changes)

✨  Deployment time: 1.44s
`

**Note: When I deploy changes via the accelerator pipeline, changes are detected and it deploys successfully.**

**To Reproduce**
Configure iam-config.yaml locally with changes, example:

before:
`    - name: AdministratorAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
        customerManaged: []
      sessionDuration: 60
`
after:
`    - name: PowerAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
        customerManaged: []
      sessionDuration: 60
`

Run the synth/deploy commands mentioned in step above, I expect changes to be detected in the stack

**Expected behavior**
I expect to be able to make changes to the existing stage that allows me to quickly deploy changes, as required

**Please complete the following information about the solution:**

- [ 1.5.1] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ap-southeast-2] Region: [e.g. us-east-1]
- [n ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ y ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ n ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by erwaxler** [comment]
Hi @dsultanaabc , thanks for raising this issue to the team. Identity Center resources were refactoring in the v1.7.0 release, are you still observing this behavior in the latest release?
