### ISSUE TITLE
AWS IAM Identity Center integration

### ISSUE THREAD

**Issue by flochaz** [awslabs/landing-zone-accelerator-on-aws#33]
Now that IAM Identity Center (previous AWS SSO) has a proper set of APIs (https://docs.aws.amazon.com/singlesignon/latest/APIReference/welcome.html) it would be great to be able to manage Permission sets,  Groups and account associations through LZA config.

It might be integrated in `iam-config.yaml` file.

**Comment by erwaxler** [comment]
Hi flochaz, 

Thank you for your interest in landing-zone-accelerator-on-aws. This feature was recently release as a part of v1.3.0, please see [this link](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IdentityCenterConfig.html) for instructions on configuring AWS Identity Center. 

Closing this issue as the feature has been implemented, please continue to create issues if this implementation of AWS Identity Center does not satisfy your use case.
