### ISSUE TITLE
Post v1.5.2 update `AWSAccelerator-Pipeline` fails with `1 validation error detected: Value at 'variables' failed to satisfy constraint: Member must have length greater than or equal to 1`

### ISSUE THREAD

**Issue by atfurman** [awslabs/landing-zone-accelerator-on-aws#333]
**Describe the bug**
This morning I updated our test LZA deployments to v1.5.2 as detailed in https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/update-the-solution.html

Post stack update, `AWSAccelerator-Pipeline` completed without issue. However, upon subsequent test run of the pipeline, I encountered the following error:

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/14967144/c070cdb0-4ab8-4272-8b17-88e3caa7d934)

Examination of the pipeline shows that there is an empty `Variables` stage. This appears to be a V2 feature. 
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/14967144/408df1ba-379e-436e-ae76-e9ed1997a575)

Furthermore, examination of the template indicates that it may not have been updated from the v1.5.1 release. 

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/14967144/f8d9a2d7-ebb7-48d0-9784-d9a4e24da12e)

Unclear if this is a contributing factor to this issue. 

**To Reproduce**
Update to v1.5.2 using the current template from https://s3.amazonaws.com/solutions-reference/landing-zone-accelerator-on-aws/latest/AWSAccelerator-InstallerStack.template

Attempt to `Release Change` on the `AWSAccelerator-Pipeline`. 

**Expected behavior**
.

**Please complete the following information about the solution:**

- [ ] Version: v1.5.2
- [ ] Region: [us-east-1, us-gov-west-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Were there any errors in the CloudWatch Logs? No notable errors identified thus far

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by atfurman** [comment]
Confirmed that the installer stack version in SSM is still 1.5.1:

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/14967144/ce451df9-a3ab-427b-a50b-80536e00c379)


@rgd11 It appears that v1.5.2 may not have been fully released.

**Comment by atfurman** [comment]
Would greatly appreciate recommended next steps to recover this deployment to a functional state.

**Comment by padebnat** [comment]
Can you please confirm installer stack `ACCELERATOR_REPOSITORY_BRANCH_NAME` parameter value, if the value is `release/v1.5.2`, you will need to release the `AWSAccelerator-Installer` pipeline. Kindly make sure InstallerStack version SSM parameter value is 1.5.2 before releasing installer pipeline.

**Comment by atfurman** [comment]
> Can you please confirm installer stack `ACCELERATOR_REPOSITORY_BRANCH_NAME` parameter value, if the value is `release/v1.5.2`, you will need to release the `AWSAccelerator-Installer` pipeline. Kindly make sure InstallerStack version SSM parameter value is 1.5.2 before releasing installer pipeline.

Yes, `release/v1.5.2` was used, even when the template incorrectly identified `1.5.1` as detailed above.

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/14967144/4075f149-2655-4d59-a1fd-37454638b6d6)

Am manually releasing the installer pipeline now and will report results when complete.
