### ISSUE TITLE
il-central-1 support

### ISSUE THREAD

**Issue by kuznetsov17** [awslabs/landing-zone-accelerator-on-aws#337]
Hi,

There is no possibility to deploy the solution to il-central-1 region, neither as default region, nor as workload region. Even if I use one of EU regions for deployment of Control Tower and Organization, I don't have any possibility to deploy my networking in il-central-1 out of the box.

According to [Documentation](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/regional-deployments.html) the Organizations and Control Tower should be supported in particular region to deploy the solution. Both of these services are available in il-central-1. 
When are you planning to add il-central-1 support? 
Thank you in advance!

**Comment by erwaxler** [comment]
Hi @kuznetsov17 , support for the il-central-1 region was included in v1.6.0 so I'll be closing this ticket. Thank you for supporting the Landing Zone Accelerator!
