### ISSUE TITLE
bug(doc): initial naming of extra OU created by Control Tower is called "Sandbox" while "Infrastructure" is expected

### ISSUE THREAD

**Issue by flochaz** [awslabs/landing-zone-accelerator-on-aws#34]
**Describe the bug**
When choosing Control Tower (CT) to initialise your environment it will propose to create an extra OU which by default is called "Sandbox". But the Installer is expecting it to be called "Infrastructure". It would be great to have it documented.

**To Reproduce**
Follow the LZA doc going the Control Tower way (which only mention "To set up AWS Control Tower, refer to [Getting started with AWS Control Tower](https://docs.aws.amazon.com/controltower/latest/userguide/getting-started-with-control-tower.html) in the AWS Control Tower User Guide.").
Then deploy LZA Installer with CT enabled. It will fail with an error mentioning that "Infrastructure" OU does not exists and found "Sandbox" one instead.

**Expected behavior**
Properly documented setup for CT.

**Please complete the following information about the solution:**

- [x] Version: v1.3.0

**Comment by rycerrat** [comment]
Hi @flochaz,

Thanks for the feedback on this!

We have this behavior documented in the Prerequisites Section under ```Create or modify Organizational Units``` in the link below :

https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html

Cheers!

**Comment by flochaz** [comment]
I might be missing something but nothing seems to mention that "Sandbox" default that need to be changed in CT: 


> ## For AWS Organizations based installation (without AWS Control Tower)
> 
> To set up AWS Organizations, refer to [Getting started with AWS Organizations](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started.html) in the AWS Organization User Guide.
> 
> Ensure the [Mandatory accounts](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/mandatory-accounts.html) are created. The Landing Zone Accelerator on AWS requires these three accounts at minimum to successfully deploy to your environment.
> 
> For more information on managing accounts in an AWS Organization, refer to [Managing the AWS accounts in your organization](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts.html) in the AWS Organization User Guide.

It tells you to look into accounts but nothing about OUs. Agree it says something in the section just after  but it can be a lot clearer from my point of view that "CT should create all the mandatory account automatically as well as the Sercurity OU. But the default extra OU is called Sandbox in the wizard and should be change to Infrastructure"
