### ISSUE TITLE
Budget Reports unable to set  up multiple email addresses 

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#347]
i have been trying to create a udget with multiple email addresses i have successfully down one but not 2. i have tried "" ,[] , ,,  ' ' , - and every one fails what is te correct code for multiple?

    - type: FORECASTED
      thresholdType: PERCENTAGE
      threshold: 100
      comparisonOperator: GREATER_THAN
      subscriptionType: EMAIL
      address: example-email@gmail.com , example-email3@gmail.com

**Comment by ChineduUzoka** [comment]
> i have been trying to create a udget with multiple email addresses i have successfully down one but not 2. i have tried "" ,[] , ,, ' ' , - and every one fails what is te correct code for multiple?
> 
> ```
> - type: FORECASTED
>   thresholdType: PERCENTAGE
>   threshold: 100
>   comparisonOperator: GREATER_THAN
>   subscriptionType: EMAIL
>   address: example-email@gmail.com , example-email3@gmail.com
> ```

address field is of type "list"
....
address:
  - example-email@gmail.com
  - example-email3@gmail.com

**Comment by frankscalzo** [comment]
> > i have been trying to create a udget with multiple email addresses i have successfully down one but not 2. i have tried "" ,[] , ,, ' ' , - and every one fails what is te correct code for multiple?
> > ```
> > - type: FORECASTED
> >   thresholdType: PERCENTAGE
> >   threshold: 100
> >   comparisonOperator: GREATER_THAN
> >   subscriptionType: EMAIL
> >   address: example-email@gmail.com , example-email3@gmail.com
> > ```
> 
> address field is of type "list" .... address:
> 
> * [example-email@gmail.com](mailto:example-email@gmail.com)
> * [example-email3@gmail.com](mailto:example-email3@gmail.com)

i had tried that as well looks like its not supported based on their response. did you have sucess with a list and what version if so are you running?

**Comment by bhkhatri221** [comment]
Hello @frankscalzo, 

A fix for this issue has been included in our [v1.6.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.6.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
