### ISSUE TITLE
Sagemaker API VPC endpoint does not create correct Private Hosted Zone DNS

### ISSUE THREAD

**Issue by jbarnet** [awslabs/landing-zone-accelerator-on-aws#348]
**Describe the bug**
Currently using the LZA to create centralized VPC endpoints there is a Private hosted zone that gets created and attached to all the VPCs.  The DNS name for this is currently sagemaker.api.ca-central-1.amazonaws.com however the value should be api.sagemaker.ca-central-1.amazonaws.com.  Unfortunately this does not allow communication to sagemaker via the VPC endpoints.

**To Reproduce**
Uncomment the VPC endpoint for sagemaker.api in the network config.
Create a sagemaker domain with VPC only mode.
View sagemaker studio logs to see that all requests to api.sagemaker.ca-central-1.amazonaws.com are filling due to timeout and firewall is blocking all requests.

**Expected behavior**
Private hosted zone should be api.sagemaker.ca-central-1.amazonaws.com when deploying the landing zone accelerator.

**Please complete the following information about the solution:**

- [ 1.4.2] Version: [e.g. v1.5.1]
- [ ca-central-1] Region: [e.g. us-east-1]
- [ NO] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ YES] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ YES] Were there any errors in the CloudWatch Logs?
I am seeing timeouts from Sagemaker Studio for any api calls made to api.sagemaker.ca-central-1.amazonaws.com

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
Unfortunately I cannot provide.

**Additional context**

**Comment by bo1984** [comment]
Hi Jeremy, thank you for using the Landing Zone Accelerator on AWS solution. This was an issue that was tracked and addressed in our 1.5.0 release (please see release notes [here](fix(networking): incorrect private hosted zones created for interface endpoint services with specific API subdomains)). 

```
fix(networking): incorrect private hosted zones created for interface endpoint services with specific API subdomains
```

Please upgrade to the latest LZA release and let us know if this issue continues to persist for you.
