### ISSUE TITLE
Same as https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/191

### ISSUE THREAD

**Issue by jperezpatino** [awslabs/landing-zone-accelerator-on-aws#358]
Same behavior as in https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/191 but in version 1.5.2, still facing the same issue.

**Comment by erwaxler** [comment]
Hi @jperezpatino , thanks for bringing this back up. A fix was reintroduced in [v1.6.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.6.0), can you verify that upgrading resolves the issue in your environment?
