### ISSUE TITLE
Organization Tag Policy fails while executing via AWS Codepipeline, but works when applied via console

### ISSUE THREAD

**Issue by gauravk29** [awslabs/landing-zone-accelerator-on-aws#360]
Description:
Applying an Organization tag policy fails during the Organization phase/step in CodePipeline. 

Steps to reproduce:

1) Create a tagging policy for Govcloud LZ

i) org-tag-policy.json:
`
{
  "tags": {
    "EnvironmentType": {
      "tag_key": {
        "@@assign": "EnvironmentType"
      },
      "tag_value": {
        "@@assign": [
          "Prod",
          "Staging",
          "QA",
          "Dev",
          "Core"
        ]
      }
    },
    "DataClassification": {
      "tag_key": {
        "@@assign": "DataClassification"
      },
      "tag_value": {
        "@@assign": [
          "Sensitive",
          "PII",
          "PHI",
          "CJI",
          "Public",
          "PCI"
        ]
      }
    },
    "AppID": {
      "tag_key": {
        "@@assign": "AppID"
      }
    },
    "CostCenter": {
      "tag_key": {
        "@@assign": "CostCenter"
      }
    },
    "Program": {
      "tag_key": {
        "@@assign": "Program"
      }
    },
    "AWSPartition": {
      "tag_key": {
        "@@assign": "AWSPartition"
      },
      "tag_value": {
        "@@assign": [
          "Standard",
          "GovCloud"
        ]
      }
  }
}
}
`
ii) And in the organization-config.yaml:

`- name: xxx-tagging-policy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits: 
        - Root
`

2) The Organization phase/step failed:
`❌  AWSAccelerator-OrganizationsStack-125656955281-us-gov-west-1 failed: Error: The stack named AWSAccelerator-OrganizationsStack-125656955281-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Policy Type TAG_POLICY not supported.
--
244 | at vXe (/var/task/index.js:10262:8515)
245 | at Runtime.handler (/var/task/__entrypoint__.js:1:938)
246 | at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29) (RequestId: 24f5871f-f04b-45d0-b95b-34b852a0a0f3)
247 | at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
248 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
249 | at async Object.deployStack (/codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
250 | at async /codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:105:11
251 |  
252 | ❌ Deployment failed: Error: The stack named AWSAccelerator-OrganizationsStack-125656955281-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Policy Type TAG_POLICY not supported.
253 | at vXe (/var/task/index.js:10262:8515)
254 | at Runtime.handler (/var/task/__entrypoint__.js:1:938)
255 | at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29) (RequestId: 24f5871f-f04b-45d0-b95b-34b852a0a0f3)
256 | at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
257 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
258 | at async Object.deployStack (/codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
259 | at async /codebuild/output/src3868/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:105:11
260 | 2023-12-14 01:42:28.042 \| error \| toolkit \| The stack named AWSAccelerator-OrganizationsStack-125656955281-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Policy Type TAG_POLICY not supported.
261 | at vXe (/var/task/index.js:10262:8515)`

**NOTE: The same tag policy attaches to the same OU when done manually in the AWS Console.**

**Expected behavior**
The Organization step should have been successfully executed.
NOTE: The LZ version is 1.5.2. So, the bug filed for the same issue should have been resolved. The bug number: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/191

**Please complete the following information about the solution:**

- [ ] Version: 1.5.2
- [ ] Region: us-gov-west-1
- [ ] Was the solution modified from the version published on this repository?: Just tagging policy was attached
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? No
- [ ] Were there any errors in the CloudWatch Logs? Yes. CodePipeline output for the Organization action.

**Comment by erwaxler** [comment]
Hi @gauravk29 , thanks for reaching out to the Landing Zone Accelerator team. Can you verify if this is still happening in v1.6.0 and later? I see the bug reappeared, but it should now be fixed from v1.6.0 forward.
