### ISSUE TITLE
AWSAccelerator-Pipeline errors due to quota limits

### ISSUE THREAD

**Issue by grumpper** [awslabs/landing-zone-accelerator-on-aws#361]
**Describe the bug**
The first time you deploy an LZA as per the implementation guide the "Deploy" stage fails.
This is because you have 3 steps executed in parallel - Network_Prepare, Security and Operations. Usually the "Security" step fails with `Error calling startBuild: Cannot have more than 1 builds in queue for the account (Service: AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException; Request ID: <request-id>; Proxy: null)`.
I think in the prerequisites it should be mentioned that service quotas L-2DC20C30 & L-4DDC4A99 should be increased. Or it should be mentioned that it's possible for the "Deploy" stage to fail so it should be monitored and the failed steps in it should be retried.

So to TL;DR: This issue is to signal that by default failures occur on deployment so the service quota limits that needs to be handled should be explicitly mentioned in the guide either as prerequisite or as something that could potentially occur. 

**To Reproduce**
Deploy LZA.

**Expected behavior**
No failures due to service quota limits if not mentioned in the guide.

**Please complete the following information about the solution:**

- [x] Version: `v1.5.2`
- [x] Region: `eu-west-1`
- [x] Was the solution modified from the version published on this repository? `No`
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? `Yes but after I hit the error`
- [x] Were there any errors in the CloudWatch Logs? `Yes`

**Screenshots**
n/a

**Additional context**
n/a

**Comment by erwaxler** [comment]
Hi @grumpper , this has been added to our Implementation Guide [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html#update-codebuild-conncurrency-quota) so I'll be closing this issue. We appreciate you bringing this to our attention, thanks again for supporting the Landing Zone Accelerator!

**Comment by richardkeit** [comment]
Note: This can be altered via `global-config.yaml` @grumpper 
~~~
limits:
  # Update Codebuild concurrency on the AWSAccellerator Pipleine
  # https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html#update-codebuild-conncurrency-quota
  - serviceCode: codebuild
    # Concurrently running builds for Linux/Large environment
    quotaCode: L-4DDC4A99
    desiredValue: 3
    deploymentTargets:
      accounts:
        - Management
~~~

**Comment by saccy** [comment]
Noting that this issue is still occurring for me:
service quota 'Concurrently running builds for Linux/Large environment' L-4DDC4A99 limit: `15`
LZA version: `1.8.1`

BTW, Looks like in this version almost all concurrency limits related to codebuild have been bumped to 15.
