### ISSUE TITLE
AWS Lambda End of Support for Node.js 16

### ISSUE THREAD

**Issue by BlakePierantoni** [awslabs/landing-zone-accelerator-on-aws#362]
**Describe the bug**
The lambda functions powering the Accelerator are nearing end of support. 

"We are ending support for Node.js 16 in Lambda on June 12, 2024. This follows Node.js 16 End-Of-Life (EOL) reached on September 11, 2023 [1]."

**Additional context**
Will this be updated or is an update on the roadmap?

**Comment by robertcurcio** [comment]
Not necessarily a bug, but an enhancement. Good thing is we have until June.

**Comment by johnraws** [comment]
@robertcurcio Thank you for opening this request for Landing Zone Accelerator on AWS. In v1.5.0 many of our Lambda runtime were updated to Node18, but there are a few remaining functions that are utilizing Node16. Our team has prioritized this issue to ensure there is ample time for appropriate testing before June 2024.

**Comment by tomburge** [comment]
@johnraws  its interesting that you say "many" of the Lambdas were updated to Node18. I'm showing very few that were actually updated as I'm currently at 1.5.2.

Most of the Logging related (not all) and the Managed AD ones are Node 18. The rest are Node 16.

**Comment by rob-woodworth** [comment]
I'll add that while AWS may be "supporting" node 16 until June, my understanding is that there have been no security updates to it since Sept 2023 which means that it's already possibly vulnerable which is not a great situation to be in for a service touted for use for expedited compliance in govcloud etc

**Comment by ckiernanTA** [comment]
Hi, I just wanted to check and see if there has been any movement on this one? I've been watching it since early January but I've not seen any updates on the thread. At a quick glance there looks to be 39 functions in the latest release still using node version 16.

**Comment by rjbaker** [comment]
Is there any update on this? LZA functions will become un-deployable in July.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by TobySaundersGDS** [comment]
This is becoming more urgent - @johnraws please can we get a response from the team on when this will be resolved?

**Comment by johnraws** [comment]
Our team is actively working on the next release of LZA that will include an update of the Node runtime to ensure that all functions are no longer on version 16. There has been a lot of feedback provided to the AWS Lambda team regarding the [deprecation schedule](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported) and it has now been updated to not block new function creation until February 2025. The timeline for the next release is targeted for the next few weeks as testing and security reviews are being completed prior to release.

**Comment by johnraws** [comment]
This has been included in our [v1.7.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0) so I will be closing this issue. Thanks for supporting the Landing Zone Accelerator!
