### ISSUE TITLE
Correct process for removing enabledRegion

### ISSUE THREAD

**Issue by atte-hemminki** [awslabs/landing-zone-accelerator-on-aws#364]
**Description**
Description/documentation of the correct process for disabling region in LZA is missing. We are using LZA on top of AWS Control Tower. In Control Tower and LZA we have allowed usage of 4 AWS regions. Now we would like to reduce the number of allowed regions to 3. What is the correct process taking down LZA resources from the region and ultimately setting region deny in Control Tower for that region? We currently don't have any VPC/networking in place in the region that we want to disable. 

In global-config.yaml we had
```
homeRegion: &HOME_REGION eu-west-1
enabledRegions:
  - *HOME_REGION
  - us-east-1
  - us-west-2
  - eu-central-1
```

When removing eu-central-1 and running the LZA pipeline, we still see KMS keys and S3 buckets in the eu-central-1 region. 

- [ ] LZA Version: v1.5.2
- [ ] Control Tower version: 3.2

**Comment by bo1984** [comment]
Hi @atte-hemminki! Thank you for using the Landing Zone Accelerator on AWS solution. Working backwards from why you still see KMS Keys and S3 buckets located in the `eu-central-1` region (I'm assuming the region you're removing from your LZA config) after you've removed the region and performed a pipeline run. For the S3 Buckets, we have the native constructs set to be retained as part of their termination policy. The KMS Keys are different as the KMS Keys that the LZA solution creates and manages, some are set to be retained (like the aforementioned S3 buckets) and some are set to be destroyed. Given the nature of the KMS Keys though, the keys that are set to be destroyed when the CloudFormation stack deletes, you'll see that the key still remains. This is built-in protection by the KMS service as the earliest a key can truly be deleted is 7 days (max 30 days).

If you're attempting to update your Control Tower settings to reflect in region deny. You can do so by going to the AWS Control Tower console and going to `Landing zone settings`. From there, you can click on `Modify settings` and go down to the `Select additional Regions for governance`. Then you can unselect `eu-central-1` and click on Next. This should go through the updating process for AWS Control Tower. 

I will leave this issue open should you have any other questions or concerns.

**Comment by atte-hemminki** [comment]
Hi, when I did run the pipeline removing `eu-central-1` region no CloudFormation stacks were destroyed in that region. Is that expected behavior? What is the recommended way of deleting CloudFormation stacks in the region?

**Comment by bo1984** [comment]
That is expected. If you're attempting to delete the stacks in the inactive (by LZA context) region, you can do so through the CloudFormation console. When you attempt to delete the stack, you'll be prompted with a message regarding Editing Termination Protection. By default, the Accelerator stacks are set with this as enabled. You can disable this in the console and initiate the delete stack process. It should be noted, some resources, specifically S3 Buckets and (some) KMS Keys are set to be retained in the region. So if you delete the CFN stacks, these resources will remain.

**Comment by kisst** [comment]
Not an ideal solution but ... here is a cleanup script to remove the deactivated regions.
https://gist.github.com/kisst/232b5aedff1745f6f3626a6543afed24

**Comment by Athanasii** [comment]
This is working as designed.

**Comment by kisst** [comment]
@Athanasii While that might be true , it's undocumented, hence the issue still valid , even if the "solution" is just document the process which follows the design.

In customisation it's clearly stated that removing a Stack from LZA config doesn't remove the deployed CFN Stack and needs to be removed by hand , the same statement should be the minimum for the enabled regions , and considering that the leftover footprint is much more complex I think it's worth spelling out *how* the cleanup should be done and what to expect to be left behind ( like KMS pending delete )
