### ISSUE TITLE
Link to CCCS-Medium config is broken in the sample configurations page README.md

### ISSUE THREAD

**Issue by ipnextgen** [awslabs/landing-zone-accelerator-on-aws#365]
Regional Configurations
[Canadian Centre for Cyber Security (CCCS) Cloud Medium](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config-cccs-medium/readme.md) 

is broken.

It should point to : https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium

**Comment by bo1984** [comment]
Hi Martin! Thanks for reaching out. I've gone ahead and created an issue in our backlog to address this issue.

I will keep this issue open until it's addressed and released. Please let us know if you have any additional questions or concerns in the meantime.

**Comment by bhkhatri221** [comment]
Hello @ipnextgen, 

The links to [Landing Zone Accelerator for CCCS Cloud Medium](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium) has been fixed with v1.6.0 release. I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!
