### ISSUE TITLE
LZA pipeline randomly fails in NetworkAssociationsStack

### ISSUE THREAD

**Issue by syanpriyajot** [awslabs/landing-zone-accelerator-on-aws#372]
**Describe the bug**
LZA pipeline randomly fails in Network AssociationsStack while creating Route53AssociateHostedZones even though no changes have been made to it. Below is the Error Stack from LZA pipeline logs

Failed resources:
--
1530 | AWSAccelerator-NetworkAssociationsStack-SharedServiceAccountID-ap-southeast-2 \| 12:24:27 AM \| UPDATE_FAILED        \| Custom::Route53AssociateHostedZones \| AssociateHostedZones/Resource/Default (AssociateHostedZonesF0E2F0DA) CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [4fcfc3fa-1a1a-4abd-aef7-f1abc2f45247]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
1531 | new CustomResource (/codebuild/output/src2406/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
1532 | \_ new AssociateHostedZones (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-route-53/associate-hosted-zones.ts:67:22)
1533 | \_ NetworkAssociationsStack.createHostedZoneAssociations (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-associations-stack/network-associations-stack.ts:1435:7)
1534 | \_ new NetworkAssociationsStack (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-associations-stack/network-associations-stack.ts:152:12)
1535 | \_ createNetworkAssociationsStacks (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:941:38)
1536 | \_ createMultiAccountMultiRegionStacks (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:184:38)
1537 | \_ main (/codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
1538 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
1539 | \_ async /codebuild/output/src2406/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Expect the pipeline to pass

**Please complete the following information about the solution:**

- [ v1.5.1]
- [ap-southeast-2]

**Comment by bo1984** [comment]
Hello Syan! Thank you for using the Landing Zone Accelerator on AWS solution. There is a custom resource that is using Lambda to do the hosted zone associations labeled `AWSAccelerator-NetworkAss-CustomRoute53AssociateHo-[RANDOM PREFIX]`.  For this Lambda function, can you attach the errors from the AWS CloudWatch Logs so that I can investigate further? I'd also ask if you're utilizing centralized VPC Endpoints in the config.

**Comment by syanpriyajot** [comment]
Hi @bo1984,

Yes we are using the centralized VPC Endpoints in the config.
After further investigation we have discovered that Lambda AWSAccelerator-NetworkAss-CustomRoute53AssociateHo-[RANDOM PREFIX] runs its maximum time limit of 15 mins and the CFN stack errors out with the response that it didnt receive a response. 

I have added subset of logs with timeout message as there is no error in the CloudWatch Logs.

2024-01-17T14:45:23.900+11:00 | 2024-01-17T03:45:23.900Z 74380e7d-66b4-4671-a799-85a06ba56bce INFO [AWS route53 200 0.881s 0 retries] getHostedZone({ Id: '**ZoneIDValue**' })
2024-01-17T14:45:23.900+11:00 | 2024-01-17T03:45:23.900Z 74380e7d-66b4-4671-a799-85a06ba56bce INFO vpc-id* is already attached to the hosted zone **ZoneIDValue**
2024-01-17T14:46:12.900+11:00 | 2024-01-17T03:46:12.900Z 74380e7d-66b4-4671-a799-85a06ba56bce INFO vpc-id* is already attached to the hosted zone **ZoneIDValue**
**2024-01-17T14:47:35.065+11:00 | 2024-01-17T03:47:35.064Z 74380e7d-66b4-4671-a799-85a06ba56bce Task timed out after 900.07 seconds**
2024-01-17T14:47:35.065+11:00 | REPORT RequestId: 74380e7d-66b4-4671-a799-85a06ba56bce Duration: 900071.50 ms Billed Duration: 900000 ms Memory Size: 256 MB Max Memory Used: 148 MB

Please advise what can be done to overcome this issue as we are not able to run LZA pipeline to completion because of this issue.

**Comment by andrew-ha** [comment]
Hey @bo1984 

Just add some context to @syanpriyajot 's logs, we currently have 32+ VPCs and 35+ AWS services with hosted zones. With each getHostedZone API call taking ~1s, on a best case scenario we need 1120s (or ~19min) to go through all the checks (more than 15min that Lambda allows). Just wondering what we can do to workaround this issue (e.g. script modifications to enable multithreading, CDK changes to use another compute service for custom resources other than Lambda...).

For convenience, this is the exact script that deploys the AssociateHostedZone custom resource:
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/b31d38efb86e9dda522d3ac8f7759dd93a14d9cb/source/packages/%40aws-accelerator/constructs/lib/aws-route-53/associate-hosted-zones.ts#L39

Cheers for your help so far :)

**Comment by bo1984** [comment]
Hi Andrew!

Thank you for the background on your environment (and thanks Syan for the providing the logs as requested). I can foresee some scalability issues and this definitely explains the intermittent errors that are being experienced in the Associations stack. I'm going to put in a bug ticket for this issue and investigate further how to solve for this. I will keep this issue open in the meantime should you have any other related questions or concerns.

**Comment by hickeydh-aws** [comment]
Hello,

Thanks again for raising this bug. This issue has been addressed in the latest release (v1.6.1). Please let us know if you run into any other problems.
