### ISSUE TITLE
Action Execution Failed in Logging - Key stage

### ISSUE THREAD

**Issue by zubair-k** [awslabs/landing-zone-accelerator-on-aws#392]
When executing Logging Stage ChangeSet AWSAccelerator-DependenciesStack-change-set cannot be created due to a mismatch with existing attribute ClientToken.

 Version: [v1.6.0]

❌  AWSAccelerator-KeyStack-xxx-eu-west-2 failed: AlreadyExistsException: ChangeSet AWSAccelerator-KeyStack-xxx-eu-west-2-change-set cannot be created due to a mismatch with existing attribute ClientToken
--
355 | at Request.extractError (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
356 | at Request.callListeners (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
357 | at Request.emit (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
358 | at Request.emit (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
359 | at Request.transition (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
360 | at AcceptorStateMachine.runTo (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
361 | at /codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
362 | at Request.<anonymous> (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
363 | at Request.<anonymous> (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
364 | at Request.callListeners (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
365 | code: 'AlreadyExistsException',
366 | time: 2024-02-02T09:22:41.228Z,
367 | requestId: '4a99d6fc-24b0-442e-9ee2-78a1c901fded',
368 | statusCode: 400,
369 | retryable: false,
370 | retryDelay: 215.8690592234258
371 | }
372 |  
373 | ❌ Deployment failed: AlreadyExistsException: ChangeSet AWSAccelerator-KeyStack-xxx-eu-west-2-change-set cannot be created due to a mismatch with existing attribute ClientToken
374 | at Request.extractError (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
375 | at Request.callListeners (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
376 | at Request.emit (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
377 | at Request.emit (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
378 | at Request.transition (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
379 | at AcceptorStateMachine.runTo (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
380 | at /codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
381 | at Request.<anonymous> (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
382 | at Request.<anonymous> (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
383 | at Request.callListeners (/codebuild/output/src2070/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
384 | code: 'AlreadyExistsException',
385 | time: 2024-02-02T09:22:41.228Z,
386 | requestId: '4a99d6fc-24b0-442e-9ee2-78a1c901fded',
387 | statusCode: 400,
388 | retryable: false,
389 | retryDelay: 215.8690592234258

More context to the issue reported:

We are trying to deploy [Landing Zone Accelerator on AWS TSE-SE] in a test environment
We got stuck at a code build step where CDK tries to create two changesets in parallel like below and fails with consecutive error

**Comment by zubair-k** [comment]
repeated issue on https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/342

**Comment by zubair-k** [comment]
Hi @bhkhatri221. 
1. Yes, I used the TSE-SE configurations, with the amendment needed which so far seem to be okay.
2. We had a standard LZA install before deploying TSE-SE successfully. 

It has been suggested that the error is down to running an older version of CDK toolkit and upgrading to v2 2.126.0. could help, however i'm struggling to do this through the templates so stuck without anyway of deploying at the moment. 

Thanks

**Comment by nagmesh** [comment]
Thank you for sharing the config over the case, the duplicate stacks were created as [enabledRegions](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.GlobalConfig.html#enabledRegions) in global config was duplicated. I'm going to go ahead and close this issue. 
Thank you for supporting Landing Zone Accelerator!
