### ISSUE TITLE
vpcTemplates: ability/documentation to do isolated VPCs with VPC templates (i.e. conneected to Central/shared services vpc, but isolated from each other)

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#397]
looking at vpcTemplatedConfig, i could not figure out a way to template an isolated VPC that would routhe trugh transient gateway and provide isolated templated networks.   I certainly did not find an example of that under references.  

Would certainly like to have such a feature, or, if exist, have an example how to use it (I could not figure out how to configure needed propagations with existing abstracts. ) 

Thanks!

**Comment by bhkhatri221** [comment]
Hello @snemir2, Thank you for using the Landing Zone Accelerator on AWS solution. The LZA solution currently supports [VpcConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.VpcConfig.html) to define a VPC that is deployed to a singled account and region. This might helps you implement a isolated VPCs based upon your requirements. 

If you have any other questions, please do not hesitate to reach out to us.
