### ISSUE TITLE
Suggestion: Tutorial implementation Landing Zone Accelerator

### ISSUE THREAD

**Issue by T-Nik** [awslabs/landing-zone-accelerator-on-aws#4]
I would like to suggest a tutorial to the development of the Landing Zone Accelerator which enables the user to comprehend the architectonic decision made hands on by maybe even rebuilding the solution. 

How would this contribute to the project?
- convey users security in administrating and adapting your work to companies needs while feeling save as one may understand the solution better if one rebuild it by oneself
- using the chance to teach AWS customers about applying AWS CDK in bigger project and how services integrate with each other.
- open up a bigger community of users and contributors on different skill levels

**Comment by rgd11** [comment]
Thank you @T-Nik for opening this issue. We currently provide more of these details in our [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/welcome.html), and are continually looking to improve all of our documentation, including developer guides.

Will keep this issue open for tracking purposes, as we finalize and release a developer guide that will be included as part of the solution repository.

**Comment by tbmorris** [comment]
More in depth examples would be great besides implementation guides.  I can't find the correct syntax for a security group.  References aren't always easy to interpret.

**Comment by awsclemj** [comment]
Hello @tbmorris,

With our release of v1.3.0 we have overhauled our documentation to include specific examples of configuration objects. You can find links to each included LZA feature in the [README](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md) document's feature matrix. 

Additionally, we have created [public Immersion Day content](https://catalog.workshops.aws/landing-zone-accelerator/en-US) that follows a workshop-style tutorial approach to implementing several features of the accelerator as you've suggested in this issue. 

Please let us know if these updates satisfy your request.
