### ISSUE TITLE
Incorrect use of defaultVpcs in NetworkConfig / DefaultVpcsConfig example

### ISSUE THREAD

**Issue by m-j-gardner** [awslabs/landing-zone-accelerator-on-aws#40]
I think the example use of defaultVpcs [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.DefaultVpcsConfig.html) has had an "s" appended in error as the definition [here](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/config/lib/network-config.ts#L895) and NetworkConfig class property [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html#defaultVpc) don't have that "s" at the end.

**Comment by awsclemj** [comment]
@m-j-gardner thanks for reporting this! We will fix the example in our next minor release.

**Comment by johnraws** [comment]
The documentation has been updated to reflect these changes. Thank you for providing feedback that helped identify these changes.
