### ISSUE TITLE
Security hub "excludeRegions" does not support ca-west-1 region

### ISSUE THREAD

**Issue by senyberg** [awslabs/landing-zone-accelerator-on-aws#401]
**Describe the bug**
When trying to exclude regions, all other regions are recognized correctly as regions but `ca-west-1` will throw error:

```
warn | config-validator | Error: Could not parse content:
* Value should be an AWS region. at /centralSecurityServices/securityHub/excludeRegions/20 in security-config.yaml config file
```

**To Reproduce**
Deploy securityhub with `ca-west-1` in excludeRegions:

securityHub:
    enable: true
    regionAggregation: true
    excludeRegions:
      - ap-south-2
      - ap-south-1
      - eu-south-1
      - eu-south-2
      - me-central-1
      - il-central-1
      - ca-central-1
      - eu-central-1
      - eu-central-2
      - us-west-1
      - us-west-2
      - af-south-1
      - eu-west-3
      - eu-west-2
      - ap-northeast-3
      - ap-northeast-2
      - ap-northeast-1
      - me-south-1
      - sa-east-1
      - ap-east-1
      - ca-west-1 #Fails on this
      - ap-southeast-1
      - ap-southeast-2
      - ap-southeast-3
      - ap-southeast-4
      - us-east-1
      - us-east-2

**Expected behavior**
`ca-west-1` should be allowed value

**Please complete the following information about the solution:**

- [x] Version: v1.6.0
- [x] Region: eu-north-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? => See description of bug

**Comment by tmanda-hf** [comment]
I got the same error when trying on version 1.5.1
`<html>
<body>

2024-02-21 23:17:14.698 \| warn \| config-validator \| Error: Could not parse content:
--
905 | * Value should be an AWS region. at /centralSecurityServices/securityHub/excludeRegions/6 in security-config.yaml config file
906 | error Command failed with exit code 1.


</body>
</html>`

**Comment by erwaxler** [comment]
Hello @senyberg , thank you for filing an issue with the Landing Zone Accelerator team!

This is the result of `ca-west-1` not yet existing as a valid region within the LZA source code. Ca-west-1 will be included in the next release of the LZA. We are tracking this in a separate issue here: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/430

Closing this issue as regional support is tracked in the linked ticket, please feel free to follow up if you have any outstanding questions and thank you again for supporting the Landing Zone Accelerator.
