### ISSUE TITLE
AWSAccelerator-GovCloudAccountVending.template references unsupported nodejs14.x Lambda Runtime causing the template to fail

### ISSUE THREAD

**Issue by mselvyn** [awslabs/landing-zone-accelerator-on-aws#408]
**Describe the bug**
The AWSAccelerator-GovCloudAccountVending.template to create the account vending machine references the now unsupported nodejs14.x Lambda Runtime causing the template to fail on first launch.

**To Reproduce**
Run the CloudFormation template found in Step.1 here: https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/option-2-deploy-on-new-aws-govcloud-us-accounts.html#step-1.-launch-the-stack-1

**Expected behavior**
The cloudformation to run and create the relevant resources (Account Vending Machine in the Service Catalog) without error.

**Please complete the following information about the solution:**

- [v1.2.1] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ us-east-1] Region: [e.g. us-east-1]
- [ no ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ no ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ no ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/44902643/98c54fc5-2519-4b34-86a3-f662e93d3ca8)

**Additional context**

**Comment by nagmesh** [comment]
Thank you for reporting this. We will fix this in the upcoming release.

**Comment by nagmesh** [comment]
The docs are pointing to the older version. Can you please try [this](https://s3.amazonaws.com/solutions-test-reference/landing-zone-accelerator-on-aws/latest/AWSAccelerator-GovCloudAccountVending.template) and let us know if you still see the problem?

**Comment by nagmesh** [comment]
The link has been fixed. Thank you!
