### ISSUE TITLE
Writeup on how to integrate with eks blueprint pattern

### ISSUE THREAD

**Issue by rverma-dev** [awslabs/landing-zone-accelerator-on-aws#41]
**Is your feature request related to a problem? Please describe.**
While Landing zone accelerator provides a robust framework on how to build 1 orchestrator for various accounts and network configurations, eks blueprint provide similar thoughts on orchestrating multiple eks cluster even across accounts and manage apps with gitops.
Its not very clear on how one should combine both the patterns to ensure an last mile delivery of secure containerised application.

**Describe the feature you'd like**
A writeup on how to extend landing zone to containers leveraging eke-blueprints

**Additional context**
https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/pipeline-multi-env-gitops.md

**Comment by rgd11** [comment]
@rverma-dev - Agree that this would be great information for our customers, but this is not directly related specifically to the LZA project. Ultimately, LZA will help establish an environments foundations, and additional application layer solutions can be deployed on top of the generated resources.

 Will close this issue, but please reach out if there are further questions.
