### ISSUE TITLE
Installing LZA v1.4.1 - Lambda function on node14

### ISSUE THREAD

**Issue by vzradha** [awslabs/landing-zone-accelerator-on-aws#414]
**Describe the bug**
Installing v1.4.1, still references node14 in prepare stage of the pipeline. More precisely CreateOrganizationAccounts/CreateOrganizationAccountsProvider/framework-onTimeout 

Additional context: we have a LZ running on v1.4.1 in production, spinning up a new Test Org to test lza upgrades.

**To Reproduce**

**Expected behavior**
should use node16 or higher

**Please complete the following information about the solution:**

- [ ] Version: [ v1.4.1]

- [ ] Region: [eu-west-2]
- [ ] Was the solution modified from the version published on this repository? [NO]
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? [YES]

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
CreateOrganizationAccounts/CreateOrganizationAccountsProvider/framework-onTimeout (CreateOrganizationAccountsCreateOrganizationAccountsProviderframeworkonTimeoutDD2DB516) Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 95c47b7c-db3b-4b11-9ce2-22b59442bc0c)" (RequestToken: d1e708ff-201d-342d-58eb-6c1824c0a8c4, HandlerErrorCode: InvalidRequest)

The stack named aws-accelerator-PrepareStack-xxxxxxxxxxx-eu-west-2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 95c47b7c-db3b-4b11-9ce2-22b59442bc0c)" (RequestToken: d1e708ff-201d-342d-58eb-6c1824c0a8c4, HandlerErrorCode: InvalidRequest), Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 7d474258-98ed-40f4-93b5-c7a4a4b2c011)" (RequestToken: 0ae8bfd9-54d7-e5c1-00e6-795a05532416, HandlerErrorCode: InvalidRequest)

**Comment by richardkeit** [comment]
@vzradha - LZA is up to version `v1.6.1`
Is there a reason why an upgrade hasn't been planned?

**Comment by vzradha** [comment]
@richardkeit - this part of our planning the upgrade. I wanted to get our Test Org the same version as the Prod Org, test the upgrade path for functionality before rolling it out in Prod LZ

**Comment by richardkeit** [comment]
Hi @vzradha ,
I don't believe AWS will be backward porting the lambda change as there have been 6x releases since the [1.4.1](https://github.com/awslabs/landing-zone-accelerator-on-aws/compare/v1.4.2...v1.6.1) drop and almost a year elapsed time.

In the future, I highly recommend planning updates as soon as they come out.
_Obviously this doesn't help in this case_

I encourage ensuring that the manual approval is present in the Prod organisation and running the pipeline with the latest release (with no changes other than new version).

Validate each line item of the diff there to ensure you're confident with the changes.


Good luck with it!

**Comment by vzradha** [comment]
@richardkeit - thanks, that is the plan.
