### ISSUE TITLE
Cannot update AWS Budgets notifications

### ISSUE THREAD

**Issue by yannickvr** [awslabs/landing-zone-accelerator-on-aws#418]
**Describe the bug**
When changing the notifications, CloudFormation fails deployment:

```
Deployment failed: Error: The stack named AWSAccelerator-OperationsStack-963397301107-eu-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Error creating budget: budget-org-cn-daily-acc - the budget already exists. (Service: AWSBudgets; Status Code: 400; Error Code: DuplicateRecordException; Request ID: c086dcbe-4d0b-435c-88f2-182885d47afc; Proxy: null), Error creating budget: budget-org-cn-monthly-acc - the budget already exists. (Service: AWSBudgets; Status Code: 400; Error Code: DuplicateRecordException; Request ID: 3463a79d-4e69-4893-83e8-2842ee21ebed; Proxy: null)
```

This is because the CloudFormation resource requires replacement of the resource when updating the `NotificationWithSubscribers` property, but the budgets created by LZA use the `BudgetName` property which has to be unique. 

**To Reproduce**
Deploy a budget with notification to email, then add or replace an email subscriber.

**Expected behavior**
The subscriber is added to the budget notification.

**Please complete the following information about the solution:**

- [x] Version: 1.6.1
- [x] Region: eu-west-1/us-east-1
- [x] Was the solution modified from the version published on this repository? no
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? n/a
- [x] Were there any errors in the CloudWatch Logs? see description

**Comment by bhkhatri221** [comment]
Hello @yannickvr, thank you for filing an issue with the Landing Zone Accelerator team! This is excepted behavior, and limitation from AWS Cloudformation resources requires replacement of the resource when updating the NotificationWithSubscribers property. LZA depends upon the AWS CloudFormation to perform budget actions, and end of getting the budget already exists error. For workaround this issue, please update the global-config.yaml file with the latest NotificationWithSubribers information and provide a unique name for the budgets. This should create you a new budget with the updated budget notification. 

Closing this issue, please feel free to follow up if you have questions on this issue. Thank you for supporting Landing Zone Accelerator!

**Comment by yannickvr** [comment]
@bhkhatri221 I'm aware of the CF limitation, and the workaround. Proper solutions would include:

- LZA recognizes this behaviour and deletes the resources before creating them
- LZA migrates from CloudFormation to CF Custom Resources as is the case with e.g. security hub and config
- Remove the `BudgetName` property from the CloudFormation template. This way CF autogenerates a name for the budget and updates on the LZA config are successful.

**Comment by richardkeit** [comment]
I'm in favour of `Remove the BudgetName property from the CloudFormation template. This way CF autogenerates a name for the budget and updates on the LZA config are successful.`
I think it's the most clean solution, using a reasonable LogicalId gives a good indication that it's LZA generated
