### ISSUE TITLE
Allow Organisations Units to be registered with LZA configuration

### ISSUE THREAD

**Issue by SennaSemakula** [awslabs/landing-zone-accelerator-on-aws#421]
**Is your feature request related to a problem? Please describe.**
When creating Organisations Units (OUs) there is a manual intervention required to first register the OU in the AWS Console using Control Tower and then adding the entry to LZA config. 

**Describe the feature you'd like**
Feature request to allow LZA pipelines support interacting with CT APIs to register the OUs without the initial manual step required using the console. 
I can see that it is now supported: https://aws.amazon.com/about-aws/whats-new/2024/02/aws-control-tower-apis-register-organizational-units/

**Comment by richardkeit** [comment]
@SennaSemakula - duplicate of https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/383

**Comment by SennaSemakula** [comment]
@richardkeit thanks closing this.
