### ISSUE TITLE
Network resources on a multi-region environment

### ISSUE THREAD

**Issue by jaristizabalc** [awslabs/landing-zone-accelerator-on-aws#422]
The multi region support has been addressed already on the following request:
https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/103

However my question is specific to the network resources created by the LZA. If I add the enabledRegions parameters and have 2 regions listed, what would happen to the centralized network components, for instance the TGW?

On the network-config.yaml the transit gateway has a region property pointing to the HOME_REGION, so my assumption is that any resources on a different region than HOME won't have access to shared network services, or endpoints VPC, given that I would have to define another transit GW element on the config file and specify the second region.

If this is the case, can we expect any out of the box functionality in the future to support the creation of the centralized networking environment in multiple regions and allow for inter-region TGW communication to inter connect the regions?

Thank you.

**Comment by bo1984** [comment]
Hello Juan! Thank you for reaching out and using the Landing Zone Accelerator on AWS (LZA) solution. In terms of Transit Gateways (TGW), these resources are region specific. The LZA solution currently supports cross-region peering between two TGWs. We have [documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.TransitGatewayPeeringConfig.html) that has an example of what this configuration would look like. In terms of the behavior you described, you're correct.  If you have a TGW established in a region (e.g. us-east-1) that TGW resource is created in that region. The `deploymentTargets` property for the TGW determines which accounts/OUs Resource Access Manager (RAM) shares the TGW out to (for that specific region). 

If you have any other questions, please do not hesitate to reach out to us.

**Comment by jaristizabalc** [comment]
Thank you @bo1984 , that answers my question.
