### ISSUE TITLE
Upgrade to codebuild image to 7.0

### ISSUE THREAD

**Issue by jlosito** [awslabs/landing-zone-accelerator-on-aws#428]
**Describe the bug**
There are several CodeBuild environments using Ubuntu standard 6.0, but standard 7.0 is available. This also includes the use of nodejs v16 instead of v18.

**To Reproduce**
Deploy LZA and check the build environment of each of the related CodeBuild projects.

**Expected behavior**
I expect the latest release of this solution to have the latest stable runtime environments when they become available.

**Please complete the following information about the solution:**

- [1.6.2] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [us-east-1] Region: [e.g. us-east-1]
- [No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [No] Were there any errors in the CloudWatch Logs?

**Comment by andy-nyunt** [comment]
Looking forward to future realease.  I'm getting similar warning in Trusted Advisor on nodejs version approaching deprecation

**Comment by erwaxler** [comment]
Hi @jlosito , this has been included in our [v1.7.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0) so I will be closing this issue. Thanks for supporting the Landing Zone Accelerator!
