### ISSUE TITLE
Support the new Canada West Region - ca-west-1

### ISSUE THREAD

**Issue by saedx1** [awslabs/landing-zone-accelerator-on-aws#430]
**Is your feature request related to a problem? Please describe.**
Yes. We are dealing with backups (and other things) and we want to be able to use ca-west-1.

**Describe the feature you'd like**
We would like for the ca-west-1 region to be supported.

**Additional context**
As of now, we get this error.
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/34514167/3ee273c6-2375-4a6f-b9c0-ef1b46e79c1c)

**Comment by padebnat** [comment]
Hello @saedx1 
Thank you for reaching out to the Landing Zone Accelerator team! We are working on adding support for Canada West Region - ca-west-1. This may be addressed in future releases.

**Comment by saedx1** [comment]
@padebnat  Any updates on this?
Control Tower now supports it: https://aws.amazon.com/about-aws/whats-new/2024/05/aws-control-tower-canada-west-calgary-region/

**Comment by erwaxler** [comment]
Hi @saedx1 , this has been included in our [v1.7.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0) so I will be closing this issue. Thanks for supporting the Landing Zone Accelerator!
