### ISSUE TITLE
Failure on prepare stage - Custom::LoadAcceleratorConfigTable|LoadAcceleratorConfigTable/Resource/Default

### ISSUE THREAD

**Issue by univitawssupport** [awslabs/landing-zone-accelerator-on-aws#435]
**Describe the bug**
Error when running pipeline on prepare stage.

AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 | 0/10 | 4:22:35 PM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack                         | AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 User Initiated
AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 | 0/10 | 4:22:42 PM | UPDATE_IN_PROGRESS   | Custom::LoadAcceleratorConfigTable                 | LoadAcceleratorConfigTable/Resource/Default (LoadAcceleratorConfigTable8F9D29D6) 
AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 | 0/10 | 4:22:42 PM | UPDATE_IN_PROGRESS   | Custom::GetPortfolioId                             | GetPortFolioId/Resource/Default (GetPortFolioId5CA7347E) 
AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 | 1/10 | 4:22:51 PM | UPDATE_COMPLETE      | Custom::GetPortfolioId                             | GetPortFolioId/Resource/Default (GetPortFolioId5CA7347E) 
1/10 Currently in progress: AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1, LoadAcceleratorConfigTable8F9D29D6
AWSAccelerator-PrepareStack-XXXXXXXXXXXX-us-east-1 | 1/10 | 4:23:33 PM | UPDATE_FAILED        | Custom::LoadAcceleratorConfigTable                 | LoadAcceleratorConfigTable/Resource/Default (LoadAcceleratorConfigTable8F9D29D6) Received response status [FAILED] from custom resource. Message returned: Error: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.
    at k6s (/var/task/index.js:29:110946)
    at /var/task/index.js:29:113282
    at TFo (/var/task/index.js:29:113299)
    at k6s (/var/task/index.js:29:111400)
    at W6s (/var/task/index.js:29:115579)
    at /var/task/index.js:29:116809
    at LFo (/var/task/index.js:29:116488)
    at GFo (/var/task/index.js:29:116593)
    at /var/task/index.js:29:116677
    at Array.reduce (<anonymous>) (RequestId: 3261951a-e8a4-4eb8-8a19-d272df930ef1)
    new CustomResource (/codebuild/output/src3230/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new LoadAcceleratorConfigTable (/codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/load-config-table.ts:133:22)
    \_ new PrepareStack (/codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:184:44)
    \_ createPrepareStack (/codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
    \_ createManagementAccountStacks (/codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
    \_ main (/codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src3230/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5

**To Reproduce**
Run the pipeline.

**Expected behavior**
Pipeline should run without error.

**Please complete the following information about the solution:**

- [ ] Version: v1.6.2

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Additional context**
The pipeline has run successfully several times. We encountered this issue when onboarding additional accounts.

**Comment by nagmesh** [comment]
Thank you for your interest in LZA!

- Did pipeline on 1.6.2 run without any issues?
- What were the changes made to the config?

Can you open a support case with us? In the support case please share the diff of working pipeline and current pipeline in the config. Also attach the lambda logs so we can take a look.

**Comment by univitawssupport** [comment]
The pipeline failed.

All we did was make changes to the accounts configuration yaml. There were some spaces in the names of the accounts that we had to change

Best,

Manny

From: Nagmesh Kumar ***@***.***>
Sent: Wednesday, April 17, 2024 1:01 PM
To: awslabs/landing-zone-accelerator-on-aws ***@***.***>
Cc: UnivITAWSSupport ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [awslabs/landing-zone-accelerator-on-aws] Failure on prepare stage - Custom::LoadAcceleratorConfigTable|LoadAcceleratorConfigTable/Resource/Default (Issue #435)


Thank you for your interest in LZA!

  *   Did pipeline on 1.6.2 run without any issues?
  *   What were the changes made to the config?

Can you open a support case with us? In the support case please share the diff of working pipeline and current pipeline in the config. Also attach the lambda logs so we can take a look.

**Comment by univitawssupport** [comment]
We found a missing parameter for one of the accounts in the accounts-config.yaml file.  
The missing parameter was organizationalUnit:
