### ISSUE TITLE
Issue creating VPC in Workload account: Error: Resource share Network-Main_TransitGatewayShare not found

### ISSUE THREAD

**Issue by jaristizabalc** [awslabs/landing-zone-accelerator-on-aws#439]
**Describe the bug**
Hello, while deploying a VPC in one of the workloads accounts, there was a failure due to a tagging policy blocking the creation of the network resource by the LZA, once this was resolved and the policy was removed the Pipeline runs again.

Now it keeps hitting the same issue "Resource share Network-Main_TransitGatewayShare not found" on the Deploy Stage under Network_VPCs.

`NetworkMainTransitGatewayShare/Resource/Default (NetworkMainTransitGatewayShare638AEAA9) Resource creation Initiated
AWSAccelerator-NetworkVpcStack-XXXXXXXXXX-us-east-1 | 36/43 | 9:49:37 PM | CREATE_FAILED        | Custom::GetResourceShare              | NetworkMainTransitGatewayShare/Resource/Default (NetworkMainTransitGatewayShare638AEAA9) Received response status [FAILED] from custom resource. Message returned: Error: Resource share Network-Main_TransitGatewayShare not found
    at P7t (/var/task/index.js:10266:316390)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runtime.handler (/var/task/__entrypoint__.js:1:932) (RequestId: 1d33d321-0925-4861-bb8c-70dd474c2497)
    new CustomResource (/codebuild/output/src1407/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new Import (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ram/resource-share.ts:185:26)
    \_ Function.fromLookup (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ram/resource-share.ts:207:12)
    \_ NetworkVpcStack.getResourceShare (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-stack.ts:615:41)
    \_ NetworkVpcStack.getTransitGatewayItem (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-stack.ts:463:20)
    \_ NetworkVpcStack.setVpcTransitGatewayMap (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-stack.ts:438:70)
    \_ new NetworkVpcStack (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/network-stacks/network-vpc-stack/network-vpc-stack.ts:78:36)
    \_ createNetworkVpcStacks (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:923:22)
    \_ createMultiAccountMultiRegionStacks (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:182:29)
    \_ main (/codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:243:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1407/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5`

- [ ] Version:  v1.6.2
- [ ] Region: [us-east-1]
- [ ] Was the solution modified from the version published on this repository?
The Network resources (TGW, Network Inspection VPC, etc..) were successfully deployed on the Network Account on a previous Pipeline run.
The issue is coming from the workload account where the new VPC is being created, here is the new config added to the network-config file.

 - name: UITCDC
    account: UITCDC
    region: *HOME_REGION
    cidrs:
      - 10.67.192.0/22
    routeTables:
      - name: UITCDC-Tgw-A
        routes: []
      - name: UITCDC-Tgw-B
        routes: []
      - name: UITCDC-App-A
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
      - name: UITCDC-App-B
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
          - name: S3Gateway
            type: gatewayEndpoint
            target: s3
          - name: DynamoDBGateway
            type: gatewayEndpoint
            target: dynamodb
    subnets:
      - name: UITCDC-App-A
        availabilityZone: a
        routeTable: UITCDC-App-A
        ipv4CidrBlock: 10.67.192.0/24
      - name: UITCDC-App-B
        availabilityZone: b
        routeTable: UITCDC-App-B
        ipv4CidrBlock: 10.67.193.0/24
      - name: UITCDC-MainTgwAttach-A
        availabilityZone: a
        routeTable: UITCDC-Tgw-A
        ipv4CidrBlock: 10.67.194.0/28
      - name: UITCDC-MainTgwAttach-B
        availabilityZone: b
        routeTable: UITCDC-Tgw-B
        ipv4CidrBlock: 10.67.194.16/28
    transitGatewayAttachments:
      - name: UITCDC-Main
        transitGateway:
          name: Network-Main
          account: PlatformNetwork
        routeTableAssociations:
          - Network-Main-Spoke
        routeTablePropagations:
          - Network-Main-Core
        subnets:
          - UITCDC-MainTgwAttach-A
          - UITCDC-MainTgwAttach-B
    gatewayEndpoints:
      defaultPolicy: Default
      endpoints: []
    useCentralEndpoints: true

It looks like there is some stale info somewhere, however even if I delete the failed CloudFormation stack on the workload account and re-run the Pipeline the issue reoccurs.

Thank you.

**Comment by bo1984** [comment]
Hello @jaristizabalc ! Thank you for using the Landing Zone Accelerator on AWS (LZA) solution. In the workload account that's failing to get the attachment, can you go to the Lambda console and look for the Lambda function that's named `AWSAccelerator-NetworkVpc-CustomGetResourceShareCu`? In there, we can check the AWS CloudWatch Log Group for that Lambda function and determine if (in the log stream) which calls are failing? Additionally, are you seeing the Resource Access Manager (RAM) share for the TGW to the workload account? Was there any blocks also on the RAM share as well?

**Comment by jaristizabalc** [comment]
hello @bo1984 , the Lambda function AWSAccelerator-NetworkVpc-CustomGetResourceShareCu is missing on the workload account since after the CF stack that creates it fails, it rolls back deleting this resource. However the CloudWatch logs persist, I am attaching those. As for the RAM, the share is created on the network account, however I don't see any LZA resource shared with the workload account.
[log-events-viewer-result-2.csv](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/15168344/log-events-viewer-result-2.csv)
[log-events-viewer-result.csv](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/15168345/log-events-viewer-result.csv)

**Comment by jaristizabalc** [comment]
The issue was on the TGW definition, the shareTargets parameter was not including the OU that contains the workload account. After it was added, the Pipeline successfully created the workload VPC and the TGW attachment.

ie.
transitGateways:
  - name: Network-Main
    account: Network-Prod
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
        - WorkloadOU
