### ISSUE TITLE
TSE-SE default deployment fails to apply changesets

### ISSUE THREAD

**Issue by michthom** [awslabs/landing-zone-accelerator-on-aws#442]
**Describe the bug**
Deployment of TSE-SE architecture with default configuration failed during Immersion Day during AWSAccelerator-Pipeline at stage Logging

**To Reproduce**
Follow steps in TSE-SE guide up to this section (4.3.2 Running the LZA pipeline):
https://catalog.workshops.aws/tse-sensitive-edition/en-US/deployment/tse-customization

**Expected behavior**
LZA pipeline deploys smoothly without errors

**Please complete the following information about the solution:**

- [ ] Version: v1.6.2
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs?

**Additional context**

Pipeline log error:

AWSAccelerator-KeyStack-381492233875-eu-west-2 failed: AlreadyExistsException: ChangeSet AWSAccelerator-KeyStack-381492233875-eu-west-2-change-set cannot be created due to a mismatch with existing attribute ClientToken
--
254 | at Request.extractError (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
255 | at Request.callListeners (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
256 | at Request.emit (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
257 | at Request.emit (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
258 | at Request.transition (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
259 | at AcceptorStateMachine.runTo (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
260 | at /codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
261 | at Request.<anonymous> (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
262 | at Request.<anonymous> (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
263 | at Request.callListeners (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
264 | code: 'AlreadyExistsException',
265 | time: 2024-04-30T13:46:44.577Z,
266 | requestId: '4ee58c48-7bb1-4a70-8614-0e309c87fdb9',
267 | statusCode: 400,
268 | retryable: false,
269 | retryDelay: 104.35504774403381
270 | }

Deployment failed: AlreadyExistsException: ChangeSet AWSAccelerator-KeyStack-xxxxxxxxxxxx-eu-west-2-change-set cannot be created due to a mismatch with existing attribute ClientToken
--
273 | at Request.extractError (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
274 | at Request.callListeners (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
275 | at Request.emit (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
276 | at Request.emit (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
277 | at Request.transition (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
278 | at AcceptorStateMachine.runTo (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
279 | at /codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
280 | at Request.<anonymous> (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
281 | at Request.<anonymous> (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
282 | at Request.callListeners (/codebuild/output/src784/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
283 | code: 'AlreadyExistsException',
284 | time: 2024-04-30T13:46:44.577Z,
285 | requestId: '4ee58c48-7bb1-4a70-8614-0e309c87fdb9',
286 | statusCode: 400,
287 | retryable: false,
288 | retryDelay: 104.35504774403381
289 | }

**Comment by michthom** [comment]
[aws-accelerator-config.zip](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/15165744/aws-accelerator-config.zip)

**Comment by nagmesh** [comment]
Thank you for your interest.

In accounts-config.yaml there is duplicate email

```
- name: Network
    description: The shared network account is used for shared networking resources. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: aws.emptynet+network@gmail.com  # SAME EMAIL ADDRESS as Perimeter
    organizationalUnit: Infrastructure
....
- name: Perimeter
    description: Used for Internet facing, IaaS-based ingress/egress security services
    email: aws.emptynet+network@gmail.com # SAME EMAIL ADDRESS as Network
    organizationalUnit: Infrastructure
```
Please make the emails unique to prevent this error. 

We will fix the code to validate and error in build when it see's duplicate emails.
