### ISSUE TITLE
where did the Construct pages go

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#444]
i got here https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SecurityConfig.html 

and get a 404 i use to get samples of each line and an explanation  i cant even go to the @aws-accelerator/constructs and find anything anymore did this all go away

i have modifications to do and needed to understand the policys to suppress security hub items since the rules are not working

**Comment by cknight725** [comment]
The documentation moved to typedocs, and theres some broken links ... start from here:
https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/v1.6.0/

**Comment by nagmesh** [comment]
Thank you @cknight725!

@frankscalzo Use the latest version of the typedoc pages
https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/

I'll go ahead and close this issue.
