### ISSUE TITLE
modifying LogGroup Class

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#445]
Trying to find a way to modify all the log groups LogGroupClass i cant seem to find an area to do this i would like the ability to set LogGroupClass to infrequent access not standard on some if not all log groups 

https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.LogGroupsConfig.html

**Comment by bo1984** [comment]
Hi @frankscalzo ! Thank you for utilizing the Landing Zone Accelerator on AWS (LZA) solution. AWS CloudWatch Log Groups do not support a storage class. Object storage classes are supported through Amazon S3 from this [documentation](https://aws.amazon.com/s3/storage-classes/). For the S3 buckets that are provisioned through LZA, we do support lifecycle rules for transitioning objects to different storage tiers. Here's the general [configuration](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.CentralLogBucketConfig.html) on one of the buckets (central), as well as a specific [link](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.LifeCycleRule.html#noncurrentVersionTransitions) to the lifecycle configuration documentation with the available storage tier options to you. If you have any other questions or concerns, please do not hesitate to reach out to us.

**Comment by frankscalzo** [comment]
@bo1984  thanks for the reply im looking to make it so i can use the log class sorry i wrote the wrong thing see here in console 
![Screenshot 2024-05-09 at 1 00 08 PM](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/9d9c3338-d58d-47a7-9bcb-513629e781ff)
