### ISSUE TITLE
LZA release 1.6.2 still using the soon-to-be-deprecated Nodejs 16

### ISSUE THREAD

**Issue by davez510** [awslabs/landing-zone-accelerator-on-aws#456]
**Describe the bug**
We received a notification recently via AWS Health alerts that Nodejs 16 will be deprecated on 12th June this year. We've recently updated our LZA from 1.5.x to 1.6.2 but found there are still functions in LZA that use Nodejs 16.

**To Reproduce**
Steps to reproduce the behavior.

1. Clone the repo.
2. Check out the release branch for v1.6.2.
3. Update the LZA CFN stack with the template for v1.6.2 and point the branch parameter to the release branch.

**Expected behavior**

Since LZA v1.6.2 was released recently, I expected the Nodejs runtime of its functions to be using the latest version or at least the next one after 16.x which will be deprecated next month.

**Please complete the following information about the solution:**

- [x] Version: v1.6.2

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: ap-southeast-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? Not applicable
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Not applicable
- [x] Were there any errors in the CloudWatch Logs? Not applicable

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by erwaxler** [comment]
Hi @davez510  , this has been included in our [v1.7.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.7.0) so I will be closing this issue. Thanks for supporting the Landing Zone Accelerator!
