### ISSUE TITLE
Document querying AWS Accelerator Central Logs - CloudWatch Logs

### ISSUE THREAD

**Issue by dgregan-flutter** [awslabs/landing-zone-accelerator-on-aws#460]
**Is your feature request related to a problem? Please describe.**
I am trying to query AWS Accelerator Central Logs to determine if a specific CloudWatch Log group exists and if it's data is being correctly captured. I can see it's possible to view each AWSAcc entry by adding an extension to the file name (https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/312) however to do this en masse would take a significant amount of time to determine if 1 CW Log group is being captured.

**Describe the feature you'd like**
https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/user-guide/logging/ to be updated with an example of querying logs sent to AWS Accelerator, like AWS Athena create table, query table

**Additional context**

**Comment by dgregan-flutter** [comment]
Looking into querying via AWS Athena, it seems that the files must have [relevant file extensions](https://docs.aws.amazon.com/athena/latest/ug/compression-formats.html#compression-support-notes-and-resources) in order for Athena to understand that the data is compressed before it can query.

So it seems like this method isn't viable unless the data put into `aws-accelerator-central-logs-ACC_ID-AWS_REGION)/CloudWatchLogs/` has file extension / file name suffix like `.gz`, `.zip` or however

**Comment by UnbiasedGoat** [comment]
+1 not sure the best way to accomplish this

**Comment by bfg-cloudsupport** [comment]
+1 The lack of querying without further engineering makes the central logging almost unusable. I'd assume the fix is for the LZA lambda to simply add a .gz to each object.

**Comment by bfg-cloudsupport** [comment]
I don't understand this. Why would we define what the file extension is? It should be set by LZA to the actual file type. I could define it as .jpg if I wanted. If they are gzips, they should be set by the logger as .gz. Not left up to us.
