### ISSUE TITLE
Landing Zone Pipeline failing at Network_Association stage

### ISSUE THREAD

**Issue by ateguia2019** [awslabs/landing-zone-accelerator-on-aws#461]
**Describe the bug**
We have launch the Accelerator-config pipeline today and it ended up with a failure at Network_Association Stage.
- There was no change in the configuration any configuration file.
- It look like LZA is trying to renew the ActiveDirectory Management instances with the latest image and the process is failing.
-  In the changeset we can see there is a difference between the before ami-id and the after ami-id. See the files attached for more details

![changeSetOverview](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/56047638/8c9b8129-4fb2-4a33-9a84-f85aedaf668b)
![Error_message](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/56047638/6a6828df-4a83-42b8-aeb8-267c859ea58d)
![Network_association_stack_error](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/56047638/2091d7cc-7b44-43fd-96c0-b4e48e442f00)

Below a piece of configuration related to the managedInstance in iam-config.yaml

activeDirectoryConfigurationInstance:
      instanceType: t3.large
      vpcName: Central
      subnetName: Central-App-A
      **imagePath: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base**
      securityGroupInboundSources:
        # Plage d'IP interne du MRNF
        - 10.141.0.0/17
      instanceRole: AWSAccelerator-RDGW-Role
      userDataScripts:
        - scriptName: JoinDomain
          scriptFilePath: ad-config-scripts/Join-Domain.ps1
        - scriptName: AWSQuickStart
          scriptFilePath: ad-config-scripts/AWSQuickStart.psm1
        - scriptName: ADGroupSetup
          scriptFilePath: ad-config-scripts/AD-group-setup.ps1
        - scriptName: ADUserSetup
          scriptFilePath: ad-config-scripts/AD-user-setup.ps1
        - scriptName: ADUserGroupSetup
          scriptFilePath: ad-config-scripts/AD-user-group-setup.ps1
        - scriptName: ADGroupGrantPermissionsSetup
          scriptFilePath: ad-config-scripts/AD-group-grant-permissions-setup.ps1
        - scriptName: ADConnectorPermissionsSetup
          scriptFilePath: ad-config-scripts/AD-connector-permissions-setup.ps1
        - scriptName: ConfigurePasswordPolicy
          scriptFilePath: ad-config-scripts/Configure-password-policy.ps1

We need your help to fix the issue , as we don't want the ActiveDirectoryConfigurationInstance to change .
The current version used is v1.5.1, but it also happen in v1.6.3

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by bo1984** [comment]
Hi @ateguia2019, thank you for using the Landing Zone Accelerator on AWS (LZA) solution. With the LZA solution, we allow you to specify the image ID that you can use for the configuration instance. From the CloudFormation [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#cfn-ec2-instance-imageid) for the EC2 instance, any change to the AMI ID will result in a replacement of the instance. The way around this moving forward would be:

1. Make a snapshot of the managed AMI that you're using
2. Make an SSM Parameter store reference for the AMI ID in that region
3. Update the **imagePath** property with the new image ID

There are caveats as you'd have to manage the lifecycle of the instance whereas with the Amazon AMIs, we manage that and do a set cadence on releases. As it relates to this issue, it looks like there was an issue where the cfn-signal was not sent to CloudFormation which indicates a failure with one of the scripts during the bootstrap phase. You should be able to enable termination protection on the instance and RDP into it so CloudFormation doesn't delete the instance. From there, you can determine which scripts are failing.

**Comment by ateguia2019** [comment]
hi @bo1984 ,
Thanks for the tip. I created a custom ssm parameter with the ami-id and it worked

**Comment by bo1984** [comment]
Thank you for confirming, @ateguia2019. I'm glad everything is working and I'll close this issue out.

**Comment by ateguia2019** [comment]
hi @bo1984 , 
Possible for you check also my issue #463 ?

Thanks and regards
