### ISSUE TITLE
What is the correct process of enabling a new  region 

### ISSUE THREAD

**Issue by ateguia2019** [awslabs/landing-zone-accelerator-on-aws#463]
Hi, 
Anyone can help on how to activate a new region (ca-west-1) in global-config.yaml ?

My LZA in running version v1.6.4
I have added this line in global-config.yaml:

enabledRegions:
  - "ca-west-1"
  
And i got the following error :
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/56047638/16226ce2-676b-49da-9ed9-b5ac33e68c38)

I don't have a replacements-config.yaml file 

Please , any suggestion on how to achieve this ?

**Comment by bhkhatri221** [comment]
Hello @ateguia2019, thank you for filing an issue with the Landing Zone Accelerator team!

This is the result of ca-west-1 not yet existing as a valid region within the LZA source code. Ca-west-1 will be included in the next release of the LZA. We are tracking this in a separate issue here: [#430] (https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/430).

Closing this issue as regional support is tracked in the linked ticket, please feel free to follow up if you have any outstanding questions and thank you again for supporting the Landing Zone Accelerator.

**Comment by n3mawashi** [comment]
Can we reopen this request and get guidance on adding a new region that is supported? Simply adding code doesn't seem to resolve updating Control Tower with the new configuration across all accounts. Does this need to be done manually? If so, when is best?
