### ISSUE TITLE
LZA AWSAccelerator-PrepareStack-xxx cloudformation fails

### ISSUE THREAD

**Issue by phani-achanta** [awslabs/landing-zone-accelerator-on-aws#47]
**Describe the bug**
Running the code pipeline after changes to config repository results in the AWSAccelerator-PrepareStack cloudformation template

**To Reproduce**
Rerunning cloudformation results in failure always

**Please complete the following information about the solution:**
- [ 1.3.0] Version: 
(SO0199-prepare) Landing Zone Accelerator on AWS. Version 1.3.0.

- [us-west-2 ] Region: [e.g. us-east-1]
- [N] Was the solution modified from the version published on this repository?
- [Y] Were there any errors in the CloudWatch Logs?

**Details**

The following resource(s) failed to create: [LoadAcceleratorConfigTable8F9D29D6]. Rollback requested by user.
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: You don't have permissions to access this resource.

**Comment by hickeydh-aws** [comment]
Hello @phani-achanta Thank you for submitting this bug request. Did this happen during an upgrade from a previous version of the accelerator to v1.3?  If so was the installer stack updated as well? Some user have reported similar errors when upgrading to version 1.3 who did not update the installer stack.

**Comment by phani-achanta** [comment]
@hickeydh-aws this is a fresh install of accelerator including the installer

**Comment by rboboc111** [comment]
Hi! At that step of the pipeline a custom resource is executed which is creating a "state" of your organization in DynamoDB. Could you please provide the execution log of that custom resource? Also, do you have any SCPs applied to your management account? A possible explanation might be that the role assumed by that custom resource to be blocked by an explicit deny in a SCP. If that's the case, you can try to whitelist that role with a condition in the deny statement. I hope it will help.

**Comment by hickeydh-aws** [comment]
Hello @phani-achanta Is it possible to review the CloudTrail logs to find which resource is denying access?

**Comment by phani-achanta** [comment]
There is only one error in the cloud trail logs : this is in the management account and claims to have not found the loggroup even though it has already been created.

` "eventTime": "2023-01-25T22:12:14Z",
    "eventSource": "logs.amazonaws.com",
    "eventName": "CreateLogStream",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "35.86.239.64",
    "userAgent": "awslambda-worker/1.0 rusoto/0.48.0 rust/1.65.0 linux",
    "errorCode": "ResourceNotFoundException",
    "errorMessage": "The specified log group does not exist.",
    "requestParameters": {
        "logGroupName": "/aws/lambda/AWSAccelerator-PrepareSta-CustomLoadAcceleratorCon-0JHruGNeLCTl",
        "logStreamName": "2023/01/25/[$LATEST]68cd4aeb9ea84ccca7069e886889f338"
    },`

**Comment by hickeydh-aws** [comment]
Hello again @phani-achanta. Thanks for providing that information. Can you provide all the parameters of the installer stack with confidential information scrubbed? That may help us identify the problem.

**Comment by josh-romme** [comment]
We were able to get farther along in the deployment but have now run into an obscure error message.  We added in the AWS Best Practices and Elections config files with appropriate edits to the config files.  When running the pipeline during the Bootstrap it fails with the logging stack.  

debug:      [logging-stack] Logging stack started for account XXXXXXXXXXXXX and region us-east-1
debug:      [Logging-stack] Create S3 Key
error:  undefined
error:  undefined
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by atfurman** [comment]
> 

I am running into this exact same error in us-east-1. Previously a build had succeeded, but now that I am attempting to define `logging` settings beyond the bare minimum:
```
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: false
    excludeRegions: []
    excludeAccounts: []
``` 

I am encountering the following error during `Build`: 

```
[2023-02-09 16:04:49] - info:       [security-audit-stack] Create SNS Topics and Subscriptions
[2023-02-09 16:04:49] - info:       [security-audit-stack] Completed stack synthesis
[2023-02-09 16:04:49] - info:       [accelerator-bootstrap] Creating bucket for region us-east-1 in account 111122223333
[2023-02-09 16:04:49] - debug:      [logging-stack] Logging stack started for account 111122223333 and region us-east-1
[2023-02-09 16:04:49] - debug:      [Logging-stack] Create S3 Key
[2023-02-09 16:04:49] - error:  undefined
[2023-02-09 16:04:49] - error:  undefined
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Container] 2023/02/09 16:04:49 Command did not exit successfully if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi exit status 1
[Container] 2023/02/09 16:04:49 Phase complete: BUILD State: FAILED
[Container] 2023/02/09 16:04:49 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ -z "${ACCELERATOR_STAGE}" ]; then yarn run ts-node --transpile-only cdk.ts synth --require-approval never --config-dir $CODEBUILD_SRC_DIR_Config --partition aws; fi. Reason: exit status 1
```

**Comment by hickeydh-aws** [comment]
Hello @atfurman thanks for providing additional context. The errors you are seeing are related to the LZA detecting an invalid configuration. Can you please take a look at the [AWS Best Practice configuration](https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/reference/sample-configurations/aws-best-practices) and the [typedoc](https://awslabs.github.io/landing-zone-accelerator-on-aws/modules/_aws_accelerator_config.html) to check the config?

Also, our team is aware that the error messages related to configuration are not helpful, and we have a fix slated for the upcoming release to address the issue.

**Comment by johnraws** [comment]
Hello @atfurman this thread has been closed due to no response received regarding the configuration checks. Please feel free to provide a response and reopen if the issue still persists and we can further investigate.
