### ISSUE TITLE
Not all v1.3.0 IamConfig class properties are listed in README

### ISSUE THREAD

**Issue by m-j-gardner** [awslabs/landing-zone-accelerator-on-aws#48]
This is a documentation issue but couldn't figure out how to change the label.
There seem to have been a few changes in v1.3.0 to the IamConfig class that aren't represented in the README, namely the identityCenter and managedActiveDirectories properties which aren't listed in the IAM Configuration table.

**Comment by awsclemj** [comment]
@m-j-gardner Thanks for the report! We'll have these added in our next minor release.

**Comment by erwaxler** [comment]
Hi @m-j-gardner, this has been resolved with the release of version 1.3.2 so I'll be closing this issue.
