### ISSUE TITLE
Referring dynamic IP ranges allocated by IPAM to VPCs in the route tables

### ISSUE THREAD

**Issue by vforvarun** [awslabs/landing-zone-accelerator-on-aws#481]
**Describe the bug**
We are using IPAM to allocate IP ranges to VPC. While defining Transit Gateway Route tables, I need to provide the Workload accounts's IP address range as "destinationCidrBlock" which is not readily known because it is dynamically allocated by IPAM.

We can use known IP Address Ranges directly in route tables, but I can't seem to find a way in the documentation to refer dynamic IP ranges allocated by IPAM to VPCs in the route tables be it Transit Gateway or any other route tables.

**To Reproduce**
Define a Route table and try to add a destinationCidrBlock which is dynamically allocated by IPAM.

**Expected behavior**
Should be able to refer the IP Address range dynamically allocated by IPAM in route tables.

**Please complete the following information about the solution:**

- [ ] Version: v1.6.2
- [ ] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? N
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
N/A

**Additional context**
N/A

**Comment by erwaxler** [comment]
Hi @vforvarun , thanks for reaching out to the Landing Zone Accelerator team. 

The functionality you are describing is not currently supported in the LZA, though you should be able to solve this problem using native Transit Gateway functionality.

When creating the attachment between the VPC and TGW, you can utilize [route propagation](https://docs.aws.amazon.com/vpc/latest/tgw/how-transit-gateways-work.html#tgw-route-propagation-overview) to automatically add the CIDR of the VPC as a new route to Transit Gateway route table(s).

This can be accomplished in the LZA config one of two ways:
1. Set [defaultRouteTablePropagation](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/v1.6.0/classes/_aws_accelerator_config.TransitGatewayConfig.html#defaultRouteTablePropagation) to `enable` - this will automatically create propagated routes for new VPC attachments created on the Transit Gateway.
2. Specify specific route tables to propagate the route to on the [transitGatewayAttachment](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/v1.6.0/classes/_aws_accelerator_config.TransitGatewayAttachmentConfig.html) configuration property of the VPC.
