### ISSUE TITLE
LZA Patch for GovCloud Feature Request

### ISSUE THREAD

**Issue by jacido** [awslabs/landing-zone-accelerator-on-aws#483]
**Is your feature request related to a problem? Please describe.**

Use cases have been reported where the install stack/pipeline updated and ran fine, but the LZA is failing on the prepare stage.

**Describe the feature you'd like**

LZA Team confirmed that they have been able to replicate this issue and have developed a fix. They are currently working on releasing a patch.

Creating this Github Issue ticket to track its release and for updates. 

**Additional context**

**Comment by bo1984** [comment]
Hello,

Thank you for opening up this issue. Can you please be more descriptive of what you're opening this feature request for?
