### ISSUE TITLE
Default VPCs no deleted in GovCloud

### ISSUE THREAD

**Issue by jperezpatino** [awslabs/landing-zone-accelerator-on-aws#484]
**Describe the bug**
Default VPCs no deleted in GovCloud even though delete property is set to true for defaultVpc configuration in network-config.yaml .

**To Reproduce**
In network-config.yaml file, add the following configuration:
defaultVpc:
  delete: true
  excludeAccounts: []

**Expected behavior**
Default VPCs that are not in used should be deleted.  It work in Commercial Partition.

**Please complete the following information about the solution:**

- [ ] Version: 1.6.2
- [ ] Region: us-gov-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? NA
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
Configuration file:
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/123606745/7b98f941-e506-4ed2-af16-bcdec7fe1c3c)

Default VPC:
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/123606745/71f3e02e-230d-4a91-8d72-87221de4d394)

**Additional context**
NA

**Comment by bo1984** [comment]
Hi @jperezpatino!

Thank you for contacting us and using the Landing Zone Accelerator on AWS (LZA) solution. In the account in question, can you got to the Lambda function `AWSAccelerator-NetworkVpc-CustomDeleteDefaultVpcCu-` and provide any errors or events from the CloudWatch logs?
