### ISSUE TITLE
GovCloud Upgrade issue v1.7.1 from v.1.6.2

### ISSUE THREAD

**Issue by MarkCondry** [awslabs/landing-zone-accelerator-on-aws#486]
**Is your feature request related to a problem? Please describe.**
Documentation: reference/sample-configurations/lza-sample-config-govcloud-us/commercial-config/global-config.yaml

**Describe the feature you'd like**
Please update: reference/sample-configurations/lza-sample-config-govcloud-us/commercial-config/global-config.yaml
with 
**cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true**

**Additional context**
During first attempt to upgrade to v1.7.1 from v.1.6.2 I got this error: Cannot specify values for both cdkOptions and centralizeCdkBuckets. Please delete centralizeCdkBuckets and use cdkOptions

I did not see any instructions to make this change prior to attempting to perform the upgrade. (this might be my problem for not looking in the right place)

When I checked the: [reference/sample-configurations/lza-sample-config-govcloud-us/commercial-config/global-config.yaml](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config-govcloud-us/commercial-config/global-config.yaml)
It still showed:
**centralizeCdkBuckets:
  enable: true**

But when I checked: [reference/sample-configurations/lza-sample-config-govcloud-us/govcloud-us-config/global-config.yaml](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config-govcloud-us/govcloud-us-config/global-config.yaml)
centralizeCdkBuckets had been replaced with:
**cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true**

I have updated the global-config.yaml file and re-running the upgrade

**Comment by bhkhatri221** [comment]
Hello @MarkCondry !  thank you for filing an issue with the Landing Zone Accelerator team! I have been able to replicate this behavior in an internal environment. I have created an issue for our team, and I will update this thread once I have an update on the team's progress.

Thank you for your interest in the Landing Zone Accelerator!

**Comment by erwaxler** [comment]
Hi @MarkCondry , this update to the sample-configurations was added in the [v1.8.1 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.8.1) so I'll go ahead and close this. Thanks again for your support of the LZA!
