### ISSUE TITLE
Duplicate emails error on validate-config

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#49]
**Describe the bug**
i am getting an error when validaing my config doing  yarn validate-config $CODEBUILD_SRC_DIR_Config

[config-validator] Error: accounts-config.yaml has 1 issues: Duplicate emails defined [cloud-resources@myemail.com,cloud-resources+log@myemail.com,cloud-resources+audit@myemail.com,cloud-resources+nwk@myemail.com,cloud-resources+nwkdev@myemail.com,cloud-resources+nwkprd@myemail.com,cloud-resources+epicnonprd@myemail.com,cloud-resources+epicnonprd@myemail.com,cloud-resources+shrdsvc@myemail.com]. in accounts-config.yaml config file

i assume its becuase i am using plus emails i have added them to the yaml with and without single quotes and still getting error

is there a work around 

- [ ] Version: 1.3.0

 - name: Epic-Prod
    description: The Epic prod account
    email: 'cloud-resources+epicnonprd@myemail.com'
    organizationalUnit: HIS/HIS-Prod  
  - name: Ohitdemo-Shared-SVC
    description: The Shared Service account
    email: 'cloud-resources+shrdsvc@myemail.com'
    organizationalUnit: Infrastructure

**Comment by hickeydh-aws** [comment]
Hello @frankscalzo. From the list of the emails provided, it looks like like there is two `cloud-resources+epicnonprd@myemail.com
cloud-resources+epicnonprd@myemail.com` emails. Can you double check the config file to make sure there isn't any duplicates?

**Comment by frankscalzo** [comment]
thanks for the quick response i guess between seeing the entire list of email i was figuring it was calling them all out and my eye being tired from staring at this for the last 13 hours i missed that

**Comment by hickeydh-aws** [comment]
No problem!
