### ISSUE TITLE
Logging stack fails upgrade from 1.4.3 to 1.7.1

### ISSUE THREAD

**Issue by Chandramouli15** [awslabs/landing-zone-accelerator-on-aws#494]
Hi Guys, 

trying to upgrade the lz from 1.4.3 to 1.7.0 version. Getting  error " log group already exist" in log archive account, so manually deleted the log group but getting same error. As per the issue closing note of " issue 471" bug fixed in 1.7.1 lz version , but getting same error in 1.7.1 version also. Please check and update. Thanks

Cloud formation stack region - eu-west-1

Stack Name - AWSAccelerator-LoggingStack-xxxxxxxxxxx-eu-west-1

Refer Issues - 471

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/32807548/42f65fa5-0bfd-401d-bcd9-8119cf9702ed)

**Comment by erwaxler** [comment]
Hi @Chandramouli15 , thanks for reaching out to the Landing Zone Accelerator team. I've been able to replicate this behavior, the team is currently working on a fix to be made available in our next release. I'll keep this issue open until the release has been published.

**Comment by johnraws** [comment]
Closing this issue as it is resolved in [release/v1.8.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.8.0)
