### ISSUE TITLE
LZA creates some KMS keys with key rotation disabled

### ISSUE THREAD

**Issue by Thomas-McKanna** [awslabs/landing-zone-accelerator-on-aws#495]
**Describe the bug**

Some LZA created KMS keys have automatic key rotation disabled. My LZA configuration was first deployed in June 2023, so perhaps these are remnants of old resources that were never properly destroyed, but I'm unsure. When I look in KMS for one of my accounts I see keys like this:

<img width="1383" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22783091/b3234cd4-80d5-4f5b-95de-5820505f6e29">

It seems there are two keys for each service: default, backup, cloudwatch, lambda, s3, sns. But only one key in each pair has an alias. Clicking into one of the keys without an alias, I see:

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22783091/6b9b31b4-b807-4ee8-9a76-812bec149cad)

The lack of automatic key rotation is causing SecurityHub findings for KMS.4 (AWS KMS key rotation should be enabled).

**To Reproduce**
Unclear how to reproduce.

**Expected behavior**
No KMS keys with automatic rotation disabled.

**Please complete the following information about the solution:**

- [x] Version: v1.6.0
- [x] Region: us-east-1 and us-east-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? No

**Comment by bo1984** [comment]
Hi Thomas!

Thank you for contacting us and utilizing the Landing Zone Accelerator on AWS (LZA) solution. Looking at the issue, we set the rotation to be `enabled` on all KMS keys that LZA utilizes for resources like S3, Lambda, CloudWatch, SNS, etc.. Here's a [link](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/11a38bd38aa931a75121a81f50e222ccec6f4202/source/packages/%40aws-accelerator/accelerator/lib/stacks/logging-stack.ts#L708) to the stack where we create the S3 KMS Key (based on the example snapshot you provided) and have it enabled. 

As it relates to the duplicate KMS keys that you see for each service, this is standard when automatic rotation is enabled. KMS will not delete the KMS keys and will reference the previous KMS key material for crypto operations as described in our [documentation](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html). 

In terms of the previous (those that don't have an alias and in your case, the first version of your) keys, the KMS service will not disable automatic rotation on the previous version of the key. I'd check CloudTrail to see if there are any `PutKeyPolicy` and `DisableKeyRotation` API calls that match up with the times where these KMS keys fell out of compliance in Security Hub and AWS Config.

**Comment by Thomas-McKanna** [comment]
Thank you @bo1984! I will investigate CloudTrail tomorrow and see if I can find these events. Perhaps it was some sort of one off mistake for rotation to be disabled. I suspect there is no real risk to enabling rotation on these keys, which I'll likely end up doing.

**Comment by bo1984** [comment]
Yes, this shouldn't cause issues if you re-enable rotation on those respective KMS keys.

**Comment by Thomas-McKanna** [comment]
I'm going to close this issue since I have no way to reproduce the problem. I don't suspect key rotation was disabled by anyone in my organization, since we have this problem in many accounts. But enabling the key rotation manually should fix the issue.
