### ISSUE TITLE
Broken Links in TypeDocs

### ISSUE THREAD

**Issue by justincoker-1159** [awslabs/landing-zone-accelerator-on-aws#499]
It appears all links under Base Configuration and Service / Feature Configuration in the TypeDocs lead to broken links. It appears to affect all versions.

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/169479831/9717812f-3624-41f7-9f34-acc8c32e6894)

**Comment by bo1984** [comment]
Hi Justin!

Thank you for reaching out and using the Landing Zone Accelerator on AWS (LZA) solution. In one of our releases, we switched over our documentation where the new URL can be found [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/user-guide/config/). In terms of the IAM Config page you're looking for, that would be found [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.IamConfig.html).
