### ISSUE TITLE
Ignore OUs and or Accounts for Brownfield install 

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#50]
Trying to find documentation on integrating with a brown field ENV I have a few accounts and OU/s i want to keep out of this while we implement and even if i have them un managed in control tower i seem to keep getting errors on deploy unless i associate them 

- [ ] Version: v1.3.0

**Comment by crissupb** [comment]
So the LZA expects all of the OU's to be in the configuration file.  An OU can have the ignore property set in the organization-config and all of the accounts in the OU will be ignored.  Just be aware that the LZA may make changes to Organization level resources that could have an impact on the accounts in the ignored OU's.  If an account is not in an ignored OU it will need to be added to the accounts-config and you would have to use deployment targets on resources to exclude the account(s).

**Comment by frankscalzo** [comment]
thanks for the clarification so not to keep bothering with questions on this is there documentation that refers to some of this i am not new to AWS but new to this deployment style i have tradtioanly deployed everything  with Terraform 

things i am trying to accomplish and running into road blocks is 
automatic deployment of VPC per new account based on Tagging  and IPAM
SSO integration with automatic groups association per account and OU I have groups that i want to be part of every account and i have project specific  groups that need to be to specific account
just to name a few.

really want to use this to deploy a new client in the healthcare space and showcase how it works and its awesomeness

**Comment by firegrass** [comment]
@frankscalzo I think you want your config to look like this. The property to use in the config file is `ignore`.

```yaml
organizationalUnits:
  - name: HIS/HIS-Non-Prod
  - name: HIS/HIS-Prod
    ignore: true
```

**Comment by frankscalzo** [comment]
worked perfect thanks
