### ISSUE TITLE
v1.8.0 Diff stage error "find: ‘./cdk.out’: No such file or directory"

### ISSUE THREAD

**Issue by nagmesh** [awslabs/landing-zone-accelerator-on-aws#501]
**Describe the bug**

When upgrading pipeline to v1.8.0, Diff stage fails with error 
```
$ /codebuild/output/src843/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts --require-approval never diff --config-dir /codebuild/output/src843/src/s3/01 --partition aws --app cdk.out --stage bootstrap
2024-06-29 01:00:54.484 | info | replacements-config | Loading replacements config substitution values
2024-06-29 01:00:54.592 | info | replacements-config | Loading replacements config substitution values
Done in 2.02s.
find: ‘./cdk.out’: No such file or directory
```

**To Reproduce**
Steps to reproduce the behavior.
Run new or upgrade existing LZA to v1.8.0 with Manual Approval. 

**Expected behavior**
Diff should pass and behave as it did in prior versions

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.5.1] v1.8.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [e.g. us-east-1] any region
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes as per message above

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

LZA is not running synth on these stages. Previously, synth was done which populated cdk.out directory. Then diff ran on that directory to produce content which was streamed from `find` command. Synth needs to run before diff. 

Removing manual approval by setting `Enable Approval Stage` to `No` in installer stack will work as a temporary measure.

**Comment by amitsmlaws** [comment]
Please upgrade to 1.8.1. This has been fixed in 1.8.1. Alternatively you can try to disable the manual Approval stage.
