### ISSUE TITLE
Build version failing if not using the latest version

### ISSUE THREAD

**Issue by alexhaycock** [awslabs/landing-zone-accelerator-on-aws#504]
**Describe the bug**
Build stage failing because we are running v1.7.1 with the following error

```
[Container] 2024/07/01 10:33:08.069367 Running command if [ "$ACCELERATOR_CHECK_VERSION" = "yes" ]; then 
                if [ "$PACKAGE_VERSION" != "$ACCELERATOR_PIPELINE_VERSION" ]; then
                  echo "ERROR: Accelerator package version in Source does not match currently installed LZA version. Please ensure that the Installer stack has been updated prior to updating the Source code in CodePipeline."
                  exit 1
                fi
              fi
``` 

It seems to be that if we are not using the version specified in the following file that we can't get past this stage. https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/13f3ebc58a162c90525ea81f69778f695e4c3cdb/source/package.json

**To Reproduce**
Run the pipeline while LZA is sat at version 1.7.1. 

We have upgraded to 1.8.0 which fixes this issue but now hit another CDK error https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/501

**Expected behavior**
Pipeline should progress through to the next stage.

**Please complete the following information about the solution:**

- [x] Version: v.1.7.1
- [x] Region: eu-west-2
- [x] Was the solution modified from the version published on this repository? No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? No service quota issues.
- [x] Were there any errors in the CloudWatch Logs? Error posted above. 

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by amitsmlaws** [comment]
Not the actual error. It's just a debug statement

**Comment by alexhaycock** [comment]
@amitsmlaws as we have upgraded all of our LZA's I can't dig in to what the actual error will be now. I will close this and raise a new one if it happens the next time a new version comes out.
