### ISSUE TITLE
The baseline 'AWSControlTowerBaseline' cannot be enabled on the Security OU*

### ISSUE THREAD

**Issue by cloudgury** [awslabs/landing-zone-accelerator-on-aws#512]
**Describe the bug**
New deployment of LZA to the existing Control Tower the pipeline "AWSAccelerator-Pipeline" fail with the following error message  
**The baseline 'AWSControlTowerBaseline' cannot be enabled on the Security OU**

**To Reproduce**
New deployment of LZA, the Control Tower is deployed .

**Expected behavior**
The pipeline execution complete successfully, in this case the OU already exist and has baseline 

**Please complete the following information about the solution:**

- [ X] Version: [e.g. v1.8.1]

- [ X] Region: [e.g. us-east-1]
- [x] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
Please migrate your code to use AWS SDK for JavaScript (v3).
--
151 | For more information, check the migration guide at https://a.co/7PzMCcy
152 | (Use `node --trace-warnings ...` to show where the warning was created)
153 | 2024-07-19 11:45:51.925 \| info \| index \| The organization unit "Security" already exists in AWS Organizations, create organizational operation skipped.
154 | 2024-07-19 11:45:52.212 \| info \| index \| The organizational unit "Security" is not registered into AWS Control Tower, it will be registered now.
155 | 2024-07-19 11:45:53.617 \| info \| index \| Enabling baseline for "Organizational Unit "Security" with id "<OU-ID>" for parent "Root". Baseline version is "4.0" and baseline identifier is "arn:aws:controltower:us-east-1::baseline/<BASELINE-ID>".
156 | 2024-07-19 11:45:53.767 \| error \| runner \| The baseline 'AWSControlTowerBaseline' cannot be enabled on the Security OU.
157 | ValidationException: The baseline 'AWSControlTowerBaseline' cannot be enabled on the Security OU.
158 | at de_ValidationExceptionRes (/codebuild/output/src969/src/s3/00/source/node_modules/@aws-sdk/client-controltower/dist-cjs/index.js:1298:21)
159 | at de_CommandError (/codebuild/output/src969/src/s3/00/source/node_modules/@aws-sdk/client-controltower/dist-cjs/index.js:1192:19)
160 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
161 | at async /codebuild/output/src969/src/s3/00/source/node_modules/@aws-sdk/client-controltower/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
162 | at async /codebuild/output/src969/src/s3/00/source/node_modules/@smithy/core/dist-cjs/index.js:165:18
163 | at async /codebuild/output/src969/src/s3/00/source/node_modules/@aws-sdk/client-controltower/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
164 | at async /codebuild/output/src969/src/s3/00/source/node_modules/@aws-sdk/client-controltower/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22 {
165 | '$fault': 'client',
166 | '$metadata': {
167 | httpStatusCode: 400,
168 | requestId: '65320bf6-7ba1-485e-b8a6-030877d90658',
169 | extendedRequestId: undefined,
170 | cfId: undefined,
171 | attempts: 1,
172 | totalRetryDelay: 0
173 | },
174 | level: 'error',
175 | mainLabel: 'accelerator',
176 | [Symbol(level)]: 'error'
177 | }
178 | error Command failed with exit code 1.
179 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by devnuII** [comment]
We hit the same bug during the upgrade from v1.6.4 to v1.8.0/v1.8.1

**Comment by cloudgury** [comment]
Thank you for your prompt response. Could you please advise on how I can resolve this error and what steps I should take next? Additionally, I would like to update the baseline already set on the child’s accounts Audit and Log Archive to the latest version 4, and LZA try to apply it to the Security OU and  this step is failing. Thanks

**Comment by bhkhatri221** [comment]
Hello @cloudgury, thank you for filing an issue with the Landing Zone Accelerator team!  

To ensure we have all relevant details for this issue, could you please confirm if the Organizational Unit (OU) registered with ControlTower has ever been manually renamed?

Thanks, and we look forward to hearing back from you!

**Comment by cloudgury** [comment]
Yes, the OU was renamed because it originally only had an AWS Organization installed in the accounts, which already had a Security OU and a security account. Before installing Control Tower, I  had to rename the old OU.
Please let me know if you need any more information.

**Comment by bhkhatri221** [comment]
Thank you @cloudgury for validating renaming OU registered with Control Tower.  

If an OU registered with ControlTower is manually renamed, the ControlTower console displays the updated OU name, but the ControlTower GetLandingZone API shows the old OU name. Due to this issue, LZA attempts to enable baseline for the given OU, which causes pipeline to fail with "The baseline 'AWSControlTowerBaseline' cannot be enabled on the Security OU." 

As a workaround,  you have the following workaround options:
- You can rename the OU back to its previous name. However, if this is not possible, proceed to the next option.
- You can add the ACCELERATOR_NO_ORG_MODULE environment value to the "AWSAccelerator-ToolkitProject" CodeBuild project with the value set to "Yes". If this environment variable is set, LZA will skip OU baseline API calls. This feature is available in LZA v1.8.0 or later. **Please note**: When the ACCELERATOR_NO_ORG_MODULE environment variable parameter is set to "Yes", LZA will not register OUs with the Control Tower APIs. Therefore, you will need to manually manage OU registration.

Let us know if this workaround works for you and if you have any further questions.

**Comment by devnuII** [comment]
I can confirm that chaging the name of the Security OU fixed the problem in our case, and the upgrade completed just fine.

**Comment by cloudgury** [comment]
Yes, changing the Organizational Unit (OU) allowed the pipeline to pass the error message. However, I have a few questions:

1. Will the "**ControlTower GetLandingZone API**" return the old OU even after the OU has been changed?

2 .If the existing accounts are added to a**ccounts-config.yaml**, which is used to manage all of the AWS accounts within the AWS Organization, and the account already exists in the organization, will it be ignored or will the account creation process be triggered again?

3. Is networking a mandatory implementation requirement for the Landing Zone Accelerator (LZA) if I do not want to use the networking module I see it is a stage in the pipeline.
 Thank you in advance

**Comment by bhkhatri221** [comment]
Hello @cloudgury , Thank you validating that the pipeline passed the above error message. 

1. In certain situations, the 'ControlTower GetLandingZone API' may return the previous Organizational Unit (OU) even after it has been modified. To verify the values, use the [get-landing-zone](https://docs.aws.amazon.com/cli/latest/reference/controltower/get-landing-zone.html#get-landing-zone) command.

2. The new account creation process will not happen. You can find the documentation for Adding existing account in the [Performing administrator tasks](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/performing-administrator-tasks.html).

3. No, networking is not a mandatory implementation requirement for the Landing Zone Accelerator (LZA) if you do not want to use the networking module. The LZA allows you to choose whether or not to deploy networking resources. You can find more information about all stages in the [core pipeline document](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/awsaccelerator-pipeline.html).

I hope this was helpful! I will be closing this issue, but please feel free to follow-up or open new issues as you have additional questions. Thank you for your interest in Landing Zone Accelerator!
