### ISSUE TITLE
Account enrollment failed - Received response status [FAILED] from custom resource.

### ISSUE THREAD

**Issue by deloitte-lza-test** [awslabs/landing-zone-accelerator-on-aws#52]
**Describe the bug**
at the prepare stage, the AWSAccelerator-PrepareStack failed, entering UPDATE_ROLLBACK_FAILED state with below error;

"The following resource(s) failed to update: [CreateCTAccounts3049A752]."

**To Reproduce**
Run LZA with 7 workload accounts?

**Expected behavior**
Enrollment for all accounts successful. Only one here has failed

**Please complete the following information about the solution:**

- [ ] Version: v1.3.0

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?: no don't believe so
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: yes
- [ ] Were there any errors in the CloudWatch Logs?: yes;

**From:** Lambda function logs /aws/lambda/AWSAccelerator-PrepareSta-CreateCTAccountsCreateCo-xxx

{
    "errorType": "Error",
    "errorMessage": "Account creation failed. Error: Accounts failed to enroll in Control Tower. Check Service Catalog Console",
    "stack": [
        "Error: Account creation failed. Error: Accounts failed to enroll in Control Tower. Check Service Catalog Console",
        "    at Runtime.kr [as handler] (/var/task/index.js:1:19159)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}

**From:** CFN

**Screenshots**
![image](https://user-images.githubusercontent.com/123182127/216363389-db964083-e15b-4287-9483-1ec680524055.png)

**Additional context**
6 of the 7 workload accounts deployed just fine. This one is deployed in the same OU as 2 others, no apparent different configuration in accounts

**Comment by nagmesh** [comment]
Under the hood accounts are added serially and baselined in Control Tower. Only when account is completed the next one is added. 
If more than 3 accounts are added and there are many baselines to cover the above issue may occur. 
Can you retry Prepare stage via CodePipeline? Account creation is usually decoupled and the solution can pick up where it left off to continue deployment.

**Comment by nagmesh** [comment]
There is a new [feature](https://aws.amazon.com/about-aws/whats-new/2022/12/aws-control-tower-concurrent-account-provisioning-operations/) in Control Tower that allows parallel account creation. We are researching this at our end and will incorporate it in our future release.

**Comment by johnraws** [comment]
Thank you for your patience as we worked to resolve the issue you encountered. The error received from the Custom Resource caused by long runtime for creating accounts should no longer occur as we now utilize the AWS Control Tower parallel account creation feature implemented in commit https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/0511569cbdcc92ee9e0c5f5b2f85acc13658d6df , allowing up to 5 accounts to be created in parallel.
