### ISSUE TITLE
Uninstaller Template does not remove all resources

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#526]
**Describe the bug**
The [uninstaller](https://catalog.workshops.aws/landing-zone-accelerator/en-US/workshop-advanced/cleanup) from the LZA workshop does not delete all resources 
There are at least these stacks in the management account:
- AWSAccelerator-IdentityCenterStack-XXX-ap-southeast-2
- AWSAccelerator-ResourcePolicyEnforcementStack-XXX-ap-southeast-2

**To Reproduce**
Launch the uninstaller CFN

**Expected behavior**
All stacks should be deleted.

**Please complete the following information about the solution:**

- [x] Version: v1.7.1
- [x] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
No log entries are created in Cloudwatch logs
<img width="2299" alt="image" src="https://github.com/user-attachments/assets/958808c6-8504-4d87-a95b-c0344c5fdf5d">

**Additional context**

**Comment by erwaxler** [comment]
Hi @richardkeit , thanks for raising this issue with the team! This has been incorporated into the code base and will be available in our next major release. Thank you for your support of the Landing Zone Accelerator!

**Comment by richardkeit** [comment]
Appreciate the support @erwaxler and team! 🚀

**Comment by erwaxler** [comment]
Hi @richardkeit, this has been included in v1.11.0 of the Landing Zone Accelerator which was released today.

I will go ahead and close this issue, please reopen the issue if the updated code has not resolved this in your environment. Thanks again for your support of the Landing Zone Accelerator!
