### ISSUE TITLE
Replace CodeCommit with an AWS option for Source Files

### ISSUE THREAD

**Issue by luke-dau** [awslabs/landing-zone-accelerator-on-aws#531]
**Is your feature request related to a problem? Please describe.**
With the deprecation of CodeCommit you have replaced the location of configuration files with S3, however many public sector customers (the primary audience for LZA) also need to have the source files stored on AWS. Are you able to please update LZA to have the option of storing the source files on S3 as well (instead of github or CodeCommit)?

**Describe the feature you'd like**
An option to store source files on S3, or have AWS reinstate CodeCommit because it was an awful decision.

**Additional context**
The community would love to know why this decision was made in the first place, seems like there are lots of people using CodeCommit - especially in the public sector.

**Comment by erwaxler** [comment]
Hi @luke-dau , as of v1.10.0 you can store the source code in an AWS S3 bucket to ensure the source code is stored on AWS. For more information on how to use this feature, please see this page: https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/source-code-location.html

Thank you for your support of the Landing Zone Accelerator!
