### ISSUE TITLE
Accelerator Metadata is writing LZA config as a byte array rather than YAML since v1.9.0

### ISSUE THREAD

**Issue by joeldesaulniers** [awslabs/landing-zone-accelerator-on-aws#536]
**Describe the bug**
After upgrading to v1.9.0, the LZA config is being written to the metadata log archive bucket as a byte array rather than YAML. [Please see this line](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/76117a978937ea8c7a5d1e58e2c3e2b2584ec0ba/source/packages/%40aws-accelerator/constructs/lib/aws-accelerator/get-accelerator-metadata/index.ts#L304) which was introduced in v1.9.0 which may be the culprit.

**To Reproduce**
Upgrade to v1.9.0 and validate that the format of the config files stored in the Log Archive's metadata bucket are now in byte array. Example: 
104,111,109,101,82,101,103,105,111,110,58,32,38,72,79,77,69,95,82,69,71,73,79,78,32,99,97,45,99,101,110,116,114,97,108

**Expected behavior**
The format of the config files stored in the Log Archive's metadata bucket should be in YAML.
Example:
homeRegion: &HOME_REGION ca-central-1
centralSecurityServices:
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
[etc...]

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.5.1]
v1.9.0

**Comment by joeldesaulniers** [comment]
<img width="1146" alt="Screenshot 2024-08-15 at 10 58 45 AM" src="https://github.com/user-attachments/assets/e31363e2-c6fc-4458-a1bd-287374674dbd">

**Comment by erwaxler** [comment]
Hi @joeldesaulniers , thanks for raising this issue. A fix for this was implemented in v1.9.2 of the LZA and is included in all subsequent releases. I'll go ahead and close this issue, please reopen or create a new issue if you continue to have challenges. Thank you for your support of the Landing Zone Accelerator!
