### ISSUE TITLE
Cannot deploy networking stack without vpcFlowLogs in NetworkConfig

### ISSUE THREAD

**Issue by ssakuh** [awslabs/landing-zone-accelerator-on-aws#54]
**Describe the bug**
You cannot synthetize the `network-vpc` stage without `vpcFlowLogs` in `network-config.yaml`.

**To Reproduce**
Try deploying the solution without this option.

**Expected behavior**
The solution should not deploy the flow logs if the option is not configured.

**Please complete the following information about the solution:**

- Version: 1.3.0
- Region: N/A
- Was the solution modified from the version published on this repository? No
- If the answer to the previous question was yes, are the changes available on GitHub? N/A
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- Were there any errors in the CloudWatch Logs? Please see below:
```
[2023-02-03 16:19:05] - info:           [toolkit] Executing cdk synth network-vpc
[2023-02-03 16:19:55] - info:           [app] Begin Accelerator CDK App
[2023-02-03 16:19:55] - error:  undefined
[2023-02-03 16:19:55] - error:  undefined
Subprocess exited with error 1
error Command failed with exit code 1.
```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nagmesh** [comment]
Can you share the network-config.yaml file used in running the pipeline? I did a fresh 1.3 install and removed vpcFlowLogs.

```yaml
defaultVpc:
  delete: false
  excludeAccounts: []
transitGateways: []
endpointPolicies: []
vpcs: []

```

But my config fails validation in build stage
```zsh
[2023-02-14 08:56:28] - info: 		[config-validator] Config source directory -  /redacted/path/to/config
[iam-config-validator.ts]: iam-config.yaml file validation started
[customizations-config-validator.ts]: customizations-config.yaml file validation started
[2023-02-14 08:56:28] - warn: 		[config-validator] Config file validation failed !!!
[2023-02-14 08:56:28] - warn: 		[config-validator] Error: Could not parse content:
* Invalid value undefined supplied to /vpcFlowLogs in iam-config.yaml config file
[2023-02-14 08:56:28] - warn: 		[config-validator] Error: Could not parse content:
* Invalid value undefined supplied to /vpcFlowLogs in network-config.yaml config file
[2023-02-14 08:56:28] - warn: 		[config-validator] Error: Could not parse content:
* Invalid value undefined supplied to /vpcFlowLogs in customizations-config.yaml config file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks.

**Comment by ssakuh** [comment]
I got my error by using ```vpcFlowLogs: {}```. Yes, this key could be entirely optional.

Btw, you might have also spotted another bug, in your output the validation stage threw an error for `vpcFlowLogs` not being present in `customizations-config.yaml` and `iam-config.yaml`, while this parameter should not be in those files anyway.

**Comment by nagmesh** [comment]
Thanks for that. I tried using `vpcFlowLogs: {}` but it still failed validation.
```zsh
[iam-config-validator.ts]: iam-config.yaml file validation started
[customizations-config-validator.ts]: customizations-config.yaml file validation started
[2023-02-15 09:44:08] - warn: 		[config-validator] Config file validation failed !!!
[2023-02-15 09:44:08] - warn: 		[config-validator] Error: Could not parse content:
* Value should be a flow log traffic type at /vpcFlowLogs/trafficType
* Invalid value undefined supplied to /vpcFlowLogs/maxAggregationInterval
* Invalid value undefined supplied to /vpcFlowLogs/destinations
* Invalid value undefined supplied to /vpcFlowLogs/defaultFormat in iam-config.yaml config file
[2023-02-15 09:44:08] - warn: 		[config-validator] Error: Could not parse content:
* Value should be a flow log traffic type at /vpcFlowLogs/trafficType
* Invalid value undefined supplied to /vpcFlowLogs/maxAggregationInterval
* Invalid value undefined supplied to /vpcFlowLogs/destinations
* Invalid value undefined supplied to /vpcFlowLogs/defaultFormat in network-config.yaml config file
[2023-02-15 09:44:08] - warn: 		[config-validator] Error: Could not parse content:
* Value should be a flow log traffic type at /vpcFlowLogs/trafficType
* Invalid value undefined supplied to /vpcFlowLogs/maxAggregationInterval
* Invalid value undefined supplied to /vpcFlowLogs/destinations
* Invalid value undefined supplied to /vpcFlowLogs/defaultFormat in customizations-config.yaml config file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
We can work on making `vpcFlowLogs` optional in network config as there can be use cases where there are no network workloads.

**Comment by awsclemj** [comment]
Hello all,

`vpcFlowLogs` was made optional in [release v1.4.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.4.0). Thank you all for your comments on the issue. I will be marking this as closed.
