### ISSUE TITLE
CodeBuild operational notification 29 August 2024

### ISSUE THREAD

**Issue by LUKEALDRED** [awslabs/landing-zone-accelerator-on-aws#549]
AWS released the following notification:

> Starting on September 4, 2024, AWS CodeBuild will upgrade its fleet of build hosts to use Amazon Linux 2023 (AL2023) from Amazon Linux 2 (AL2) [1]. If your builds rely on AL2 as the underlying operating system, you will need to update your buildspec and any custom images to work with the AL2023. However, if you have already upgraded your buildspec or any custom images you can disregard the rest of this message.
> 
> CodeBuild provides managed container images for AL2023 and contain many of the popular runtimes [2].
> 
> If you have any questions or concerns, please reach out to AWS Support [3].
> 
> [1] https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2.html
> [2] https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html#linux-runtimes
> [3] https://aws.amazon.com/support

Just want to check that this does not affect Landing Zone Accelerator.

**Comment by crissupb** [comment]
LZA uses an Ubuntu image in CodeBuild.  Currently the standard:7.0 image.  This is the latest Ubuntu image available.
