### ISSUE TITLE
Native support to supply a TLS Inspection Configuration ARN to a property of the NfwFirewallPolicyConfig Class NfwFirewallPolicyConfig

### ISSUE THREAD

**Issue by LukaszJD** [awslabs/landing-zone-accelerator-on-aws#551]
**Is your feature request related to a problem? Please describe.**
LZA currently does not natively support the creation of TLS Inspection configuration resource. 
As a work around we deployed it by implementing the customizations-config.yaml file, however we reached another limitation of LZA, when trying to associate the TLS config resource to FW policy.
NfwFirewallPolicyConfig class does not have a property available that allows TLS configuration to associate with firewall policy, unlike that of the AWS::NetworkFirewall::FirewallPolicy resource type available in CloudFormation where it is possible to provide a TLSInspectionConfigurationArn value to the policy.

**Describe the feature you'd like**
Support to supply a TLS Inspection Configuration ARN in the network-config.yaml file, so that TLS Config resource can be associated with the Firewall Policy.

**Comment by bo1984** [comment]
Hi @LukaszJD !

I see that this request is similar to this [issue](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/550). I will close this issue and keep you updated on the aforementioned issue.
