### ISSUE TITLE
bug: Build doesn't detect version correctly

### ISSUE THREAD

**Issue by mbevc1** [awslabs/landing-zone-accelerator-on-aws#557]
**Describe the bug**
During the `Build` stage there is an error in the pipeline output (still returns success at the end, just noisy logs):
```
Container] 2024/08/29 10:41:20.971151 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2024/08/29 10:41:20.971169 Phase context status code:  Message: 
[Container] 2024/08/29 10:41:21.044168 Entering phase INSTALL
[Container] 2024/08/29 10:41:21.082495 Phase complete: INSTALL State: SUCCEEDED
[Container] 2024/08/29 10:41:21.082521 Phase context status code:  Message: 
[Container] 2024/08/29 10:41:21.117424 Entering phase PRE_BUILD
[Container] 2024/08/29 10:41:21.118133 Running command export PACKAGE_VERSION=$(cat source/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[:space:]')
[Container] 2024/08/29 10:41:21.220793 Running command if [ "$ACCELERATOR_CHECK_VERSION" = "yes" ]; then 
                if [ "$PACKAGE_VERSION" != "$ACCELERATOR_PIPELINE_VERSION" ]; then
                  echo "ERROR: Accelerator package version in Source does not match currently installed LZA version. Please ensure that the Installer stack has been updated prior to updating the Source code in CodePipeline."
                  exit 1
                fi
              fi
[Container] 2024/08/29 10:41:21.225403 Phase complete: PRE_BUILD State: SUCCEEDED
...
```

**To Reproduce**
Every time.

**Expected behavior**
Clean logs.

**Please complete the following information about the solution:**

- [x] Version: 1.9.2

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: eu-west-2
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by andy-nyunt** [comment]
I am seeing the same issue upgrading from v1.9.1 to v1.9.2

**Comment by 116davinder** [comment]
I am seeing the same issue, when doing fresh installing of 1.9.2 version.

**Comment by richardkeit** [comment]
Hi @mbevc1 ,

What error are you referring to?

From the above snippet, it says it's running a command which is a conditional echo and then exit with error code 1.

As there doesn't seem to be an echo in the log, the condition isn't hit - so I'm not sure what the error is meant to be?

**Comment by mbevc1** [comment]
@richardkeit oh, it does indeed! My bad misreading this as it's only echoing the command but obviously not returning 1 :smile: .

I'll close the issue, but messaging in the log is a bit misleading :)

**Comment by richardkeit** [comment]
All good @mbevc1 - CodeBuild can be a little noisy in that regard (would be nice to toggle it on and off, purely at presentation layer)
