### ISSUE TITLE
security-config.yaml ${ACCEL_LOOKUP... documentation

### ISSUE THREAD

**Issue by ptyo** [awslabs/landing-zone-accelerator-on-aws#57]
**Is your feature request related to a problem? Please describe.**
I am trying to create some custom Config rules that have auto remediation built in. I see line entries in the file that are leveraging the ${ACCEL_LOOKUP:: .....) but I can find no documentation on how to leverage it.

**Describe the feature you'd like**
I would like to have some documentation available that explains how I can leverage that function.

**Additional context**

Here is the block of code from best practices templates that I am trying to reverse engineer to figure out how the ${ACCEL_LOOKUP...) works:

        - name: accelerator-s3-bucket-server-side-encryption-enabled
          identifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
          complianceResourceTypes:
            - AWS::S3::Bucket
          remediation:
            rolePolicyFile: custom-config-rules/bucket-sse-enabled-remediation-role.json
            automatic: true
            targetId: Put-S3-Encryption
            retryAttemptSeconds: 60
            maximumAutomaticAttempts: 5
            parameters:
              - name: BucketName
                value: RESOURCE_ID
                type: String
              - name: KMSMasterKey
                value: ${ACCEL_LOOKUP::KMS}
                type: StringList

In the above the vlue: ${ACCEL_LOOKUP::KMS} returns the S3 CMK value to encrypt with

Below is the code I created to solve another issue:

        - name: abc-sns-topic-encryption-enabled
          identifier: SNS_ENCRYPTED_KMS
          complianceResourceTypes:
            - AWS::SNS::Topic
          remediation:
            rolePolicyFile: custom-config-rules/abc-config-remediation-encrypt-sns-topic-role.json
            automatic: true
            targetId: abc-config-remediation-encrypt-sns-topic
            retryAttemptSeconds: 60
            maximumAutomaticAttempts: 5
            parameters:
              - name: TopicArn
                value: RESOURCE_ID
                type: String
              - name: KMSMasterKey
                value: ${ACCEL_LOOKUP::KMS}
                type: StringList

The above code works, but it encrypts with the S3 CMK... How do i get ${ACCEL_LOOKUP::KMS} to return the SNS CMK?

**Comment by ptyo** [comment]
Here are the only references that I have found up to this point:
https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.LaunchTemplateConfig

says this:


Valid AMI ID or a reference to ssm parameter store to get AMI ID. If ssm parameter is referenced it should follow the pattern ${ACCEL_LOOKUP::ImageId:/path/to/ssm/parameter/for/ami}

For example to get the latest x86_64 amazon linux 2 ami, the value would be ${ACCEL_LOOKUP::ImageId:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}

**Comment by awsclemj** [comment]
Hello,

We have added a [new section](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-solution-specific-variables.html#accel_lookup-reference-variable) to our Implementation Guide with additional details on the ${ACCEL_LOOKUP} variable. We plan to add additional examples and use cases for these variables in a subsequent release. Thank you for the feedback!
