### ISSUE TITLE
The bootstrap template doesn't handle parameter updates.

### ISSUE THREAD

**Issue by kisst** [awslabs/landing-zone-accelerator-on-aws#574]
**Describe the bug**
The bootstrap template doesn't handle parameter updates.

I provisioned the pipeline with manual approvals as in early stages that made sense, and had the intention to turn it of later, however updating the parameter, did not result in update in the pipline.

**To Reproduce**
Deploy with manual approval, and then update to have no manual approval `EnableApprovalStage` Parameter  

**Expected behavior**
The provisioned pipeline is updated as per the parameter of the template is updated.

**Please complete the following information about the solution:**

- [x] Version: 1.9.2
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? No

**Additional context**
It was a brownfield deployment hence a separated OU holds all legacy accounts, this caused the first execution of the pipeline to fail as there was no option to modify the org config prior to first deployment.

**Comment by erwaxler** [comment]
Hi @kisst thanks for reaching out to the Landing Zone Accelerator team!

You are correct that updating the `AWSAccelerator-InstallerStack` stack in CloudFormation alone will not update the `AWSAccelerator-Pipeline`. You must then run the release a new change to run the `AWSAccelerator-InstallerPipeline` CodePipeline which will make changes to the `AWSAccelerator-Pipeline`.

I encourage you to take a closer look at [this page](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/deployment-pipelines.html) in our documentation which more clearly describes the activities of each pipeline. When updating to a new version, the CloudFormation update triggers the `AWSAccelerator-InstallerPipeline` automatically, but for smaller changes this process requires manual intervention. 

I'll go ahead and close this issue as resolved, please continue to open issues with the team for guidance or clarification.
