### ISSUE TITLE
Closing an account did not remove the dynamoDB table Entry.

### ISSUE THREAD

**Issue by alabkris** [awslabs/landing-zone-accelerator-on-aws#582]
**Describe the bug**
Closing an account did not remove the dynamoDB table.

**To Reproduce**
Procedure used to close an account:
remove from the account Service Catalog product list as defined.
move the account to Suspended OU
issue Close Account command
remove the account from the accounts-config.yaml file.
Run the AWSAccelerator-Pipeline CodePipeline.

**Expected behavior**
DyamoDB still shows the accounts listed under orignal OU

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.9.0]

- [x] Region: [e.g. us-west-2]
- [x] Was the solution modified from the version published on this repository? no
- [x] If the answer to the previous question was yes, are the changes available on GitHub? NA
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? NA
- [x] Were there any errors in the CloudWatch Logs? NA

**Comment by crissupb** [comment]
Thank you for your feedback.  This behavior is intentional. The application uses config commit hashes when retrieving data from the table and will not pull the deleted account from the table when it needs the account records.

**Comment by Athanasii** [comment]
This is working as designed.
