### ISSUE TITLE
JSON parse error in`printStackDiff` leading to malformed diffs

### ISSUE THREAD

**Issue by k7k0** [awslabs/landing-zone-accelerator-on-aws#597]
**Describe the bug**
When running a stack diff, the [printStackDiff function](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/v1.9.2/source/packages/%40aws-accelerator/utils/lib/diff-stack.ts#L50) is doing a `JSON.stringify` of `newTemplate` which is the template path, not the contents. Leading to diffs like this:

```
Stack: AWSAccelerator-NetworkAssociationsGwlbStack-<account>-<region>
Other Changes
[+] Unknown 270: l
[+] Unknown 271: a
[+] Unknown 272: t
[+] Unknown 273: e
[+] Unknown 274: .
[+] Unknown 275: j
[+] Unknown 276: s
[+] Unknown 277: o
[+] Unknown 278: n
[~] Unknown 266: j to t
[~] Unknown 267: s to e
[~] Unknown 268: o to m
[~] Unknown 269: n to 
```
instead it should do `JSON.stringify(readTemplate(newTemplate))` to stringify the file contents and get the correct mangled version.

**To Reproduce**
Synth and diff a stage having `differenceCount` bigger than the number of letters of the <stack>.json path length. 
For example, add a new region and a VPC, then
```
yarn ts-node --transpile-only cdk.ts --require-approval never --partition aws --stage network-associations --config-dir <config- dir> synth
yarn ts-node --transpile-only cdk.ts --require-approval never --partition aws --stage network-associations --config-dir <config-dir> diff
``` 

**Expected behavior**

```
Stack: AWSAccelerator-NetworkAssociationsGwlbStack-<account>-<region>
Template
[+] Description Description: (SO0199-networkgwlb) Landing Zone Accelerator on AWS. Version 1.9.2.

Parameters
[+] Parameter ###
....

Resources
[+] AWS::SSM::Parameter ###
[+] AWS::SSM::Parameter ###
```

**Please complete the following information about the solution:**

- [x] Version: 1.9.2
- [x] Region: any
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [x] Were there any errors in the CloudWatch Logs? N/A

**Comment by richardkeit** [comment]
Smart @k7k0! 

Related issue:
- https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/577

**Comment by k7k0** [comment]
it looks like a [regression introduced while upgrading to CDK 2.148.0](https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/16ec0cc5add8a79c10cb07457cae6b9524e613ab#diff-a799deca78205b2a65ce95d7c6c69e705ba78e2bd1049fc5b6e3d43f7cb66a19). 
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/ed193f3f-93d7-4f88-91a0-2d7af6f6b722">

`readTemplate` should be used for the `fullDiff` on next line as well

**Comment by richardkeit** [comment]
@erwaxler - please mark as closed.
Thanks
