### ISSUE TITLE
CodeCommit -> Other VCS for config files : Migration path for existing installations

### ISSUE THREAD

**Issue by ap-hyperbole** [awslabs/landing-zone-accelerator-on-aws#612]
**Is your feature request related to a problem? Please describe.**
The existing Landing Zone Accelerator (LZA) installation (version 1.8.1) uses the default CodeCommit repository for configuration files. Release notes for LZA version 1.9.0, along with new parameters in the template, suggest there's an option to use an existing configuration repository. This can be done with the UseExistingConfigRepo parameter in the template. However, the parameter description and the release notes both discourage using this option after the initial installation and suggest manual intervention is required.

**Describe the feature you'd like**
Documentation and clear steps on how to migrate existing CodeCommit stored config files  to other VCS (Github, Bitbucket etc..) with the exact steps for manual intervention required and potential impact.

**Comment by mbevc1** [comment]
Same might apply if you want to migrate from S3 to supported GH in v1.10.0

**Comment by richardkeit** [comment]
FYI @ap-hyperbole @mbevc1 
https://aws.amazon.com/blogs/publicsector/moving-from-aws-codecommit-or-amazon-s3-to-external-configuration-repositories-for-landing-zone-accelerator-on-aws/

**Comment by mbevc1** [comment]
Cool, thanks for sharing @richardkeit !

**Comment by ap-hyperbole** [comment]
thanks @richardkeit

**Comment by ap-hyperbole** [comment]
@richardkeit  
<img width="996" alt="Screenshot 2024-12-02 at 18 35 43" src="https://github.com/user-attachments/assets/806f0e45-a2ce-4266-b0e0-7bacfc74c7bd">
I think there is an error in the document. It says "To export from the CodeCommit repository:" and then repeats the instructions for S3 zip download process from the previous section. 

Also, it would be useful to mention the minimum LZA deployment version which supports this migration process. 

Finally, I am presuming this would work with Bitbucket as long as CodeConnection is configured and a link is established with Bitbucket? 

Many thanks!

**Comment by richardkeit** [comment]
Hi @ap-hyperbole ,

Fair enough - moving to another source code repository, personally I would do the following from the existing codecommit:
1. Create New Repo (in Bitbucket sounds like in your use case)
1. From the local version of the repo:
~~~bash
git remote add bitbucket <bitbucket_url>
git push bitbucket main
~~~

Based on the new installer files, yeh if CodeStar connection to Bitbucket is established, populate it in this parameter for the InstallerStack:
~~~json
    "ConfigCodeConnectionArn": {
      "Type": "String",
      "Default": "",
      "Description": "The ARN of an AWS CodeConnection referencing your existing LZA configuration repository. To use this parameter, useExistingConfigRepo must be set to Yes and ConfigurationRepositoryLocation must be set to codeconnection."
    },
~~~
