### ISSUE TITLE
Add support to create IAM user without login credentials

### ISSUE THREAD

**Issue by senyberg** [awslabs/landing-zone-accelerator-on-aws#615]
**Is your feature request related to a problem? Please describe.**
All IAM users created through LZA userSet has access to the console, with login credentials saved in Secrets Manager. More often than not, users without access to console are needed.

**Describe the feature you'd like**
Add support to create an IAM user without console access. For example with flag `consoleAccess: true/false`, or `type: CLI/console` etc.

**Comment by bo1984** [comment]
Hi Sebastian!

Thank you for reaching out. There's a feature request that was already opened on your behalf for this particular issue. I will keep this ticket open in the meantime until this has been implemented and set for public release. Please let us know if you have any additional questions or concerns in the meantime.

**Comment by erwaxler** [comment]
Hi @senyberg , this feature has been included in v1.11.0 released today! You can now define the [disableConsoleAccess](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/interfaces/___packages__aws_accelerator_config_lib_models_iam_config.IUserConfig.html#disableConsoleAccess) property for IAM users created through LZA.

I will go ahead and mark this issue as closed, please continue to raise feature requests through new GitHub issues. Thanks again for your support of the Landing Zone Accelerator!
