### ISSUE TITLE
Deploying specific stack when using LZA pipeline

### ISSUE THREAD

**Issue by andreprawira** [awslabs/landing-zone-accelerator-on-aws#619]
**Is your feature request related to a problem? Please describe.**
The problem is related to how long the pipeline runs, each runs takes 1 hour, and we'd be wasting a lot of time just to make a tiny change

**Describe the feature you'd like**
In the LZA installer pipeline, we have a Deploy stage and in it there is a Customizations step. We are trying to deploy a stack in that step, and we are wondering if its possible to somehow from terminal to bypass the pipeline so i can deploy the stack in the Customizations step, that way we dont have to wait 45 minutes to find out if our yaml is right or wrong

**Additional context**
![image](https://github.com/user-attachments/assets/d6e39593-3c06-4ba6-8242-50b3c4fd0b5b)

**Comment by erwaxler** [comment]
Hi @andreprawira thanks for reaching out to the Landing Zone Accelerator on AWS team. The functionality you described is currently available and documented on this page: https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/developer-guide/scripts/

I'll go ahead and close this issue, thank you for your support of the Landing Zone Accelerator!

**Comment by andreprawira** [comment]
@erwaxler i tried following the doc you linked, i dont know which part i got it wrong, but looks like whenever i run `yarn run ts-node --transpile-only cdk.ts deploy --stage deployment --require-approval any-change --config-dir <my-path> --partition aws --region us-east-1 --account <acc-number> --app cdk.out` i got `error Couldn't find a package.json file in <my-path>` the content of my repository is as below, the codes and the pipelines are working as i expected
![image](https://github.com/user-attachments/assets/c3719723-290e-494e-a2bf-a5ff61e5745f)

**Comment by erwaxler** [comment]
You need to clone the [LZA source code](https://github.com/awslabs/landing-zone-accelerator-on-aws/) locally, not only the configuration files. Then follow the instructions [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/developer-guide/dependencies/) before running commands, specifically:

```
cd source
yarn install
yarn build
```

**Comment by andreprawira** [comment]
@erwaxler hmm i see, i have to speak with our internal team because they have integrated the lza source code with our products into a single service catalog portfolio, its very convenient, so when the accelerator pipeline is created, we just download the config files in the config bucket and voila

but then it doenst come with the package.json

**Comment by richardkeit** [comment]
That's something for you to take up with your internal team most likely @andreprawira

At the end of the day, they are both Git repos meant to be in source control separately.

For the workflow you're trying to achieve, it's "possible" but not advisable. What will likely happen is someone will do a "git add -A" and then wonder why their repo is bloated.
