### ISSUE TITLE
Issue with Snapshot testing (not updated)

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#624]
**Describe the bug**
Snapshot tests are failing due to release of 1.10.

**To Reproduce**
Run `yarn test` from the source directory

**Expected behavior**
Snapshot tests pass

**Please complete the following information about the solution:**

- [X] Version: 1.10.0

**Screenshots**
Nil
 
**Additional context**
Following https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/developer-guide/features/#snapshot-testing I created this PR https://github.com/awslabs/landing-zone-accelerator-on-aws/pull/611 . Unfort the tests still fail.

**Comment by richardkeit** [comment]
Hi @bo1984 , @erwaxler ,

After the 1.10.1 release, there is still the issue where the automated_tests workflow runs against the main branch and not the feature branch.

This is evident from this action run https://github.com/awslabs/landing-zone-accelerator-on-aws/actions/runs/11946584954.

The action completes a check per this log: https://github.com/awslabs/landing-zone-accelerator-on-aws/actions/runs/11946584954/job/33301174026#step:2:67
This references this commit [d8fe87d61cf8dc8fea255753bf93ffd24fae6d76](https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/d8fe87d61cf8dc8fea255753bf93ffd24fae6d76) which is on main.

This was acknowledged https://github.com/awslabs/landing-zone-accelerator-on-aws/pull/611#issuecomment-2459908526,  please resolve this so we can continue to submit pull requests and not get the ❌ on the builds (as they aren't related to the code changes).

Do let me know if my understanding is wrong

**Comment by erwaxler** [comment]
Hey @richardkeit , thanks for bringing attention to this. I was out of office for the last few weeks and was unable to get that fix in before we released v1.10.1. I'm working on this now and will keep this issue updated regarding the release in which I expect this fix to be available.

**Comment by richardkeit** [comment]
Thank you @erwaxler , as released - happy to close

Hope you have some time off this end of year period 🎉

**Comment by erwaxler** [comment]
Thanks @richardkeit , same to you!
