### ISSUE TITLE
Update Subscription Lambda has insufficient privledges

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#646]
**Describe the bug**
Custom resource responsible for configuring centralised logging (kinda important function) silently fails with access denied on KMS encryption

**To Reproduce**
`global-config.yaml`:
~~~yaml
logging:
  cloudwatchLogs:
    enable: true
    encryption:
      useCMK: true
      deploymentTargets:
        organizationalUnits:
          - Root
~~~

**Expected behavior**
No errors and log groups have encryption enabled

**Please complete the following information about the solution:**

- [x] Version: `1.10.0`
- [x] Region: `ap-southeast-2
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs?: No, which raises a question - "should it be?"

**Screenshots**
<img width="1377" alt="Screenshot 2024-11-15 at 10 12 40 AM" src="https://github.com/user-attachments/assets/5f1ef79c-f514-4502-af14-806136532e2c">
<img width="2302" alt="Screenshot 2024-11-15 at 10 11 54 AM" src="https://github.com/user-attachments/assets/9f90c158-4cae-4f15-bf1c-50780ea63e15">

**Additional context**
PR raised for fix, please give it some love 💚 :
- https://github.com/awslabs/landing-zone-accelerator-on-aws/pull/645

PS: This feature doesn't respect the encryption value, ie it **ALWAYS** attempts to encrypt (from what I can see)

**Comment by bo1984** [comment]
@richardkeit just to provide an update, the MR passed and should be included in our 1.11 release. Thanks again for your work and contributions, it is greatly appreciated.
