### ISSUE TITLE
ec2-instance-profile-permissions.zip/index.js TypeError when no Customer Policies defined

### ISSUE THREAD

**Issue by CaylentKittle** [awslabs/landing-zone-accelerator-on-aws#65]
File in question:
/reference/sample-configurations/aws-best-practices/custom-config-rules/ec2-instance-profile-permissions.zip/index.js

**Describe the bug**
If there is no "requiredCustomerPolicies" defined, the "split" of the null string on line 86 fails, and fails to evaluate or set the resource as compliant.

**To Reproduce**
Define no Customer Required Policies in the config. Allow the lambda to run and check the cloud trail logs for the lambda run. You will see the Type Error and the failure to split the null string.

**Expected behavior**
The lambda should see there are no customer defined policies, and just set the resource as compliant if the conditions satisfy. 

**Please complete the following information about the solution:**

- This was tested and found on Version: v1.3.0

Existing code (line 86 - 109 of ec2-instance-profile-permissions.zip/index.js) :
*Note: The Grammar and spelling is also off.

``` const requiredCustomerPolicies = ruleParams.CustomerManagedPolicies.split(',');
    for (const requiredPolicy of requiredCustomerPolicies) {
      if (!requiredPolicy) {
        continue;
      }
      if (!existingPolicyArns.includes(requiredPolicy.trim())) {
        return {
          complianceType: 'NON_COMPLIANT',
          annotation: 'The IAM Role is not having required polocies attached ' + requiredPolicy,
        };
      }
    }
    return {
      complianceType: 'COMPLIANT',
      annotation: 'The resource is compliant',
    };
  } else {
    // TODO retrive from api call
  }

  return {
    complianceType: 'NON_COMPLIANT',
    annotation: 'The resource logging destination is incorrect',
  }; ```


Planned proposed change:

```if ( ruleParams.CustomerManagedPolicies !== undefined ) {
      const requiredCustomerPolicies = ruleParams.CustomerManagedPolicies.split(',');
      for (const requiredPolicy of requiredCustomerPolicies) {
        if (!requiredPolicy) {
          continue;
        }
        if (!existingPolicyArns.includes(requiredPolicy.trim())) {
          return {
            complianceType: 'NON_COMPLIANT',
            annotation: 'The IAM Role does not have the required Customer Managed policies attached ' + requiredPolicy,
          };
        }
      }
    } else {
      return {
        complianceType: 'COMPLIANT',
        annotation: 'No Customer Managed Policy defined. The resource is compliant',
      }
    }
  }```


Cloudtrail output:

```{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'split' of undefined",
    "stack": [
        "TypeError: Cannot read property 'split' of undefined",
        "    at evaluateCompliance (/var/task/index.js:86:73)",
        "    at Runtime.exports.handler (/var/task/index.js:23:28)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
} ```

**Comment by awsclemj** [comment]
Hello,

The LZA team has chosen to remove this custom config rule code from our sample configuration. If you are still using the config rule in question in your environment, you may update the underlying code as you've suggested and repackage the zip file in your configuration repository.

We thank you very much for reporting the issue and your support of the LZA solution!
