### ISSUE TITLE
Fix AWS inspector vulnerabilities CWE-502,1321

### ISSUE THREAD

**Issue by bantl23** [awslabs/landing-zone-accelerator-on-aws#657]
**Describe the bug**
Fix CWE-502,1321 -- Deserialization of untrusted object

**To Reproduce**
AWS Inspector marks about 33 index.js (lambda functions) files as High code vulnerability

**Expected behavior**
AWS Inspector does not find an issue with those index.js files.

**Please complete the following information about the solution:**

- [ v1.9.2] Version: [e.g. v1.5.1]
- [us-east-1 ] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [n/a] If the answer to the previous question was yes, are the changes available on GitHub?
- [no] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
![Screenshot 2024-11-22 160003](https://github.com/user-attachments/assets/9fbb7c47-d3f3-455a-8543-b20427925e7a)

**Additional context**
N/A

**Comment by nagmesh** [comment]
Hello, 

Thank you for your interest in LZA. We scan code in sample config under latest branch but do not scan older versions as underlying runtimes like node14 are deprecated and cannot be launched.

I think those vulnerabilities are based on older code for [ec2-intance-profile-permissions](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/6b2323307ef85dcccc2c67944674617125c0c06a/reference/sample-configurations/lza-sample-config-cn/custom-config-rules/ec2-instance-profile-permissions.zip) and [attach-ec2-instance-profile](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/release/v1.4.3/reference/sample-configurations/aws-best-practices/custom-config-rules/attach-ec2-instance-profile.zip).

If the code is still the same you can try to wrap try/catch to every JSON.parse call so if current code is 
```nodejs
const invokingEvent = JSON.parse(event.invokingEvent);
```

Then change it to 
```nodejs
let invokingEvent;
try {
  invokingEvent = JSON.parse(event.invokingEvent);
} catch (error) {
  console.error('Error parsing invokingEvent:', error);
  throw new Error('Invalid invokingEvent format');
}
```

Repeat that for every location where JSON.parse is present and that should mitigate the issue. 

Hope that helps!

**Comment by bantl23** [comment]
Thanks for your response, that was it.
