### ISSUE TITLE
Add support for the .gz format for logs streaming to S3 bucket via LZA central logging

### ISSUE THREAD

**Issue by NdemeraS** [awslabs/landing-zone-accelerator-on-aws#660]
**Is your feature request related to a problem? Please describe.**

With the central logging feature of the LZA, when logs are streamed from Firehose to S3, they do not have the .gz extension explicitly added to the files. It appears that Amazon Athena requires that the logs have this extensions otherwise the queries cannot be run

**Describe the feature you'd like**

Add an option within the [LZA configuration](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/interfaces/___packages__aws_accelerator_config_lib_models_global_config.ICloudWatchLogsConfig.html) to specify the format of the logs in S3

**Comment by erwaxler** [comment]
Hi @NdemeraS , this has been included in v1.11.0 of the Landing Zone Accelerator which was released today. I will go ahead and close this issue, thanks for your support of the Landing Zone Accelerator!
