### ISSUE TITLE
Cleanup Script Fails

### ISSUE THREAD

**Issue by farmerbean** [awslabs/landing-zone-accelerator-on-aws#67]
**Describe the bug**
The Cleanup script from https://catalog.workshops.aws/landing-zone-accelerator/en-US/cleanup fails to run correctly due to bad commands in the userdata script used to deploy the ec2 instance in the cloudformation stack

**To Reproduce**
Download and run the cloudformation stack as per the instructions and watch the automation fail

**Expected behavior**
The ec2 instance runs and deletes all the necessary resources

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```bash

# Set region
yum install -y jq
region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
export AWS_REGION=$region

if [[ "false" == "true" ]]; then
  deleteFlag="--installer-delete true"
else
  deleteFlag=""
fi

if [[ "false" == "true" ]]; then
  repoFlag="--delete-config-repo true"
else
  repoFlag=""
fi

# Setup logging
logFile='/var/log/landing-zone-accelerator-on-aws-cleanup'
yum install -y amazon-cloudwatch-agent
echo '{
        "agent": {
                "run_as_user": "root"
        },
        "logs": {
                "logs_collected": {
                        "files": {
                                "collect_list": [
                                        {
                                                "file_path": "/var/log/landing-zone-accelerator-on-aws-cleanup",
                                                "log_group_name": "landing-zone-accelerator-on-aws-cleanup",
                                                "log_stream_name": "{instance_id}",
                                                "retention_in_days": 90
                                        }
                                ]
                        }
                }
        },
        "metrics": {
                "metrics_collected": {
                        "statsd": {
                                "metrics_aggregation_interval": 0,
                                "metrics_collection_interval": 10,
                                "service_address": ":8125"
                        }
                }
        }
}' > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
systemctl start amazon-cloudwatch-agent

yum install -y git &>>$logFile

if ! [ -d "landing-zone-accelerator-on-aws" ]; then
  git clone https://github.com/awslabs/landing-zone-accelerator-on-aws.git &>>$logFile
fi

cd landing-zone-accelerator-on-aws/source &>>$logFile
##### broken because you're in source/ already
nodeVersion=$(grep "@types/node" 'source/packages/@aws-accelerator/accelerator/package.json' | awk '{print $2}' | sed 's/"//g' | awk -F. '{print $1}')

if [ -z $nodeVersion ]; then
  nodeVersion=16
fi

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. /.nvm/nvm.sh &>>$logFile
nvm install $nodeVersion &>>$logFile

npm install yarn -g &>>$logFile

yarn install &>>$logFile
##### broken because you're in source/ already
cd source/packages/@aws-accelerator/tools/ &>>$logFile
yarn run --verbose ts-node --transpile-only uninstaller.ts --installer-stack-name AWSAccelerator-InstallerStack --ignore-termination-protection true --full-destroy true $deleteFlag $deleteRepo --partition aws --delete-data --ignore-termination-protection --delete-bootstraps true --delete-pipelines &>>$logFile
/opt/aws/bin/cfn-signal -e 0 --stack LZA-Cleanup-Stack --resource CleanupEC2 --region eu-west-1

```

- [x] Region: [e.g. us-west-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by johnraws** [comment]
Hello @farmerbean, Thank you for reaching out regarding the cleanup script for the LZA workshop. The issues you have encountered as part of the cleanup process have been resolved in a new release of the Workshop. The LZA Workshop now utilizes a single account deployment that will allow the environment to be managed as part of the Workshop and not require a user to create their own LZA environment. The previous steps, including the updated cleanup scripts, are now included as part of the [(Optional) LZA Advanced Labs](https://catalog.workshops.aws/landing-zone-accelerator/en-US/workshop-advanced) section of the workshop. If you are still encountering any errors, please do not hesitate to reopen this issue or create a new issue if it is not related to this request.
