### ISSUE TITLE
mandatoryAccounts name cannot be changed - Unable to find mandatory account

### ISSUE THREAD

**Issue by bpauwels** [awslabs/landing-zone-accelerator-on-aws#675]
**Describe the bug**
In the `accounts-config.yaml`, it says "We recommend you do not change mandatory account names".
If you change them regardlessly, the Build stage fails with the following errors:
```
Unable to find mandatory account with name Management.
Unable to find mandatory account with name Audit.
Unable to find mandatory account with name LogArchive.
```

**To Reproduce**
Change mandatory account names

**Expected behavior**
Account names are changed. If that's not possible, change the comment in accounts-config.yaml

**Please complete the following information about the solution:**

- [ ] Version: 1.10.1

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Athanasii** [comment]
If not using Control Tower, you must first create an organization, and ensure the [mandatory accounts](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/mandatory-accounts.html) are present.
