### ISSUE TITLE
Failed to delete old Endpoint VPC after an endpoint VPC CIDR change

### ISSUE THREAD

**Issue by sdzhangtao** [awslabs/landing-zone-accelerator-on-aws#678]
**Describe the bug**
After a CIDR change to Endpoint VPC, pipeline will create a new Endpoint VPC since this change will not be an update. So a new Endpoint VPC must be created and old one deleted.
The new Endpoint VPC was successfully created. However the old Endpoint VPC was failed to delete. The delete was partial succesful, the transit gateway association, transit gateway subnet was successfully deleted. However, the subnets that will host the interface endpoints was not deleted. The error indicates that there are dependency errors.

**To Reproduce**
Update the endpoint VPC CIDR, rerun the pipeline, and there  will be one more endpoint VPCs, both with name Enpoint. A new one and old one not deleted. And there are error messages in pipeline cloudwatch logs

**Expected behavior**
New Endpoint VPC created and old Enpoint VPC deleted.

**Please complete the following information about the solution:**

- [ ] Version: v1.10.1

- [ ] Region: ca-central-1
- [ ] Were there any errors in the CloudWatch Logs?
There are errors indicating failed to delete subnets due to dependency error

**Comment by richardkeit** [comment]
Hi @sdzhangtao ,

This is documented as the expected behaviour with suggested way to deploy modifications [Managing resource dependencies](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/managing-resource-dependencies.html)

**Comment by sdzhangtao** [comment]
Thanks so much for the reference. Good to know, obviously an update to a VPC providing shared services will incur a down time because of multiple pipeline runs or multiple CLI commands. 
CLI commands would make the process faster, however, not providing an audit trail with pipeline runs. Eventually the local configuration change should be commited to config repo

**Comment by richardkeit** [comment]
Yes, that's more or less the "development" flow most people use.
Pipeline runs while provide an audit trail, the developer experience isn't appealing.

It's a consideration to use a seperate AWS Organization for development processes and then commit the working final to the "production" Organization.

**Comment by richardkeit** [comment]
Hi @sdzhangtao ,

Can you please closed the issue if this has been resolved?
