### ISSUE TITLE
topics in snsTopics has incorrect indentation in documentation

### ISSUE THREAD

**Issue by ashmeetp** [awslabs/landing-zone-accelerator-on-aws#68]
https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#snsTopics

snsTopics:
  depoymentTargets:
    organizationalUnits:
      - Root
    topics:
      - name: Security
        emailAddresses:
          - SecurityNotifications@example.com

topics definition indentation needs to be aligned with depoymentTargets. This example causes build stage failure.

**Comment by erwaxler** [comment]
@ashmeetp Thank you for your interest in Landing Zone Accelerator on AWS! Thank you for identifying this, this will be resolved in our next upcoming release. I will keep this issue open until the documentation has been updated.

**Comment by erwaxler** [comment]
Hi @ashmeetp, this has been resolved with the release of version 1.3.2 so I'll be closing this issue.
