### ISSUE TITLE
Code Pipeline fails in the Security Stage when adding a new account with configurations security-config enabled

### ISSUE THREAD

**Issue by insignias** [awslabs/landing-zone-accelerator-on-aws#8]
**Describe the bug**

Code Pipeline fails in the Security Stage when adding a new account with configurations in security-config.yaml enabled. It fails only for the new account I do not see any error for already created account:

`AWSAccelerator-SecurityStack-753133502924-us-east-1 | 15/25 | 6:58:48 PM | CREATE_FAILED        | Custom::GuardDutyCreatePublishingDestinationCommand | GuardDutyPublishingDestination/Resource/Default (GuardDutyPublishingDestination52AE4412) Received response status [FAILED] from custom resource. Message returned: InvalidInputException: The request was rejected because you do not have the required iam:GetRole permission.`

**To Reproduce**
1. Deploy AWSAccelerator Pipeline
2. After the deployment is successful add a new Account in the accounts-config.yaml
3. Enable the security-config.yaml with AWS Best practices
4. Deploy again

**Expected behavior**
The Pipeline should complete successfully with the new account setup and security-configs enabled.

**Please complete the following information about the solution:**

- [ ] Version: [v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: [us-east-1]
- [ ] Was the solution modified from the version published on this repository? Yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No, it's in my code commit repository
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs?  `Received response status [FAILED] from custom resource. Message returned: InvalidInputException: The request was rejected because you do not have the required iam:GetRole permission. at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 6cb560f3-e78b-40f8-b0b1-8aaee6f2613a)`

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by hickeydh-aws** [comment]
Hey Samir,

As changes were made to the code outside of the most recent Landing Zone Accelerator version, we have no way of knowing if the changes made are affecting the deployment of resources. If this is reproducible with the current version of the Landing Zone Accelerator, not using custom code, please feel free to re-open this issue.
