### ISSUE TITLE
Incorrect deployment instructions

### ISSUE THREAD

**Issue by vveselov** [awslabs/landing-zone-accelerator-on-aws#81]
**Describe the bug**
1. When you follow the README.md for the deployment the command fails due to the generated template.json exceeds the size limit. Workaround - create s3 bucket, copy the template to s3, then use --template-url https://....

2. Then create-template fails with the following error:
An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [AcceleratorQualifier, ManagementAccountId, ManagementAccountRoleName] do not exist in the template

**To Reproduce**
Get fresh account. Follow the README.md instructions

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: (SO0199) Landing Zone Accelerator on AWS. Version 1.3.1.

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? no
- [x] If the answer to the previous question was yes, are the changes available on GitHub? no changes
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? - yes
- [x] Were there any errors in the CloudWatch Logs? no

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by awsclemj** [comment]
Hello,

We have updated the [installation instructions](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md#4-deploy-the-installer-stack) in our latest README release. Thank you for the feedback!
