### ISSUE TITLE
Please version your documentation website

### ISSUE THREAD

**Issue by roncanepa** [awslabs/landing-zone-accelerator-on-aws#85]
**Is your feature request related to a problem? Please describe.**
Having the [documentation](https://awslabs.github.io/landing-zone-accelerator-on-aws/index.html) available is great but it really needs to be versioned, please.  Every time you deploy a release, the prior release's docs get wiped out and replaced by the current release, which makes it very difficult.  I know that I can build the yarn docs locally but this feels like something I shouldn't have to do. I saw there was a recent UI update and I was hoping that this feature would also be included but I didn't see a way to do so. I fully intend to keep pace with LZA releases as much as possible but there's always going to be a lag time between a release and my ability to update our LZA to the latest.

**Describe the feature you'd like**
LZA reference doc website needs to be able to toggle between LZA versions so that docs don't get wiped out by every new release.

**Additional context**
N/A

**Comment by awsclemj** [comment]
Hello, and thank you for providing this feedback!

Our documentation site is now versioned. You can navigate to previous versions of the solution's configuration reference by appending the version number to the URL. For example, to navigate to v1.3.0 documentation, you can use https://awslabs.github.io/landing-zone-accelerator-on-aws/v1.3.0.

Thank you!

**Comment by frankscalzo** [comment]
@awsclemj 

thanks for this Jimmy i noticed 1.4.0 docs are blown out when you go to them on mac / chrome but 1.30 look fine
