### ISSUE TITLE
Add support for tags on AccountConfig

### ISSUE THREAD

**Issue by jblaplace-mrnf** [awslabs/landing-zone-accelerator-on-aws#91]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
I would like to be able to add some Tags to accounts created by LZA upon account creation.

**Additional context**
Being able to properly tag my account upon creation would allow me to perform custom automation specifically around being able to identify a set of accounts that related on to the other based on their tags.

**Comment by awsclemj** [comment]
Closing this feature request as we are already tracking this feature in our internal project management pipeline.
