### ISSUE TITLE
ServiceCatalog::PortfolioPrincipalAssociation Issue

### ISSUE THREAD

**Issue by blackpioter** [awslabs/landing-zone-accelerator-on-aws#97]
**Describe the bug**
Issue while running AWSAccelerator-PrepareStack

**To Reproduce**
Deploy AWSAccelerator

**Expected behavior**
AWSAccelerator-PrepareStack passes green.

**Please complete the following information about the solution:**

- [x] Version: v1.3.2
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? no

- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [x] Were there any errors in the CloudWatch Logs? no

**Screenshots**
![image](https://user-images.githubusercontent.com/8004647/225881353-dab68fc1-5db8-4085-900f-b29568432248.png)

**Comment by crissupb** [comment]
Thank you for your interest in the Landing Zone Accelerator.  If you could answer a couple of follow-up questions that would help in understanding what may be causing the issue.
Which AWS region are you deploying the solution to?
Has ControlTower been enabled and does the ControlTower console show any errors?
Can you attach a copy of the CloudWatch log entries from the Log Group that starts with this name `/aws/lambda/AWSAccelerator-PrepareSta-CustomGetPortfolioId-Cust-`?

**Comment by blackpioter** [comment]
@crissupb 
Region I'm trying to deploy is us-east-1.

ControlTower is enabled. It automatically loads on eu-west-2 region.
When I try to switch to ControlTower in us-east-1 I get the error shown on the screenshot.
![Screenshot 2023-03-20 at 09 54 40](https://user-images.githubusercontent.com/8004647/226291507-34f9dc9e-733f-4f71-ad94-26bbfa8cf10b.png)

Here are the logs from Log Group:

[log-events-viewer-result.csv](https://github.com/awslabs/landing-zone-accelerator-on-aws/files/11015901/log-events-viewer-result.csv)

**Comment by crissupb** [comment]
The LZA solution needs to be deployed in the same home region as Control Tower.  Based on the console error it would appear that the home region for Control Tower is not us-east-1.  This would explain why the solution is unable to find the service catalog portfolio id for Control Tower.
