### ISSUE TITLE
Tag Handling

### ISSUE THREAD

**Issue by farmerbean** [awslabs/landing-zone-accelerator-on-aws#99]
**Is your feature request related to a problem? Please describe.**
We are tagging every resource we're creating through LZA because AWS good practice. However, due to the number of resources, and the number of tags, our config files are becoming a little .. tag heavy.

**Describe the feature you'd like**
Can we push all the tags to a job at the end of our config, or tag afterwards, or a tagging module, or use the CDK rather than the yaml, or anything apart from hundreds of lines of yaml that's just repeated tags

**Additional context**
please and thank you.

**Comment by erwaxler** [comment]
@farmerbean This feature has been included in our latest v1.5.0 release with documentation available [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html#tags), I'll go ahead and close the issue. Thank you for raising this!

**Comment by anthony-sarkis-pwc** [comment]
This issue has not been resolved
